updated smtpd.c, test-indimail-mta
1. smtpd.c: sanitized variable names for badmailfrom, badrcptto,
   blackholedrcpt, blackholedsender, spamignore
2. smtpd.c: removed blachole*pattern, spamignorepattern
3. test-indimail-mta: added tests for goodrcpt, goodrcptpatterns

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.72 2024-02-23 01:31:31+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.73 2024-02-23 21:42:56+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
 testuser=tuser
+blockeduser=blocked
 outarchive=outarchive
 incarchive=incarchive
 myuid=$(id -u)
@@ -161,6 +162,7 @@ do_cleanup_failed()
 		$testdir/tcpclient.smtp $testdir/.vacation.dir/* $testdir/.vacation.msg \
 		$testdir/$user/Maildir/new/* $testdir/$testuser/Maildir/new/* \
 		$testdir/$testuser/Maildir/.Quarantine $testdir/$testuser/Maildir/.Spam \
+		$testdir/$blockeduser/Maildir \
 		$qmaildir/alias/Maildir/new/* $qmaildir/autoturn/$vdomain/Maildir/new/* \
 		$qmaildir/autoturn/$vdomain/Maildir/cur/* $sysconfdir/users $testdir/variables
 	sudo /bin/rm -f  $cntrldir/mailarch $cntrldir/accesslist $cntrldir/from.envrules \
@@ -294,6 +296,9 @@ remove_mail()
 	if [ -d $testdir/$testuser/Maildir ] ; then
 		find $testdir/$testuser/Maildir -type f -exec /bin/rm -f {} \;
 	fi
+	if [ -d $testdir/$blockeduser/Maildir ] ; then
+		find $testdir/$blockeduser/Maildir -type f -exec /bin/rm -f {} \;
+	fi
 }
 
 shutdown_svscan()
@@ -337,6 +342,9 @@ setup_maildir()
 	if [ -d $testdir/$testuser/Maildir ] ; then
 		find $testdir/$testuser/Maildir -type f -exec /bin/rm -f {} \;
 	fi
+	if [ -d $testdir/$blockeduser/Maildir ] ; then
+		find $testdir/$blockeduser/Maildir -type f -exec /bin/rm -f {} \;
+	fi
 	if [ -d $testdir/$incarchive ] ; then
 		find $testdir/$incarchive/Maildir -type f -exec /bin/rm -f {} \;
 	fi
@@ -354,6 +362,7 @@ setup_maildir()
 		mkdir -p $testdir/$testuser/Maildir/$i
 		mkdir -p $testdir/$testuser/Maildir/.Quarantine/$i
 		mkdir -p $testdir/$testuser/Maildir/.Spam/$i
+		mkdir -p $testdir/$blockeduser/Maildir/$i
 		mkdir -p $testdir/blackholed/Maildir/$i
 		mkdir -p $testdir/$incarchive/Maildir/$i
 		mkdir -p $testdir/$outarchive/Maildir/$i
@@ -370,6 +379,8 @@ setup_assign()
 	echo "+$user-:$user:$myuid:$mygid:$testdir/$user:-::"
 	echo "=$testuser:$testuser:$myuid:$mygid:$testdir/$testuser:::"
 	echo "+$testuser-:$testuser:$myuid:$mygid:$testdir/$testuser:-::"
+	echo "=$blockeduser:$blockeduser:$myuid:$mygid:$testdir/$blockeduser:::"
+	echo "+$blockeduser-:$blockeduser:$myuid:$mygid:$testdir/$blockeduser:-::"
 	echo "=$outarchive:$outarchive:$myuid:$mygid:$testdir/$outarchive:::"
 	echo "+$outarchive-:$outarchive:$myuid:$mygid:$testdir/$outarchive:-::"
 	echo "=$incarchive:$incarchive:$myuid:$mygid:$testdir/$incarchive:::"
@@ -510,8 +521,6 @@ setup_config()
 	echo ./Maildir/                           > $cntrldir/defaultdelivery
 	echo TLSv1_2:TLSv1_3                      > $cntrldir/tlsclientmethod
 	echo TLSv1_2:TLSv1_3                      > $cntrldir/tlsservermethod
-	echo blocked@$HOSTNAME                    > $cntrldir/badmailfrom
-	echo blocked@$HOSTNAME                    > $cntrldir/badrcptto
 	echo blackholed@$HOSTNAME                 > $cntrldir/blackholedsender
 	echo blackholed@$HOSTNAME                 > $cntrldir/blackholedrcpt
 	echo 10                                   > $cntrldir/timeoutremote
@@ -2726,7 +2735,7 @@ test_smtp_accesslist()
 			printf "\r  testing SMTP RECIPIENT accesslist using wildmat succeeded %44s [%.4f sec]\n" " " $secs
 		else
 			tcount=$(expr $tcount + 1)
-			printf "\r  testing SMTP RECIPIENT accesslist using REGEXP succeeded %45s [%.4f sec]\n" " " $secs
+			printf "\r  testing SMTP RECIPIENT accesslist using REGEXP  succeeded %44s [%.4f sec]\n" " " $secs
 		fi
 		print_pct
 	else
@@ -2753,10 +2762,10 @@ test_smtp_accesslist()
 		secs=$(echo $t1 $t2 sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		if [ $1 -eq 0 ] ; then
 			tcount=$(expr $tcount + 1)
-			printf "\r  testing SMTP SENDER accesslist using wildmat succeeded %47s [%.4f sec]\n" " " $secs
+			printf "\r  testing SMTP SENDER    accesslist using wildmat succeeded %44s [%.4f sec]\n" " " $secs
 		else
 			tcount=$(expr $tcount + 1)
-			printf "\r  testing SMTP SENDER accesslist using REGEXP succeeded %48s [%.4f sec]\n" " " $secs
+			printf "\r  testing SMTP SENDER    accesslist using REGEXP  succeeded %44s [%.4f sec]\n" " " $secs
 		fi
 		print_pct
 	else
@@ -3547,7 +3556,7 @@ test_blocked()
 {
 	t1=$(date +"%s.%4N")
 	case $1 in
-		1|3|5|7)
+		1|3|5|7|9|10|11|12)
 		swaks -S --to blocked@$HOSTNAME --from $user@$HOSTNAME --server 127.0.0.1 --port $smtp_port >$tmpdir/swaks.$$
 		;;
 		2|4|6|8)
@@ -3573,6 +3582,11 @@ test_blocked()
 			ret=1
 		fi
 		;;
+		9|10|11|12)
+		check_mail $testdir/$blockeduser/Maildir
+		ret=$?
+		/bin/rm -f $cntrldir/goodrcptto $cntrldir/goodrcptpatterns
+		;;
 	esac
 	if [ $ret -eq 0 ] ; then
 		t2=$(date +"%s.%4N")
@@ -3594,6 +3608,14 @@ test_blocked()
 			printf "\r  testing badrcptpatterns   wildmat succeeded %58s [%.4f sec]\n" " " $secs
 		elif [ $1 -eq 8 ] ; then
 			printf "\r  testing badmailpatterns   wildmat succeeded %58s [%.4f sec]\n" " " $secs
+		elif [ $1 -eq 9 ] ; then
+			printf "\r  testing goodrcptto    exact match succeeded %58s [%.4f sec]\n" " " $secs
+		elif [ $1 -eq 10 ] ; then
+			printf "\r  testing goodrcptto    regex match succeeded %58s [%.4f sec]\n" " " $secs
+		elif [ $1 -eq 11 ] ; then
+			printf "\r  testing goodrcptto        wildmat succeeded %58s [%.4f sec]\n" " " $secs
+		elif [ $1 -eq 12 ] ; then
+			printf "\r  testing goodrcpttpatterns wildmat succeeded %58s [%.4f sec]\n" " " $secs
 		fi
 		print_pct
 	else
@@ -3616,8 +3638,17 @@ test_blocked()
 			echo "  testing badrcptpatterns wildmat match failed [$secs sec]"
 		elif [ $1 -eq 8 ] ; then
 			echo "  testing badmailpatterns wildmat match failed [$secs sec]"
+		elif [ $1 -eq 9 ] ; then
+			printf "\r  testing goodrcptto exact match failed [%.4f sec]\n" $secs
+		elif [ $1 -eq 10 ] ; then
+			printf "\r  testing goodrcptto regex match failed [%.4f sec]\n" $secs
+		elif [ $1 -eq 11 ] ; then
+			printf "\r  testing goodrcptto wildmat match failed [%.4f sec]\n" $secs
+		elif [ $1 -eq 12 ] ; then
+			printf "\r  testing goodrcptpatterns wildmat failed [%.4f sec]\n" $secs
 		fi
 		(
+		echo "l1=$l1, ret=$ret"
 		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		)|less
@@ -3674,7 +3705,7 @@ test_blackholed()
 		secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
 		if [ $# -eq 0 ] ; then
 			tcount=$(expr $tcount + 1)
-			printf "\r  testing blackholedrcpt succeeded %69s [%.4f sec]\n" " " $secs
+			printf "\r  testing blackholedrcpt   succeeded %67s [%.4f sec]\n" " " $secs
 		else
 			tcount=$(expr $tcount + 1)
 			printf "\r  testing blackholedsender succeeded %67s [%.4f sec]\n" " " $secs
@@ -6606,14 +6637,38 @@ do_svscan_without_svscanlog()
 	# hide ip
 	test_hide_host_ip
 
+	sudo svc -a $servicedir/smtpd/log
+	echo blocked@$HOSTNAME > $cntrldir/badmailfrom
+	echo blocked@$HOSTNAME > $cntrldir/badrcptto
 	test_blocked 1 #badrcptto
 	test_blocked 2 #badmailfrom
+
+	echo blocked@$HOSTNAME > $cntrldir/goodrcptto
+	test_blocked 9 #goodrcptto exact match
+	#/bin/rm -f $cntrldir/goodrcptto
+
+	echo 1 > $servicedir/smtpd/variables/QREGEX
+	echo block.*@$HOSTNAME > $cntrldir/goodrcptto
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
+	test_blocked 10 #goodrcptto regex match
+
+	echo 0 > $servicedir/smtpd/variables/QREGEX
+	echo block*@$HOSTNAME > $cntrldir/goodrcptto
+	sudo svc -r $servicedir/smtpd
+	sleep 1
+	test_blocked 11 #goodrcptto wildmat
+
+	echo block*@$HOSTNAME > $cntrldir/goodrcptpatterns
+	test_blocked 12 #goodrcptpatterns wildmat
+	/bin/rm -f $cntrldir/goodrcptpatterns
+
 	/bin/rm -f $cntrldir/badmailfrom
 	/bin/rm -f $cntrldir/badrcptto
 	echo block*@$HOSTNAME > $cntrldir/badmailpatterns
 	echo block*@$HOSTNAME > $cntrldir/badrcptpatterns
-	test_blocked 7 #badrcptto
-	test_blocked 8 #badmailfrom
+	test_blocked 7 #badrcptpatterns
+	test_blocked 8 #badmailpatterns
 
 	echo 0 > $servicedir/smtpd/variables/QREGEX
 	echo block*@$HOSTNAME > $cntrldir/badmailfrom
@@ -6652,6 +6707,7 @@ do_svscan_with_svscanlog()
 	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
 	test_svscan_log
 	test_svscan_run
+	sleep $sleep_int
 	test_smtps "mail using SMTPS by tcpserver"
 	test_svscan_shutdown
 
@@ -8877,6 +8933,8 @@ display_tests()
 	echo "test svscan autoscan"
 	echo "test svscan subreaper feature"
 	echo "test blocking (badmailfrom, badrcptto)"
+	echo "test blocking (badmailfrompatterns, badrcptpatterns)"
+	echo "test unblocking (goodrcpt, goodrcptpatterns)"
 	echo "test blachole (blackholedrcpt, blackholedsender)"
 	echo "test SPF"
 	echo "test DKIM using dkim, qmail-dkim"
@@ -8918,7 +8976,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=308
+	total_tests=312
 fi
 failed=0
 do_setup
@@ -8988,6 +9046,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.73  2024-02-23 21:42:56+05:30  Cprogrammer
+# added tests for goodrcpt, goodrcptpatterns
+#
 # Revision 1.72  2024-02-23 01:31:31+05:30  Cprogrammer
 # added tests for badmailpatterns, badrcptpatterns
 #
