reduce script test timings

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.28 2023-10-07 01:29:06+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.29 2023-10-07 08:43:39+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -56,7 +56,7 @@ smtp_port=2050
 qmqp_port=2628
 qmtp_port=2209
 smtp_socket=$testdir/run/smtpd
-sleep_int=2
+sleep_int=0.5
 HOSTNAME=$(uname -n)
 domainkey_dir=$cntrldir/domainkeys
 real_domain_rsa2048=/etc/indimail/control/domainkeys/argos.indimail.org/argos
@@ -74,7 +74,7 @@ do_cleanup_failed()
 	fi
 	svpid=$(sed -n '$p' $servicedir/.svscan.pid 2>/dev/null)
 	if [ -n "$svpid" ] ; then
-		shutdown_svscan $svpid
+		shutdown_svscan
 		sleep $sleep_int
 	else
 		smtp_pid=$(/bin/ps -ef|grep $smtp_port|grep qmail-smtpd|awk '{print $2}')
@@ -129,7 +129,7 @@ check_mail_count()
 		if [ $mcount -eq $2 ] ; then
 			break
 		fi
-		sleep 1
+		sleep 0.5
 		count=$(expr $count + 1)
 		if [ $count -gt 10 ] ; then
 			echo "check_mail_count: count=$count: Failed to receive Mail" 1>&2
@@ -165,9 +165,9 @@ check_mail()
 			fi
 			break
 		fi
-		sleep 1
+		sleep 0.5
 		count=$(expr "$count" + 1)
-		if [ $count -gt 5 ] ; then
+		if [ $count -gt 10 ] ; then
 			echo "check_mail: Failed to receive Mail" 1>&2
 			return 1
 		fi
@@ -201,9 +201,9 @@ check_mail_header()
 			mail_file=$(ls -lt $dir/new|head -2|tail -1|awk '{print $9}')
 			break
 		fi
-		sleep 1
+		sleep 0.5
 		count=$(expr "$count" + 1)
-		if [ $count -gt 5 ] ; then
+		if [ $count -gt 10 ] ; then
 			echo "Failed to receive Mail" 1>&2
 			return 1
 		fi
@@ -233,15 +233,35 @@ remove_mail()
 
 shutdown_svscan()
 {
+	tx1=$(date +"%s.%4N")
+	count=0
+	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
+	while true
+	do
+		if [ -z "$svpid" -o ! -f $servicedir/.svscan.pid ] ; then
+			break
+		fi
+		sudo kill $svpid
+		sleep 0.5
+		count=$(expr $count + 1)
+		if [ $count -gt 10 ] ; then
+			if [ -d $servicedir/.svscan/log ] ; then
+				sudo svc -dx $servicedir/* $servicedir/*/log $servicedir/.svscan/log
+			else
+				sudo svc -dx $servicedir/* $servicedir/*/log
+			fi
+			echo "shutdown_svscan: count=$count: Failed to stop svsan" 1>&2
+			return 1
+		fi
+	done
 	if [ -d $servicedir/.svscan/log ] ; then
-		sudo kill $1
-		sleep 5
 		sudo svc -dx $servicedir/* $servicedir/*/log $servicedir/.svscan/log
 	else
-		sudo kill $1
-		sleep 5
 		sudo svc -dx $servicedir/* $servicedir/*/log
 	fi
+	tx2=$(date +"%s.%4N")
+	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	return 0
 }
 
 setup_maildir()
@@ -1316,10 +1336,10 @@ test_smtp_chk_sender()
 
 test_smtp_surbl()
 {
-	t1=$(date +"%s.%4N")
 	echo /usr/sbin/surblqueue > $servicedir/smtpd/variables/QMAILQUEUE
 	sudo svc -r $servicedir/smtpd
-	sleep $sleep_int
+	sleep 2
+	t1=$(date +"%s.%4N")
 	(
 	echo This is a test message for surbl
 	echo http://surbl-org-permanent-test-point.com/
@@ -1345,15 +1365,15 @@ test_smtp_surbl()
 
 	/bin/rm -f $servicedir/smtpd/variables/QMAILQUEUE $testdir/tmp/swaks.$$
 	sudo svc -r $servicedir/smtpd
-	sleep $sleep_int
+	sleep 2
 	if [ $ret1 -ne 0 -a $ret2 -eq 0 -a $ret4 -eq 0 ] ; then
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-(2*$4))}')
+		secs=$(echo $t1 $t2 $sleep_secs 2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
 		tcount=$(expr $tcount + 2)
 		printf "  testing mail using SMTP for SURBL succeeded %58s [%.4f sec]\n" " " $secs
 	else
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-(2*$4))}')
+		secs=$(echo $t1 $t2 $sleep_secs 2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
 		(
 		echo "l1=$l1"
 		echo "  testing mail using SMTP for SURBL failed [$secs sec]"
@@ -2250,16 +2270,16 @@ test_svscan_run()
 test_svscan_shutdown()
 {
 	t1=$(date +"%s.%4N")
-	shutdown_svscan $svpid # this is 5 sec sleep
+	shutdown_svscan
 	if [ "$(cat $testdir/svscan.out 2>/dev/null)" = "goodbye world" ] ; then
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1-5)}')
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		tcount=$(expr $tcount + 1)
 		printf "  testing svscan shutdown script execution succeeded %51s [%.4f sec]\n" " " $secs
 	else
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1-5)}')
-		shutdown_svscan $svpid
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		shutdown_svscan
 		(
 		echo "  testing svscan shutdown script execution failed [$secs sec]"
 		echo "svscan.log"
@@ -5394,9 +5414,9 @@ log_type=1
 do_without_svscan
 log_type=2
 do_svscan_without_svscanlog
-shutdown_svscan $svpid
+shutdown_svscan
 do_svscan_with_svscanlog
-shutdown_svscan $svpid
+shutdown_svscan
 
 wait
 
@@ -5445,6 +5465,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.29  2023-10-07 08:43:39+05:30  Cprogrammer
+# reduce test time
+#
 # Revision 1.28  2023-10-07 01:29:06+05:30  Cprogrammer
 # added test for hiding IP, host in received headers
 #
