added test for UNIX socket

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -22,6 +22,7 @@ tcpserver=$bindir/tcpserver
 qmail_queue=$sbindir/qmail-queue
 s_nail=/usr/bin/s-nail
 smtp_port=2050
+smtp_socket=$testdir/run/smtpd
 sleep_int=2
 HOSTNAME=$(uname -n)
 
@@ -38,6 +39,9 @@ function do_cleanup_failed()
 	sudo /bin/rm -rf $servicedir
 	sudo /bin/rm -rf $logdir
 	sudo /bin/rm -rf $testdir/queue
+	sudo /bin/rm -rf $testdir/bin
+	sudo /bin/rm -rf $testdir/tmp
+	sudo /bin/rm -rf $testdir/run
 	sudo /bin/rm -rf $testdir/sleep.out
 	sudo /bin/rm -rf $testdir/svscan.out
 	sudo /bin/rm -rf $testdir/tcpclient.smtp
@@ -243,34 +247,35 @@ function test_tcpclient_script()
 	echo "exit 0"
 	) > $testdir/tcpclient.smtp
 	chmod +x $testdir/tcpclient.smtp
-	if [ $# -eq 0 ] ; then
+	case $1 in
+		1)
 		tcpclient -vDHR 0 $smtp_port $testdir/tcpclient.smtp  > $logdir/tcpclient/tcpclient.log 2>&1
-	else
-		tcpclient -n $certdir/servercert.pem -vDHR 0 $smtp_port $testdir/tcpclient.smtp  > $logdir/tcpclient/tcpclient.log 2>&1
-	fi
+		;;
+		2)
+		tcpclient -vDHRn $certdir/servercert.pem 0 $smtp_port $testdir/tcpclient.smtp  > $logdir/tcpclient/tcpclient.log 2>&1
+		;;
+		3)
+		tcpclient -v $smtp_socket $testdir/tcpclient.smtp  > $logdir/tcpclient/tcpclient.log 2>&1
+		;;
+		4)
+		tcpclient -vn $certdir/servercert.pem $smtp_socket $testdir/tcpclient.smtp  > $logdir/tcpclient/tcpclient.log 2>&1
+		;;
+	esac
 	/bin/rm -f $testdir/tcpclient.smtp
 	check_mail
 	if [ $? -eq 0 ] ; then
-		if [ $# -eq 0 ] ; then
-			tcount=$(expr $tcount + 1)
-			echo "  testing mail doing SMTP with tcpclient succeeded"
-		else
-			tcount=$(expr $tcount + 1)
-			echo "  testing mail doing SMTPS with tcpclient succeeded"
-		fi
+		tcount=$(expr $tcount + 1)
+		echo "  testing mail doing SMTP with tcpclient succeeded"
 	else
 		(
-		if [ $# -eq 0 ] ; then
-			echo "  testing mail doing SMTP with tcpclient failed"
-		else
-			echo "  testing mail doing SMTPS with tcpclient failed"
-		fi
+		echo "  testing mail doing SMTPS with tcpclient failed"
 		echo "tcpclient.log.log"
 		cat $logdir/tcpclient/tcpclient.log
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		)
@@ -342,7 +347,7 @@ function test_qmail_inject()
 
 function create_authsmtp()
 {
-	if [ -f /tmp/authsmtp ] ; then
+	if [ -f $testdir/bin/authsmtp ] ; then
 		return 0
 	fi
 	(
@@ -355,15 +360,15 @@ function create_authsmtp()
 	echo "pass=\`echo \$var | cut -d ' ' -f2\`"
 	echo "echo user=\$user 1>&2"
 	echo "echo pass=\$pass 1>&2"
-	echo "exec 4>/tmp/authsmtp.\$\$ 3</tmp/authsmtp.\$\$"
-	echo "/bin/rm -f /tmp/authsmtp.\$\$"
+	echo "exec 4>$testdir/tmp/authsmtp.\$\$ 3<$testdir/tmp/authsmtp.\$\$"
+	echo "/bin/rm -f $testdir/tmp/authsmtp.\$\$"
 	echo "echo \$var | tr [\" \"] [\"\\0\"] 1>&4"
 	echo "if [ \"\$user\" = \"$user@$HOSTNAME\" -a \"\$pass\" = \"abcd12345678\" ] ; then"
 	echo "	exit 0"
 	echo "fi"
 	echo "exec \$*"
-	) >/tmp/authsmtp
-	chmod +x /tmp/authsmtp
+	) > $testdir/bin/authsmtp
+	chmod +x $testdir/bin/authsmtp
 }
 
 function start_tcpserver_smtp()
@@ -388,25 +393,27 @@ function start_tcpserver_smtp()
 		REJECTSPAM=0 \
 		MAKE_SEEKABLE=1 \
 		DKIMVERIFY="" \
-		$tcpserver -u qmaild -g qmail -HR 0 $smtp_port $qmail_smtpd $HOSTNAME /tmp/authsmtp /sbin/sys-checkpwd /bin/false > $logdir/smtpd/smtpd.log 2>&1
-	) &
+		$tcpserver -u qmaild -g qmail -HR 0 $smtp_port $qmail_smtpd $HOSTNAME \
+			$testdir/bin/authsmtp /sbin/sys-checkpwd /bin/false
+	) > $logdir/smtpd/smtpd.log 2>&1 &
 
 	count=0
 	while true
 	do
 		bash -c "</dev/tcp/0/$smtp_port" 2>/dev/null
 		if [ $? -eq 0 ] ; then
-			#echo "Port 0:$smtp_port is alive" 1>&2
 			break
 		fi
 		count=$(expr $count + 1)
 		if [ $count -gt 5 ] ; then
 			echo "Failed to start qmail-smtpd" 1>&2
+			echo "$logdir/smtpd/smtpd.log"
+			cat $logdir/smtpd/smtpd.log
 			exit 1
 		fi
 		sleep 1
 	done
-	smtp_pid=$(/bin/ps -ef|grep $smtp_port|grep -v sudo|grep qmail-smtpd|awk '{print $2}')
+	smtp_pid=$(/bin/ps -ef|grep -v sudo|grep $smtp_port|grep qmail-smtpd|awk '{print $2}')
 	sudo kill -0 $smtp_pid
 	if [ $? -eq 0 ] ; then
 		tcount=$(expr $tcount + 1)
@@ -415,10 +422,50 @@ function start_tcpserver_smtp()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing SMTP on port $smtp_port using tcpserver failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
-		echo "qmail-send.log"
-		cat $logdir/qmail-send/qmail-send.log
+		) |less
+		exit 1
+	fi
+}
+
+function start_tcpserver_smtp_unix()
+{
+	echo
+	echo "Starting SMTP on socket $smtp_socket using tcpserver"
+	(
+	env - \
+		USE_QPWGR=1 \
+		STARTTLS=1 \
+		BIGTODO=0 \
+		CONFSPLIT=23 \
+		QUEUEDIR=$testdir/queue \
+		CONTROLDIR=$cntrldir \
+		CERTDIR=$certdir \
+		ENABLE_CRAM=1 \
+		DEBUG=1 \
+		DEBUG_LOGIN=1 \
+		QMAILQUEUE="$sbindir/qmail-dkim $sbindir/qmail-spamfilter" \
+		SPAMFILTER="/usr/bin/bogofilter -p -d /etc/indimail" \
+		SPAMEXITCODE=0 \
+		REJECTSPAM=0 \
+		MAKE_SEEKABLE=1 \
+		DKIMVERIFY="" \
+		$tcpserver $smtp_socket $qmail_smtpd $HOSTNAME \
+			$testdir/bin/authsmtp /sbin/sys-checkpwd /bin/false
+	) > $logdir/smtpd/smtpd.log 2>&1 &
+
+	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
+	kill -0 $smtp_pid
+	if [ $? -eq 0 ] ; then
+		tcount=$(expr $tcount + 1)
+		echo "  testing SMTP on socket $smtp_socket using tcpserver succeeded"
+	else
+		sudo kill $send_pid $smtp_pid
+		(
+		echo "  testing SMTP on socket $smtp_socket using tcpserver failed"
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
 		) |less
 		exit 1
 	fi
@@ -434,10 +481,11 @@ function test_smtp_tls()
 	else
 		(
 		echo "  testing mail using SMTP with STARTTLS failed"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) |less
@@ -457,10 +505,11 @@ function test_smtp_notls()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing mail using SMTP without STARTTLS failed"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		echo "qmail-send.log"
@@ -483,28 +532,29 @@ function test_smtp_dkimverify()
 	(
 	cat $testdir/mail1.txt|dkim -z 2 -s $dkim_key
 	cat $testdir/mail1.txt && rm -f $testdir/mail1.txt
-	) >/tmp/mail2.txt
-	swaks --data - -n -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port < /tmp/mail2.txt
+	) >$testdir/tmp/mail2.txt
+	swaks --data - -n -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port < $testdir/tmp/mail2.txt
 	check_mail_header "DKIM-Status: good"
 	if [ $? -eq 0 ] ; then
 		tcount=$(expr $tcount + 1)
 		echo "  testing mail using SMTP for DKIM verification succeeded"
-		/bin/rm -f /tmp/mail1.txt /tmp/mail2.txt
+		/bin/rm -f $testdir/tmp/mail1.txt $testdir/tmp/mail2.txt
 	else
 		(
 		echo "  testing mail using SMTP for DKIM verification failed"
 		echo "mail.txt"
-		cat /tmp/mail2.txt
+		cat $testdir/tmp/mail2.txt
 		echo "----------------------------------------"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) | less
 		sudo kill $send_pid $smtp_pid
-		/bin/rm -f /tmp/mail1.txt /tmp/mail2.txt
+		/bin/rm -f $testdir/tmp/mail1.txt $testdir/tmp/mail2.txt
 		exit 1
 	fi
 }
@@ -527,10 +577,11 @@ function test_smtp_bogofilter()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing mail using SMTP for spamfilter failed"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) | less
@@ -549,10 +600,11 @@ function test_smtps()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  $1 failed"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) | less
@@ -573,7 +625,7 @@ function test_smtp_auth_login()
 			sudo kill $send_pid $smtp_pid
 			(
 			echo "  testing mail using SMTP with LOGIN authentication failed"
-			echo "smtpd.log"
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 			) | less
 			exit 1
@@ -582,7 +634,7 @@ function test_smtp_auth_login()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing mail using SMTP with LOGIN authentication failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
 		) | less
 		exit 1
@@ -602,7 +654,7 @@ function test_smtp_auth_plain()
 			sudo kill $send_pid $smtp_pid
 			(
 			echo "  testing mail using SMTP with PLAIN authentication failed"
-			echo "smtpd.log"
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 			) | less
 			exit 1
@@ -611,7 +663,7 @@ function test_smtp_auth_plain()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing mail using SMTP with PLAIN authentication failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
 		) | less
 		exit 1
@@ -632,7 +684,7 @@ function test_smtp_auth_cram_md5()
 			sudo kill $send_pid $smtp_pid
 			(
 			echo "  testing mail using SMTP with CRAM-MD5 authentication failed"
-			echo "smtpd.log"
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 			) | less
 			exit 1
@@ -641,7 +693,7 @@ function test_smtp_auth_cram_md5()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing mail using SMTP with CRAM-MD5 authentication failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
 		) | less
 		exit 1
@@ -686,10 +738,11 @@ function test_qmail_remote_auth()
 			sudo kill $send_pid $smtp_pid
 			(
 			echo "  testing qmail-remote AUTH $1, qmail-remote send+receive failed"
-			echo "smtpd.log"
 			if [ $log_type -eq 1 ] ; then
+				echo "$logdir/smtpd/smtpd.log"
 				cat $logdir/smtpd/smtpd.log
 			elif [ -f $logdir/smtpd/current ] ; then
+				echo "$logdir/smtpd/current"
 				cat $logdir/smtpd/current
 			fi
 			echo "qmail-remote.log"
@@ -701,10 +754,11 @@ function test_qmail_remote_auth()
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing qmail-remote AUTH $1, qmail-remote send+receive failed"
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		echo "qmail-remote.log"
@@ -720,10 +774,11 @@ function test_qmail_remote_auth()
 			sudo kill $send_pid $smtp_pid
 			(
 			echo "  testing BATV signing+verification failed"
-			echo "smtpd.log"
 			if [ $log_type -eq 1 ] ; then
+				echo "$logdir/smtpd/smtpd.log"
 				cat $logdir/smtpd/smtpd.log
 			elif [ -f $logdir/smtpd/current ] ; then
+				echo "$logdir/smtpd/current"
 				cat $logdir/smtpd/current
 			fi
 			echo "qmail-remote.log"
@@ -762,10 +817,11 @@ function test_qmail_remote_routing()
 		echo "  testing qmail-remote SMTPROUTE env qmail-remote send+receive failed"
 		echo "qmail-remote.log"
 		$testdir/qremote.$$
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) | less
@@ -788,10 +844,11 @@ function test_qmail_remote_routing()
 		echo "  testing qmail-remote smtproutes control file qmail-remote send+receive failed"
 		echo "qmail-remote.log"
 		$testdir/qremote.$$
-		echo "smtpd.log"
 		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 		elif [ -f $logdir/smtpd/current ] ; then
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 		fi
 		) | less
@@ -859,14 +916,18 @@ function test_qmail_remote_auth_cdb()
 
 function terminate_smtp()
 {
-	sudo kill $1
-	sleep $sleep_int
+	if [ -n "$1" ] ; then
+		sudo kill $*
+		sleep $sleep_int
+	fi
 }
 
 function terminate_send()
 {
-	sudo kill $1
-	sleep $sleep_int
+	if [ -n "$1" ] ; then
+		sudo kill $*
+		sleep $sleep_int
+	fi
 }
 
 function start_tcpserver_smtps
@@ -882,8 +943,8 @@ function start_tcpserver_smtps
 		QUEUEDIR=$testdir/queue \
 		CONTROLDIR=$cntrldir \
 		CERTDIR=$certdir \
-		$tcpserver -u qmaild -g qmail -HR 0 $smtp_port $qmail_smtpd > $logdir/smtpd/smtpd.log 2>&1
-	) &
+		$tcpserver -u qmaild -g qmail -HR 0 $smtp_port $qmail_smtpd
+	) > $logdir/smtpd/smtpd.log 2>&1 &
 
 	count=0
 	while true
@@ -898,14 +959,14 @@ function start_tcpserver_smtps
 			sudo kill $send_pid
 			(
 			echo "Failed to start qmail-smtpd" 1>&2
-			echo "smtpd.log"
+			echo "$logdir/smtpd/smtpd.log"
 			cat $logdir/smtpd/smtpd.log
 			) | less
 			exit 1
 		fi
 		sleep 1
 	done
-	smtp_pid=$(/bin/ps -ef|grep $smtp_port|grep -v sudo|grep qmail-smtpd|awk '{print $2}')
+	smtp_pid=$(/bin/ps -ef|grep -v sudo|grep $smtp_port|grep qmail-smtpd|awk '{print $2}')
 	sudo kill -0 $smtp_pid
 	if [ $? -eq 0 ] ; then
 		tcount=$(expr $tcount + 1)
@@ -914,7 +975,39 @@ function start_tcpserver_smtps
 		sudo kill $send_pid $smtp_pid
 		(
 		echo "  testing SMTPS on port $smtp_port using tcpserver failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		) | less
+		exit 1
+	fi
+}
+
+function start_tcpserver_smtps_unix
+{
+	echo
+	echo "Starting SMTPS on socket $smtp_socket using tcpserver"
+	(
+	env - \
+		USE_QPWGR=1 \
+		SMTPS=1 \
+		BIGTODO=0 \
+		CONFSPLIT=23 \
+		QUEUEDIR=$testdir/queue \
+		CONTROLDIR=$cntrldir \
+		CERTDIR=$certdir \
+		$tcpserver $smtp_socket $qmail_smtpd
+	) > $logdir/smtpd/smtpd.log 2>&1 &
+
+	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
+	kill -0 $smtp_pid
+	if [ $? -eq 0 ] ; then
+		tcount=$(expr $tcount + 1)
+		echo "  testing SMTPS on socket $smtp_socket using tcpserver succeeded"
+	else
+		sudo kill $send_pid $smtp_pid
+		(
+		echo "  testing SMTPS on socket $smtp_socket using tcpserver failed"
+		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
 		) | less
 		exit 1
@@ -993,7 +1086,7 @@ function start_svscan_without_svscanlog()
 			shutdown_svscan $svpid
 			(
 			echo "  testing service $i startup failed"
-			echo "smtpd.log"
+			echo "$logdir/smtpd/current"
 			cat $logdir/smtpd/current
 			echo "qmail-send.log"
 			cat $logdir/qmail-send/current
@@ -1015,7 +1108,7 @@ function test_stop_smtps()
 		shutdown_svscan $svpid
 		(
 		echo "  testing stopping of service using svc failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1034,7 +1127,7 @@ function test_stop_supervise()
 		shutdown_svscan $svpid
 		(
 		echo "  testing stopping of supervise using svc failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1053,7 +1146,7 @@ function test_restart_service_using_hup()
 		shutdown_svscan $svpid
 		(
 		echo "  testing restarting of supervise by sending hup to svscan failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1074,7 +1167,7 @@ function test_restart_service_using_svc()
 		shutdown_svscan $svpid
 		(
 		echo "  testing restarting of supervise using svc failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1091,7 +1184,7 @@ function test_multilog()
 		shutdown_svscan $svpid
 		(
 		echo "  testing logging using multilog failed"
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1113,7 +1206,7 @@ function test_blocked()
 		else
 			echo "  testing badmailfrom failed"
 		fi
-		echo "smtpd.log"
+		echo "$logdir/smtpd/current"
 		cat $logdir/smtpd/current
 		) | less
 		exit 1
@@ -1513,6 +1606,10 @@ function do_setup()
 	mkdir -p $logdir/svscan
 	mkdir -p $logdir/smtpd
 	(
+	mkdir -p $testdir/tmp
+	chmod 1777 $testdir/tmp
+	mkdir -p $testdir/bin
+	mkdir -p $testdir/run
 	setup_maildir
 	setup_assign
 	setup_config
@@ -1544,14 +1641,25 @@ function do_without_svscan()
 	test_smtp_auth_login
 	test_smtp_auth_plain
 	test_smtp_auth_cram_md5
-	test_tcpclient_script # test smtp using tcpclient
+	test_tcpclient_script 1 # test smtp using tcpclient
 	terminate_smtp $smtp_pid
 
 	# start smtps using tcpserver
 	start_tcpserver_smtps
 	smtp_pid=$(/bin/ps -ef|grep $smtp_port|grep -v sudo|grep qmail-smtpd|awk '{print $2}')
 	test_smtps "testing mail using SMTPS by qmail-smtpd"
-	test_tcpclient_script 1 # test smtps using tcpclient
+	test_tcpclient_script 2 # test smtps using tcpclient
+	terminate_smtp $smtp_pid
+
+	start_tcpserver_smtp_unix
+	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
+	test_tcpclient_script 3 # test smtp using tcpclient
+	echo "Terminating $smtp_pid"
+	terminate_smtp $smtp_pid
+
+	start_tcpserver_smtps_unix
+	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
+	test_tcpclient_script 4 # test smtps using tcpclient
 	terminate_smtp $smtp_pid
 
 	# terminate qmail-send
