added dkim verification test in qmail-smtpd

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,5 +1,8 @@
 #!/bin/sh
 user=mbhangui
+dkim_key=/etc/indimail/control/domainkeys/argos.indimail.org/argos
+#
+#
 testdir=/tmp/qmail-test
 maildir=$testdir/$user/Maildir
 servicedir=$testdir/service
@@ -30,9 +33,39 @@ function check_mail()
 		mcount=$(ls $maildir/new | wc -l)
 		if [ $mcount -gt 0 ] ; then
 			mail_file=$(ls -lt $maildir/new|head -2|tail -1|awk '{print $9}')
-			echo "Got Mail $mail_file"
 			/bin/rm -f $maildir/new/$mail_file
 			return 0
+		fi
+		sleep 1
+		count=$(expr "$count" + 1)
+		echo count=$count
+		if [ $count -gt 5 ] ; then
+			echo "Failed to receive Mail" 1>&2
+			break
+		fi
+	done
+	return 1
+	) >> $logdir/mail/mail.log 2>&1
+}
+
+function check_mail_dkim()
+{
+	count=0
+	ret=1
+	(
+	while true
+	do
+		mcount=$(ls $maildir/new | wc -l)
+		if [ $mcount -gt 0 ] ; then
+			mail_file=$(ls -lt $maildir/new|head -2|tail -1|awk '{print $9}')
+			grep "DKIM-Status: good" $maildir/new/$mail_file
+			if [ $? -eq 0 ] ; then
+				/bin/rm -f $maildir/new/$mail_file
+				return 0
+			else
+				/bin/rm -f $maildir/new/$mail_file
+				return 1
+			fi
 		fi
 		sleep 1
 		count=$(expr "$count" + 1)
@@ -103,6 +136,7 @@ function setup_config()
 	sudo /usr/sbin/svctool --cntrldir=$cntrldir --config=qmail
 	sudo /usr/sbin/svctool --certdir=$certdir    --config=cert \
 		--postmaster=postmaster@$HOSTNAME --common_name=$HOSTNAME
+	sudo chown -R $user $cntrldir
 	echo @$HOSTNAME > $cntrldir/nodnscheck
 	tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16 > $cntrldir/batvkey
 }
@@ -308,6 +342,8 @@ function start_tcpserver_smtp()
 		ENABLE_CRAM=1 \
 		DEBUG=1 \
 		DEBUG_LOGIN=1 \
+		QMAILQUEUE=$sbindir/qmail-dkim \
+		DKIMVERIFY="" \
 		$tcpserver -u qmaild -g qmail -v -HR 0 2025 $qmail_smtpd $HOSTNAME /tmp/authsmtp /sbin/sys-checkpwd /bin/false > $logdir/smtpd/smtpd.log 2>&1
 	) &
 
@@ -361,6 +397,31 @@ function test_smtp_notls()
 		echo "  testing mail using SMTP without STARTTLS succeeded"
 	else
 		echo "  testing mail using SMTP without STARTTLS failed"
+		sudo kill $send_pid $smtp_pid
+		exit 1
+	fi
+}
+
+function test_smtp_dkimverify()
+{
+	(
+	echo "To: $user@$HOSTNAME"
+	echo "From: $user@$HOSTNAME"
+	echo "Subject: Testing DKIM"
+	echo "Date: $(date -R)"
+	echo
+	echo "This is an email to test DKIM"
+	) > $testdir/mail.txt
+	(
+	cat $testdir/mail.txt|dkim -z 2 -s $dkim_key
+	cat $testdir/mail.txt && rm -f $testdir/mail.txt
+	) | swaks --data - -n -S --to $user@$HOSTNAME --server localhost --port 2025
+	check_mail_dkim
+	if [ $? -eq 0 ] ; then
+		tcount=$(expr $tcount + 1)
+		echo "  testing mail using SMTP for DKIM verification succeeded"
+	else
+		echo "  testing mail using SMTP for DKIM verification failed"
 		sudo kill $send_pid $smtp_pid
 		exit 1
 	fi
@@ -1186,6 +1247,7 @@ function do_without_svscan()
 	test_qmail_remote_auth_cdb
 	test_smtp_tls
 	test_smtp_notls
+	test_smtp_dkimverify
 	test_smtp_auth_login
 	test_smtp_auth_plain
 	test_smtp_auth_cram_md5
