added tests for slowq-send

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.55 2023-12-11 18:49:43+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.56 2023-12-15 23:06:18+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -31,6 +31,7 @@ libexecdir=/usr/libexec/indimail
 tmpdir=$testdir/tmp
 qmail_newu=$sbindir/qmail-newu
 qmail_start=$sbindir/qmail-start
+slowq_start=$sbindir/slowq-start
 qmail_inject=$bindir/qmail-inject
 qmail_smtpd=$sbindir/qmail-smtpd
 qmail_qmqpd=$sbindir/qmail-qmqpd
@@ -97,35 +98,23 @@ do_cleanup_failed()
 		if [ -n "$smtp_pid" ] ; then
 			terminate_smtp_qmtp $smtp_pid
 		fi
-		send_pid=$(get_send_pid)
-		if [ -n "$send_pid" ] ; then
-			terminate_send $send_pid
-			sleep $sleep_int
-		fi
+		[ -z "$send_pid" ] && send_pid=$(get_send_pid qmail-send $testdir/queue)
+		terminate_send "$send_pid"
+
+		[ -z "$slowq_pid1" ] && slowq_pid1=$(get_send_pid slowq-send $testdir/slowq1)
+		terminate_send "$slowq_pid1"
+
+		[ -z "$slowq_pid2" ] && slowq_pid2=$(get_send_pid slowq-send $testdir/slowq2)
+		terminate_send "$slowq_pid2"
 	fi
-	sudo /bin/rm -rf $servicedir
-	sudo /bin/rm -rf $logdir
-	sudo /bin/rm -rf $testdir/queue
-	sudo /bin/rm -rf $testdir/domainqueue
-	sudo /bin/rm -rf $testdir/bin
-	sudo /bin/rm -rf $tmpdir
-	sudo /bin/rm -rf $testdir/run
-	sudo /bin/rm -rf $testdir/sleep.out
-	sudo /bin/rm -rf $testdir/svscan.out
-	sudo /bin/rm -rf $testdir/tcpclient.smtp
-	sudo /bin/rm -rf $testdir/.vacation.dir/*
-	sudo /bin/rm -rf $testdir/.vacation.msg
-	sudo /bin/rm -rf $testdir/$user/Maildir/new/*
-	sudo /bin/rm -rf $testdir/$testuser/Maildir/new/*
-	sudo /bin/rm -rf $testdir/$testuser/Maildir/.Quarantine
-	sudo /bin/rm -rf $testdir/$testuser/Maildir/.Spam
-	sudo /bin/rm -rf $qmaildir/alias/Maildir/new/*
-	sudo /bin/rm -rf $qmaildir/autoturn/$vdomain/Maildir/new/* $qmaildir/autoturn/$vdomain/Maildir/cur/*
-	sudo /bin/rm -rf $sysconfdir/users
-	sudo /bin/rm -f  $cntrldir/mailarch
-	sudo /bin/rm -f  $cntrldir/accesslist
-	sudo /bin/rm -f  $cntrldir/from.envrules $cntrldir/badmailfrom.custom
-	sudo /bin/rm -rf $testdir/variables
+	sudo /bin/rm -rf $servicedir $logdir $testdir/queue $testdir/slowq1 $testdir/slowq2 $testdir/qmta $testdir/domainqueue \
+		$testdir/bin $tmpdir $testdir/run $testdir/sleep.out $testdir/svscan.out $testdir/tcpclient.smtp \
+		$testdir/.vacation.dir/* $testdir/.vacation.msg \
+		$testdir/$user/Maildir/new/* $testdir/$testuser/Maildir/new/* \
+		$testdir/$testuser/Maildir/.Quarantine $testdir/$testuser/Maildir/.Spam \
+		$qmaildir/alias/Maildir/new/* $qmaildir/autoturn/$vdomain/Maildir/new/* $qmaildir/autoturn/$vdomain/Maildir/cur/* \
+		$sysconfdir/users $testdir/variables
+	sudo /bin/rm -f  $cntrldir/mailarch $cntrldir/accesslist $cntrldir/from.envrules $cntrldir/badmailfrom.custom
 }
 
 check_mail_count()
@@ -358,18 +347,22 @@ setup_queue()
 {
 	t1=$(date +"%s.%4N")
 	sudo queue-fix -s 23 -b 0 $testdir/queue
-	if [ $? -eq 0 ] ; then
+	ret1=$?
+	if [ $ret1 -ne 0 ] ; then
+		echo "testing create qmail queue failed for $testdir/queue"
+		failed=1
+		exit 1
+	fi
+	sudo queue-fix -r -s 23 -b 0 $testdir/slowq1 && sudo queue-fix -r -s 23 -b 0 $testdir/slowq2
+	ret2=$?
+	if [ $ret2 -eq 0 ] ; then
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		tcount=$(expr $tcount + 1)
-		printf "\r  testing create qmail queue succeeded %65s [%.4f sec]\n" " " $secs
+		printf "\r  testing create qmail queue succeeded for qmail-send, slowq-send %38s [%.4f sec]\n" " " $secs
 		print_pct
 	else
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
-		tcount=$(expr $tcount + 1)
-		printf "\r%118s" " "
-		printf "\r  testing create qmail queue failed [%.4f sec]\n" $secs
+		echo "testing create qmail queue failed for $testdir/slowq1|$testdir/slowq2"
 		failed=1
 		exit 1
 	fi
@@ -616,8 +609,11 @@ test_tcpclient_script()
 	fi
 }
 
-run_qmail_send()
+create_qmail_getpw()
 {
+	if [ -x $testdir/bin/qmail-getpw ] ; then
+		return 0
+	fi
 	(
 	echo "#!/bin/sh"
 	echo "uid=\$(grep \"^\$1\" $testdir/etc/passwd |awk -F: '{print \$3}')"
@@ -634,9 +630,55 @@ run_qmail_send()
 	echo "fi"
 	) > $testdir/bin/qmail-getpw
 	chmod 755 $testdir/bin/qmail-getpw
+	return $?
+}
+
+run_qmail_send()
+{
+	create_qmail_getpw
+	if [ $# -eq 0 -o $# -gt 2 ] ; then
+		echo here1
+		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2 [silent]" 1>&2
+		return 1
+	fi
+	[ $# -eq 2 ] && silent=1 || silent=0
+	if [ "$1" = "qmail-send" ] ; then
+		start_pg=$qmail_start
+		pg1=qmail-send
+		pg2=slowq-send
+		logfn=qmail-send.log
+		queuedir=$testdir/queue
+		todo_proc=0 # not used by qmail-send
+		opt="-s"
+		pcount=6
+	elif [ "$1" = "slowq-send-1" ] ; then
+		start_pg=$slowq_start
+		pg1=slowq-send
+		pg2=qmail-send
+		logfn=slowq1-send.log
+		queuedir=$testdir/slowq1
+		todo_proc=1
+		opt=""
+		pcount=5
+	elif [ "$1" = "slowq-send-2" ] ; then
+		start_pg=$slowq_start
+		pg1=slowq-send
+		pg2=qmail-send
+		logfn=slowq2-send.log
+		queuedir=$testdir/slowq2
+		todo_proc=0
+		opt=""
+		pcount=4
+	else
+		echo here2 [$1]
+		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2 [silent]" 1>&2
+		return 1
+	fi
+	t1=$(date +"%s.%4N")
 	(
-	exec 1>$logdir/qmail-send/qmail-send.log
-	exec 2>$logdir/qmail-send/qmail-send.log
+	mkdir -p $logdir/$pg1
+	exec 1>$logdir/$pg1/$logfn
+	exec 2>$logdir/$pg1/$logfn
 	exec 0<&2
 	sudo env - \
 		PATH=/bin:/usr/sbin \
@@ -646,41 +688,93 @@ run_qmail_send()
 		CERTDIR=$certdir \
 		CONFSPLIT=23 \
 		QMAILGETPW=$testdir/bin/qmail-getpw \
-		QUEUEDIR=$testdir/queue \
+		QUEUEDIR=$queuedir \
 		ASSIGNDIR=$sysconfdir/users \
 		RELAYCLIENT="" \
+		TODO_PROCESSOR=$todo_proc \
 		PASSWD_FILE=$testdir/etc/passwd \
 		QMAILLOCAL=$sbindir/spawn-filter \
 		QMAILREMOTE=$sbindir/spawn-filter \
 		QREMOTE=$sbindir/rd-remote \
-		$qmail_start -s ./Maildir/
+		$start_pg $opt ./Maildir/
 	) &
+	tx1=$(date +"%s.%4N")
+	pid=$(get_send_pid $pg1 $queuedir)
+	if [ "$1" = "qmail-send" ] ; then
+		send_pid=$pid
+	elif [ "$1" = "slowq-send-1" ] ; then
+		slowq_pid1=$pid
+	elif [ "$1" = "slowq-send-2" ] ; then
+		slowq_pid2=$pid
+	fi
+	count=$(ps -ef | grep -E -v $pg2 | grep -E "$pg1|todo-proc|slowq-todo|qmail-lspawn|qmail-rspawn|qmail-clean" | grep $queuedir | wc -l)
+	tx2=$(date +"%s.%4N")
+	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	if [ -n "$pid" -a $pid -gt 0 -a -n "$count" -a $count -eq $pcount ] ; then
+		[ $silent -eq 1 ] && return 0
+		t2=$(date +"%s.%4N")
+		tcount=$(expr $tcount + 1)
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		case "$1" in
+			"qmail-send")
+			printf "\r  testing %-10s startup with external todo-proc succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			;;
+			"slowq-send-1")
+			printf "\r  testing %-10s startup with    todo-processor  succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			;;
+			"slowq-send-2")
+			printf "\r  testing %-10s startup without todo-processor  succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			;;
+		esac
+	else
+		echo "testing $pg1 option ($1) startup failed "$pg1"_pid=$pid, count=$count"
+		echo "$pg1 log"
+		cat $logdir/$pg1/$logfn
+		failed=1
+		exit 1
+	fi
 }
 
 get_send_pid()
 {
 	count=0
+	if [ $# -ne 2 ] ; then
+		echo "get_send_pid qmail-send|slowq-send queuedir" 1>&2
+		return
+	fi
+	pg=$1
+	if [ "$1" = "qmail-send" ] ; then
+		logfn="qmail-send.log"
+	elif [ "$1" = "slowq-send-1" ] ; then
+		logfn="slowq1-send.log"
+	elif [ "$1" = "slowq-send-2" ] ; then
+		logfn="slowq2-send.log"
+	fi
+	sleep_secs=0
 	while true
 	do
-		send_pid=$(/bin/ps -ef | grep qmail-send |grep $testdir |grep -E -v "qmail-clean|grep" | awk '{print $2}')
-		if [ -n "$send_pid" ] ; then
+		pid=$(/bin/ps -ef | grep $pg | grep $2 |grep -E -v "qmail-clean|grep" | awk '{print $2}')
+		if [ -n "$pid" ] ; then
 			break
 		fi
 		sleep 1
 		count=$(expr $count + 1)
 		if [ $count -gt 5 ] ; then
-			if [ -f $logdir/qmail-send/qmail-send.log ] ; then
-				cat $logdir/qmail-send/qmail-send.log 1>&2
-				echo "Failed to start qmail-send" 1>&2
+			if [ -f $logdir/$pg/$logfn ] ; then
+				cat $logdir/$pg/$logfn 1>&2
+				echo "Failed to start $pg" 1>&2
 			fi
 			return 1
 		fi
 	done
-	echo $send_pid
+	echo $pid
 }
 
 test_qmail_inject()
 {
+	# $1 - From
+	# $2 - To
+	# #3 - queuedir
 	for i in 1 2
 	do
 		t1=$(date +"%s.%4N")
@@ -690,35 +784,34 @@ test_qmail_inject()
 			(
 			echo "=$user:$user:$myuid:$mygid:$testdir/$user:::"
 			echo "+$user-:$user:$myuid:$mygid:$testdir/$user:-::"
-			#echo "=blackholed:blackholed:$myuid:$mygid:$testdir/blackholed:::"
-			#echo "+blackholed-:blackholed:$myuid:$mygid:$testdir/blackholed:-::"
 			echo "."
 			) > $sysconfdir/users/assign
 		fi
 		$qmail_newu $sysconfdir/users
 		(
-		echo "From: $2"
-		echo "To: $3"
+		echo "From: $1"
+		echo "To: $2"
 		echo "Subject: Test"
 		echo "Date: $(date -R)"
 		echo
 		echo "Test message"
 		) | env - \
-			QUEUEDIR=$testdir/queue \
+			QUEUEDIR=$3 \
 			QMAILQUEUE=$qmail_queue \
 			CONTROLDIR=$cntrldir \
 			BIGTODO=0 \
 			CONFSPLIT=23 \
-			$qmail_inject $3
+			$qmail_inject $2
 		check_mail
 		if [ $? -eq 0 ] ; then
+			q=$(basename $3)
 			t2=$(date +"%s.%4N")
 			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 			tcount=$(expr $tcount + 1)
 			if [ $i -eq 1 ] ; then
-				printf "\r  testing qmail-inject /etc/passwd user, qmail send+receive succeeded %34s [%.4f sec]\n" " " $secs
+				printf "\r  testing qmail-inject queue %-6s /etc/passwd user, qmail send+receive succeeded %21s [%.4f sec]\n" $q " " $secs
 			else
-				printf "\r  testing qmail-inject qmail-user, qmail send+receive succeeded %40s [%.4f sec]\n" " " $secs
+				printf "\r  testing qmail-inject queue %-6s qmail       user, qmail send+receive succeeded %21s [%.4f sec]\n" $q " " $secs
 			fi
 			print_pct
 		else
@@ -726,9 +819,9 @@ test_qmail_inject()
 			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 			printf "\r%118s\n" " "
 			if [ $i -eq 1 ] ; then
-				echo "  testing qmail-inject /etc/passwd user, qmail send+receive failed [$secs sec]"
+				echo "  testing qmail-inject queue $3 /etc/passwd user, qmail send+receive failed [$secs sec]"
 			else
-				echo "  testing qmail-inject qmail-user, qmail send+receive failed [$secs sec]"
+				echo "  testing qmail-inject queue $3 qmail user, qmail send+receive failed [$secs sec]"
 			fi
 			cat $logdir/qmail-send/qmail-send.log|less
 			failed=1
@@ -3036,9 +3129,7 @@ start_tcpserver_smtps_unix()
 setup_svscan_basic()
 {
 	t1=$(date +"%s.%4N")
-	sudo /bin/rm -rf $servicedir
-	sudo /bin/rm -rf $logdir/smtpd
-	sudo /bin/rm -rf $logdir/qmail-send
+	sudo /bin/rm -rf $servicedir $logdir/smtpd $logdir/qmail-send $logdir/slowq-send
 
 	mkdir -p $servicedir/smtpd/variables
 	mkdir -p $servicedir/smtpd/log
@@ -4109,7 +4200,7 @@ setup_virtual()
 			sudo sh -c "echo $qmaildir/autoturn/$i/Maildir/ > $qmaildir/autoturn/.qmail-$qfn-default"
 			sudo chown -R $u:$g $qmaildir/autoturn/$i $qmaildir/autoturn/.qmail-$qfn-default
 		done
-		send_pid=$(get_send_pid)
+		send_pid=$(get_send_pid qmail-send $testdir/queue)
 		if [ -n "$send_pid" ] ; then
 			sudo kill -1 $send_pid
 		fi
@@ -4122,7 +4213,7 @@ setup_virtual()
 			fi
 		done
 		/bin/rm -rf $qmaildir/autoturn/$vdomain $cntrldir/virtualdomains
-		send_pid=$(get_send_pid)
+		send_pid=$(get_send_pid qmail-send $testdir/queue)
 		if [ -n "$send_pid" ] ; then
 			sudo kill -1 $send_pid
 		fi
@@ -5225,44 +5316,17 @@ test_autoturn()
 	start_tcpserver_smtp 1
 }
 
-do_without_svscan2()
-{
-	printf "\r%118s\n" " "
-	echo "Testing commands run without using svscan"
-	# use qmail-start to start qmail-send
-	run_qmail_send
-	send_pid=$(get_send_pid)
-	if [ $? -ne 0 ] ; then
-		exit 1
-	fi
-	# start smtp using tcpserver
-	start_tcpserver_smtp 4
-	sleep $sleep_int
-
-	setup_virtual 1
-	create_authsmtp
-	#test_maildirserial
-	#test_etrn1
-	#test_etrn2
-	#test_atrn
-	test_autoturn
-	setup_virtual 0
-	echo
-	failed=1
-	exit 1
-}
-
 do_without_svscan()
 {
 	printf "\r%118s\n" " "
 	echo "Testing commands run without using svscan"
-	# use qmail-start to start qmail-send
-	run_qmail_send
-	send_pid=$(get_send_pid)
-	if [ $? -ne 0 ] ; then
-		exit 1
-	fi
-	test_qmail_inject $user $user $user
+	# use qmail-start, slowq-sart to start qmail-send, slowq-send
+	run_qmail_send qmail-send
+	run_qmail_send slowq-send-1
+	run_qmail_send slowq-send-2
+	test_qmail_inject $user $user $testdir/queue
+	test_qmail_inject $user $user $testdir/slowq1
+	test_qmail_inject $user $user $testdir/slowq2
 	setup_assign # restore users/assign
 	test_alias
 
@@ -5367,9 +5431,43 @@ do_without_svscan()
 	test_tcpclient_script 4 # test smtps using tcpclient
 	terminate_smtp_qmtp $smtp_pid
 
-	# terminate qmail-send
-	terminate_send $send_pid
+	# terminate qmail-send, slowq-send
+	terminate_send "$send_pid"
+	terminate_send "$slowq_pid1"
+	terminate_send "$slowq_pid2"
 }
+
+do_without_svscan2()
+{
+	printf "\r%118s\n" " "
+	echo "Testing commands run without using svscan"
+	# use qmail-start, slowq-sart to start qmail-send, slowq-send
+	run_qmail_send qmail-send
+	run_qmail_send slowq-send-1
+	run_qmail_send slowq-send-2
+	test_qmail_inject $user $user $testdir/queue
+	test_qmail_inject $user $user $testdir/slowq1
+	test_qmail_inject $user $user $testdir/slowq2
+	echo
+	failed=1
+	exit 1
+	# start smtp using tcpserver
+	start_tcpserver_smtp 4
+	sleep $sleep_int
+
+	setup_virtual 1
+	create_authsmtp
+	#test_maildirserial
+	#test_etrn1
+	#test_etrn2
+	#test_atrn
+	test_autoturn
+	setup_virtual 0
+	echo
+	failed=1
+	exit 1
+}
+  
 
 test_qmqp()
 {
@@ -7705,7 +7803,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=273
+	total_tests=280
 fi
 failed=0
 do_setup
@@ -7767,6 +7865,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.56  2023-12-15 23:06:18+05:30  Cprogrammer
+# added tests for slowq-send
+#
 # Revision 1.55  2023-12-11 18:49:43+05:30  Cprogrammer
 # added test for qmail-inject domainqueue
 #
