display timings for setup

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.18 2023-09-29 23:39:53+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.19 2023-09-30 13:38:16+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -164,7 +164,6 @@ setup_maildir()
 	fi
 	mkdir -p $cntrldir
 	mkdir -p $sysconfdir/users
-	echo "Creating $maildir" 1>&2
 	for i in cur new tmp
 	do
 		mkdir -p $maildir/$i
@@ -174,7 +173,7 @@ setup_maildir()
 
 setup_assign()
 {
-	echo "Creating $sysconfdir/users/assign" 1>&2
+	t1=$(date +"%s.%4N")
 	(
 	echo "=$user:$user:$myuid:$mygid:$testdir/$user:::"
 	echo "+$user-:$user:$myuid:$mygid:$testdir/$user:-::"
@@ -182,25 +181,98 @@ setup_assign()
 	echo "+$testuser-:$testuser:$myuid:$mygid:$testdir/$testuser:-::"
 	echo "."
 	) > $sysconfdir/users/assign
-	echo "Creating $sysconfdir/users/cdb" 1>&2
 	$qmail_newu $sysconfdir/users
+	if [ $? -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing create assign/user.cdb succeeded %61s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		printf "  testing create assign/user.cdb failed [%.4f sec]\n" $secs
+		exit 1
+	fi
 }
 
 setup_queue()
 {
-	echo "Creating queue in $testdir/queue" 1>&2
+	t1=$(date +"%s.%4N")
 	sudo queue-fix -s 23 -b 0 $testdir/queue
+	if [ $? -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing create qmail queue succeeded %65s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing create qmail queue failed [%.4f sec]\n" $secs
+		exit 1
+	fi
 }
 
 setup_config()
 {
-	echo "Creating default config files in $cntrldir"
+	t1=$(date +"%s.%4N")
+	mkdir -p $testdir/setup
+	(
 	env CONTROLDIR=$cntrldir config-fast $HOSTNAME
 	sudo /usr/sbin/svctool --cntrldir=$cntrldir --config=qmail
-	sudo /usr/sbin/svctool --certdir=$certdir    --config=cert \
-		--postmaster=postmaster@$HOSTNAME --common_name=$HOSTNAME
-	cp /etc/indimail/bogofilter.cf.example $sysconfdir
-	sudo /usr/sbin/svctool --sysconfdir=$sysconfdir --config=bogofilter
+	)>$testdir/setup/setup.log 2>&1
+	if [ $? -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing qmail configuration succeeded %64s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		(
+		printf "  testing qmail configuration failed [%.4f sec]\n" $secs
+		cat $testdir/setup/setup.log
+		) |less
+		exit 1
+	fi
+	if [ ! -f $certdir/servercert.pem ] ; then
+		t1=$(date +"%s.%4N")
+		sudo /usr/sbin/svctool --certdir=$certdir    --config=cert \
+			--postmaster=postmaster@$HOSTNAME --common_name=$HOSTNAME >$testdir/setup/setup.log 2>&1
+		if [ -f $certdir/servercert.pem ] ; then
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+			tcount=$(expr $tcount + 1)
+			printf "  testing create self signed certificate succeeded %53s [%.4f sec]\n" " " $secs
+		else
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+			tcount=$(expr $tcount + 1)
+			(
+			printf "  testing create self signed certificate failed [%.4f sec]\n" $secs
+			cat $testdir/setup/setup.log
+			) |less
+			exit 1
+		fi
+	fi
+	if [ ! -f $sysconfdir/bogofilter.cf ] ; then
+		t1=$(date +"%s.%4N")
+		cp /etc/indimail/bogofilter.cf.example $sysconfdir
+		sudo /usr/sbin/svctool --sysconfdir=$sysconfdir --config=bogofilter
+		if [ -f $sysconfdir/bogofilter.cf ] ; then
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+			tcount=$(expr $tcount + 1)
+			printf "  testing Create bogofilter configuration succeeded %52s [%.4f sec]\n" " " $secs
+		else
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+			tcount=$(expr $tcount + 1)
+			printf "  testing Create bogofilter configuration failed [%.4f sec]\n" $secs
+		fi
+	fi
+	sudo chown -R $user $cntrldir
 	tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16 > $cntrldir/batvkey
 	echo ./Maildir/                           > $cntrldir/defaultdelivery
 	echo TLSv1_2:TLSv1_3                      > $cntrldir/tlsclientmethod
@@ -213,8 +285,6 @@ setup_config()
 	echo @$ext_domain
 	echo @$HOSTNAME
 	)                                         > $cntrldir/nodnscheck
-	sudo chown -R $user $cntrldir
-	ls -l $cntroldir/global_vars
 }
 
 test_tcpclient_script()
@@ -1063,7 +1133,7 @@ test_qmail_remote_auth()
 			t2=$(date +"%s.%4N")
 			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 			tcount=$(expr $tcount + 1)
-			printf "  testing qmail-remote AUTH %-8s, qmail-remote send+receive succeeded %30s [%.4f sec]\n" "$1" " " $secs
+			printf "  testing qmail-remote AUTH %-8s qmail-remote send+receive succeeded %31s [%.4f sec]\n" "$1" " " $secs
 			/bin/rm -f $testdir/qremote.$$
 		else
 			sudo kill $send_pid $smtp_pid
@@ -2382,17 +2452,19 @@ test_recipients()
 do_setup()
 {
 	t1=$(date +"%s.%4N")
-	echo "Starting Setup"
+	if [ -f $certdir/servercert.pem ] ; then
+		echo "Starting Setup (this will take a moment)"
+	else
+		echo "Starting Setup (this will take some time)"
+	fi
 	# basic setup for maildir, assign config and queue
 	sudo /bin/rm -rf $logdir
-	mkdir -p $logdir/setup
 	mkdir -p $logdir/qmail-remote
 	mkdir -p $logdir/mail
 	mkdir -p $logdir/tcpclient
 	mkdir -p $logdir/qmail-send
 	mkdir -p $logdir/svscan
 	mkdir -p $logdir/smtpd
-	(
 	mkdir -p $testdir/tmp
 	chmod 1777 $testdir/tmp
 	mkdir -p $testdir/bin
@@ -2401,7 +2473,6 @@ do_setup()
 	setup_assign
 	setup_config
 	setup_queue
-	) > $logdir/setup/setup.log 2>&1
 }
 
 do_without_svscan()
@@ -2429,10 +2500,10 @@ do_without_svscan()
 	if [ $t -eq 1 ] ; then
 		secs=$(echo $t1x $t3x | awk '{printf("%0.4f\n", $2-$1)}')
 		tcount=$(expr $tcount + 1)
-		printf "Testing filterit internal faster by %2.4f sec than external command succeeded %25s [%.4f sec]" $diff " " $secs
+		printf "  testing filterit internal faster by %2.4f sec than external command succeeded %23s [%.4f sec]" $diff " " $secs
 	else
 		secs=$(echo $t1x $t3x | awk '{printf("%0.4f\n", $2-$1)}')
-		echo "Testing filterit internal faster [$diff sec] than external command failed [$secs sec]"
+		echo "  testing filterit internal faster [$diff sec] than external command failed [$secs sec]"
 	fi
 
 	# start smtp using tcpserver
@@ -2667,7 +2738,7 @@ do_autoresponder()
 		echo "  testing autoresponder [$secs sec]"
 		echo "Expected subject as $reply_subject but got $subject"
 		echo "qmail-send.log"
-		cat $logdir/qmail-send/qmail-send.log
+		cat $logdir/qmail-send/current
 		) |less
 		exit 1
 	fi
@@ -4334,6 +4405,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.19  2023-09-30 13:38:16+05:30  Cprogrammer
+# display timings for setup
+#
 # Revision 1.18  2023-09-29 23:39:53+05:30  Cprogrammer
 # display test time at fixed column
 #
