added test for authdomains, AUTH_ALL env var setting

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.34 2023-10-16 18:38:12+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.35 2023-10-16 20:55:17+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -1218,7 +1218,7 @@ test_smtp_secure_auth()
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		tcount=$(expr $tcount + 1)
-		printf "\r  testing mail using SECURE AUTH SMTP authentication succeeded %41s [%.4f sec]\n" " " $secs
+		printf "\r  testing mail using SECURE  AUTH SMTP authentication succeeded %40s [%.4f sec]\n" " " $secs
 		print_pct
 	else
 		t2=$(date +"%s.%4N")
@@ -1240,7 +1240,6 @@ test_smtp_secure_auth()
 	sleep 2
 
 	# Test REQUIREAUTH
-	echo "$HOSTNAME:127.0.0.1:$smtp_port $user@$HOSTNAME abcd12345678" > $cntrldir/smtproutes
 	t1=$(date +"%s.%4N")
 	# this should fail without using authentication
 	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost \
@@ -1275,7 +1274,77 @@ test_smtp_secure_auth()
 		failed=1
 		exit 1
 	fi
+
 	/bin/rm -f $servicedir/smtpd/variables/REQUIREAUTH
+	sudo svc -r $servicedir/smtpd
+	sleep 2
+
+	# Test authdomains
+	t1=$(date +"%s.%4N")
+	echo "@$HOSTNAME" > $cntrldir/authdomains
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port \
+		--tls-on-connect > $testdir/tmp/swaks.$$ 2>&1
+	ret1=$?
+	l1=$(sed -n 1p < $testdir/tmp/swaks.$$)
+	echo $l1 | grep ".*553 sorry, that domain isn't allowed to be relayed thru this MTA without authentication; no valid cert for gateway #5.7.1" > /dev/null
+	ret2=$?
+	failed=1
+	/bin/rm -f $cntrldir/authdomains
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port \
+		--tls-on-connect
+	check_mail
+	ret3=$?
+
+	if [ $ret1 -ne 0 -a $ret2 -eq 0 -a $ret3 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing mail using authdomains control file succeeded %48s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		(
+		echo "ret1=$ret1, ret2=$ret2, ret3=$ret3, l1=[$l1]"
+		echo "  testing mail using authdomains control file failed [$secs sec]"
+		echo "$logdir/smtpd/current"
+		cat $logdir/smtpd/current
+		)|less
+		failed=1
+		exit 1
+	fi
+
+	# Test AUTH_ALL
+	echo 1 > $servicedir/smtpd/variables/AUTH_ALL
+	sudo svc -r $servicedir/smtpd
+	sleep 2
+	t1=$(date +"%s.%4N")
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port \
+		--tls-on-connect > $testdir/tmp/swaks.$$ 2>&1
+	ret1=$?
+	l1=$(sed -n 1p < $testdir/tmp/swaks.$$)
+	echo $l1 | grep ".*553 sorry, that domain isn't allowed to be relayed thru this MTA without authentication; no valid cert for gateway #5.7.1" > /dev/null
+	ret2=$?
+	if [ $ret1 -ne 0 -a $ret2 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing mail using AUTH_ALL env variable succeeded %51s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1)}')
+		(
+		echo "ret1=$ret1, ret2=$ret2, l1=[$l1]"
+		printf "\r  testing mail using AUTH_ALL env variable failed [$secs sec]"
+		echo "$logdir/smtpd/current"
+		cat $logdir/smtpd/current
+		)|less
+		failed=1
+		exit 1
+	fi
+
+	/bin/rm -f $servicedir/smtpd/variables/AUTH_ALL
 	sudo svc -r $servicedir/smtpd
 	sleep $sleep_int
 }
@@ -2232,7 +2301,7 @@ test_stop_smtps()
 {
 	t1=$(date +"%s.%4N")
 	sudo svc -d $servicedir/smtpd
-	sleep $sleep_int
+	sleep 2
 	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost --port $smtp_port --tls-on-connect 2>/dev/null
 	if [ $? -eq 2 ] ; then
 		t2=$(date +"%s.%4N")
@@ -3940,16 +4009,17 @@ do_svscan_without_svscanlog()
 	setup_svscan_basic
 	start_svscan_without_svscanlog
 	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
+	create_authsmtp
 	test_smtps "mail using SMTPS by qmail-smtpd"
 	test_qmqp
 	test_qmtp
+	test_smtp_secure_auth
 	test_recipients
 	test_smtp_cugmail
 	test_smtp_chk_sender
 	test_smtp_surbl
 	test_autoresponder 0
 	test_qmail_qfilter
-	test_smtp_secure_auth
 	test_stop_smtps
 	test_stop_supervise
 	test_restart_service_using_hup
@@ -5831,6 +5901,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.35  2023-10-16 20:55:17+05:30  Cprogrammer
+# added test for authdomains, AUTH_ALL env variable setting
+#
 # Revision 1.34  2023-10-16 18:38:12+05:30  Cprogrammer
 # added test for SECURE AUTH and REQUIREAUTH
 #
