added test for hiding IP, host in received headers

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.27 2023-10-06 02:23:28+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.28 2023-10-07 01:29:06+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -633,12 +633,12 @@ test_qmail_inject()
 		else
 			t2=$(date +"%s.%4N")
 			secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
-			(
 			if [ $i -eq 1 ] ; then
 				echo "  testing qmail-inject /etc/passwd user, qmail send+receive failed [$secs sec]"
 			else
 				echo "  testing qmail-inject qmail-user, qmail send+receive failed [$secs sec]"
 			fi
+			(
 			cat $logdir/qmail-send/qmail-send.log
 			)|less
 			failed=1
@@ -2957,6 +2957,9 @@ test_maildirserial()
 		failed=1
 		exit 1
 	fi
+	if [ -d $maildir ] ; then
+		find $maildir -type f -exec /bin/rm -f {} \;
+	fi
 }
 
 do_autoresponder()
@@ -3499,10 +3502,10 @@ test_qmqp()
 	else
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $sleep_int $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		echo "  testing qmail-qmqpc, qmail-qmqpd failed [$secs sec]"
 		(
 		echo "body=$body"
 		echo "subject$subject"
-		echo "  testing qmail-qmqpc, qmail-qmqpd failed [$secs sec]"
 		cat $logdir/qmqpd/current
 		)|less
 		failed=1
@@ -3580,6 +3583,68 @@ test_qmtp()
 	fi
 }
 
+test_hide_host_ip()
+{
+	t1=$(date +"%s.%4N")
+	(
+	printf "#!/bin/sh\nexec $envdir ./variables $tcpserver -u qmaild -g qmail -v -HR 127.0.0.1 "
+	printf "$smtp_port env HIDE_HOST=1 $qmail_smtpd $HOSTNAME $testdir/bin/authsmtp "
+	printf "/bin/false 2>&1\n"
+	) >$servicedir/smtpd/run
+	echo 1 > $servicedir/smtpd/variables/SMTPS
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
+	swaks -S --tls-on-connect --to $user@$HOSTNAME --from $user@$HOSTNAME --server 127.0.0.1 --port $smtp_port \
+		--a LOGIN -au $user@$HOSTNAME -ap "abcd12345678" >/dev/null
+	check_mail_header $maildir Received 0
+	if [ -n "$mail_file" ] ; then
+		$e822header -I Received < $maildir/new/$mail_file > $testdir/tmp/header
+		/bin/rm -f $mail_file
+		l1=$(sed -n 1p < $testdir/tmp/header)
+		l2=$(sed -n 2p < $testdir/tmp/header)
+		l3=$(sed -n 4p < $testdir/tmp/header)
+		echo $l1 | grep $HOSTNAME > /dev/null
+		ret1=$?
+		echo $l2 | grep 127.0.0.1 > /dev/null
+		ret2=$?
+		echo $l3 | grep $HOSTNAME > /dev/null
+		ret3=$?
+		echo $l3 | grep 127.0.0.1 > /dev/null
+		ret4=$?
+	else
+		ret1=0
+		ret2=0
+		ret3=0
+		ret4=0
+	fi
+	if [ $ret1 -ne 0 -a $ret2 -ne 0 -a $ret3 -ne 0 -a $ret4 -ne 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_int $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing hide host, ip in received headers succeeded %50s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_int $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		echo "  testing hide host, ip in received heades failed [$secs sec]"
+		(
+		echo "l1=[$l1] (host), l2=[$l2] (ip), l3=[$l3] (host+ip)"
+		echo "ret1=$ret1, ret2=$ret2, ret3=$ret3, ret4=$ret4"
+		echo "header$header"
+		cat $logdir/smtpd/current
+		)|less
+		failed=1
+		exit 1
+	fi
+	(
+	printf "#!/bin/sh\nexec $envdir ./variables $tcpserver -u qmaild -g qmail -v -HR 0 "
+	printf "$smtp_port env HIDE_HOST=1 $qmail_smtpd $HOSTNAME $testdir/bin/authsmtp "
+	printf "/bin/false 2>&1\n"
+	) >$servicedir/smtpd/run
+	/bin/rm -f $servicedir/smtpd/variables/SMTPS
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
+}
+
 do_svscan_without_svscanlog()
 {
 	t1=$(date +"%s.%4N")
@@ -3605,6 +3670,7 @@ do_svscan_without_svscanlog()
 	test_multilog
 	start_new_service
 	remove_new_service
+	test_hide_host_ip
 	test_blocked
 	test_blocked 1
 }
@@ -5379,6 +5445,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.28  2023-10-07 01:29:06+05:30  Cprogrammer
+# added test for hiding IP, host in received headers
+#
 # Revision 1.27  2023-10-06 02:23:28+05:30  Cprogrammer
 # updated test script
 #
