updated test script

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.52 2023-12-09 23:52:06+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.54 2023-12-11 00:17:11+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -479,6 +479,7 @@ setup_config()
 	echo "atrn.dom"
 	) >> $cntrldir/rcpthosts
 	sort -u $cntrldir/rcpthosts -o $cntrldir/rcpthosts
+	/bin/rm -f $cntrldir/libindimail
 }
 
 test_tcpclient_script()
@@ -927,6 +928,41 @@ start_tcpserver_smtp()
 		failed=1
 		exit 1
 	fi
+}
+
+start_tcpserver_smtp_turn()
+{
+	mkdir -p $testdir/smtpd/variables
+	/bin/rm -f $testdir/smtpd/variables/*
+	echo 1                 > $testdir/smtpd/variables/USE_QPWGR
+	echo 0                 > $testdir/smtpd/variables/BIGTODO
+	echo 23                > $testdir/smtpd/variables/CONFSPLIT
+	echo $testdir/queue    > $testdir/smtpd/variables/QUEUEDIR
+	echo $cntrldir         > $testdir/smtpd/variables/CONTROLDIR
+	echo $sysconfdir/users > $testdir/smtpd/variables/ASSIGNDIR
+	echo $smtp_port        > $testdir/smtpd/variables/PORT
+	echo 1                 > $testdir/smtpd/variables/MAKE_SEEKABLE
+	echo "$qmail_queue"    > $testdir/smtpd/variables/QMAILQUEUE
+	(
+	sudo envdir -c $testdir/smtpd/variables \
+		$tcpserver -l $HOSTNAME -HR 0 $smtp_port sh -c "setuidgid -g qmail qmaild $qmail_smtpd;$testdir/bin/qmta"
+	) > $logdir/smtpd/smtpd.log 2>&1 &
+
+	count=0
+	tx1=$(date +"%s.%4N")
+	while true
+	do
+		smtp_pid=$(/bin/ps -ef|grep -v sudo|grep $smtp_port|grep qmail-smtpd|awk '{print $2}')
+		if [ -n "$smtp_pid" ] ; then
+			break
+		fi
+		sleep 1
+	done
+	tx2=$(date +"%s.%4N")
+	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	sudo kill -0 $smtp_pid
+	ret=$?
+	return $ret
 }
 
 start_tcpserver_smtp_unix()
@@ -2828,6 +2864,9 @@ terminate_smtp_qmtp()
 	if [ -n "$1" ] ; then
 		sudo kill $*
 		sleep $sleep_int
+		sleep_secs=$sleep_int
+	else
+		sleep_secs=0
 	fi
 }
 
@@ -5003,7 +5042,6 @@ test_atrn()
 		chmod 600 $sysconfdir/fetchmailrc
 		echo 1 > $testdir/smtpd/variables/ODMR
 		terminate_smtp_qmtp $smtp_pid
-		/bin/rm -f $cntrldir/libindimail
 		start_tcpserver_smtp 4
 		s2=$sleep_secs
 		sleep 1.1 # maildirserial has resolution of 1 seconds
@@ -5061,11 +5099,87 @@ test_atrn()
 		)|less
 		failed=1
 		/bin/rm -f $testdir/variables/ODMR $cntrldir/smtproutes $cntrldir/atrnaccess
-		sudo $svctool --cntrldir=$cntrldir --fixsharedlibs >/dev/null
 		exit 1
 	fi
-	sudo $svctool --cntrldir=$cntrldir --fixsharedlibs >/dev/null
 	/bin/rm -f $testdir/variables/ODMR $cntrldir/smtproutes $cntrldir/atrnaccess
+}
+
+test_autoturn()
+{
+	t1=$(date +"%s.%4N")
+
+	sudo queue-fix -m -s 23 -b 0 $testdir/qmta
+	echo "$HOSTNAME:QUEUEDIR=$testdir/qmta,CONTROLDIR=$cntrldir,BIGTODO=0,CONFSPLIT=23" > $cntrldir/domainqueue
+
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server 127.0.0.1 --port $smtp_port \
+		>$tmpdir/swaks.$$
+	ret1=$?
+	/bin/rm -f $cntrldir/domainqueue
+	(
+	echo "env - \\"
+	echo "	PATH=/bin:/usr/sbin \\"
+	echo "	QUEUEDIR=$testdir/qmta \\"
+	echo "	BIGTODO=0 \\"
+	echo "	CONFSPLIT=23 \\"
+	echo "	USE_QPWGR=1 \\"
+	echo "	CONTROLDIR=$cntrldir \\"
+	echo "	QMAILGETPW=$testdir/bin/qmail-getpw \\"
+	echo "	ASSIGNDIR=$sysconfdir/users \\"
+	echo "	PASSWD_FILE=$testdir/etc/passwd \\"
+	echo "	$sbindir/qmta-send ./Maildir/"
+	) > $testdir/bin/qmta
+	chmod +x $testdir/bin/qmta
+	terminate_smtp_qmtp $smtp_pid
+	ret2=$?
+	s1=$sleep_secs
+	start_tcpserver_smtp_turn
+	ret3=$?
+	s2=$sleep_secs
+	(
+	echo "#!/bin/sh"
+	echo "exec 0<&6"
+	echo "exec 1>&7"
+	echo "read key"
+	echo "greeting=\$(echo \$key | awk '{print \$1}')"
+	echo "if [ \$greeting -ne 220 ] ; then"
+	echo "	echo \"Greeting failed\" 1>&2"
+	echo "	printf \"QUIT\r\n\""
+	echo "fi"
+	echo "printf \"QUIT\r\n\""
+	echo "read key"
+	echo "echo \$key 1>&2"
+	echo "exit 0"
+	) > $testdir/tcpclient.smtp
+	chmod +x $testdir/tcpclient.smtp
+
+	# trigger AUTOTURN
+	tcpclient -vDHR 127.0.0.1 $smtp_port $testdir/tcpclient.smtp > $logdir/tcpclient/tcpclient.log 2>&1
+	ret4=$?
+	check_mail
+	ret5=$?
+	s3=$sleep_secs
+	/bin/rm -f $testdir/bin/qmta
+	if [ $ret1 -eq 0 -a $ret2 -eq 0 -a $ret3 -eq 0 -a $ret4 -eq 0 -a $ret5 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $s1 $s2 $s3 | awk '{printf("%0.4f\n", $2-$1-$3-$4-$5)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing AUTOTURN service succeeded %67s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		printf "\r%118s\n" " "
+		echo "ret1=$ret1, ret2=$ret2, ret3=$ret3, ret4=$ret4, ret5=$ret5"
+		echo "  testing AUTOTURN service failed [$secs sec]"
+		(
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		echo "$logdir/qmail-send/qmail-send.log"
+		cat $logdir/qmail-send/qmail-send.log
+		)|less
+		failed=1
+		exit 1
+	fi
+	terminate_smtp_qmtp $smtp_pid
+	start_tcpserver_smtp 1
 }
 
 do_without_svscan2()
@@ -5080,8 +5194,6 @@ do_without_svscan2()
 	fi
 	# start smtp using tcpserver
 	start_tcpserver_smtp 4
-	# start qmtp using tcpserver
-	start_tcpserver_qmtp
 	sleep $sleep_int
 
 	setup_virtual 1
@@ -5089,7 +5201,8 @@ do_without_svscan2()
 	#test_maildirserial
 	#test_etrn1
 	#test_etrn2
-	test_atrn
+	#test_atrn
+	test_autoturn
 	setup_virtual 0
 	echo
 	failed=1
@@ -5162,6 +5275,7 @@ do_without_svscan()
 	test_etrn1
 	test_etrn2
 	test_atrn
+	test_autoturn
 	setup_virtual 0
 	terminate_smtp_qmtp $qmtp_pid
 
@@ -7548,7 +7662,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=262
+	total_tests=273
 fi
 failed=0
 do_setup
@@ -7569,7 +7683,8 @@ fi
 secs=0.0
 printf "\r%118s\n" " "
 for i in QMAILQUEUE envdir tcpclient-tcp tcpclient-ssl tcpclient-unix \
-	maildirdeliver bounce 822header 822body qmail-getpw nodnscheck rd-remote
+	maildirdeliver bounce 822header 822body qmail-getpw nodnscheck rd-remote \
+	maildirsmtp qmta-send fetchmail
 do
 	tcount=$(expr $tcount + 1)
 	printf "\r  implicit test %20s succeeded %57s [%.4f sec]\n" $i " " $secs
@@ -7609,6 +7724,12 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.54  2023-12-11 00:17:11+05:30  Cprogrammer
+# remove libindimail control file
+#
+# Revision 1.53  2023-12-10 22:18:13+05:30  Cprogrammer
+# added test for AUTOTURN
+#
 # Revision 1.52  2023-12-09 23:52:06+05:30  Cprogrammer
 # added tests for ETRN and ATRN
 #
