added tests for maildirserial, serialsmtp, sreialqmtp

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.25 2023-10-04 21:01:42+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.26 2023-10-05 23:38:27+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -9,6 +9,7 @@ myuid=$(id -u)
 mygid=$(id -g)
 real_domain=argos.indimail.org
 srs_domain=srs.indimail.org
+vdomain=virtual.indimail.org
 ext_domain=gmail.com
 dkim_key=/etc/indimail/control/domainkeys/$real_domain/$(echo $real_domain | cut -d. -f1)
 #
@@ -69,6 +70,7 @@ do_cleanup_failed()
 	if [ $failed -eq 0 ] ; then
 		return 0
 	fi
+	svpid=$(sed -n '$p' $servicedir/.svscan.pid 2>/dev/null)
 	if [ -n "$svpid" ] ; then
 		shutdown_svscan $svpid
 		sleep $sleep_int
@@ -78,7 +80,7 @@ do_cleanup_failed()
 			smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
 		fi
 		if [ -n "$smtp_pid" ] ; then
-			terminate_smtp $smtp_pid
+			terminate_smtp_qmtp $smtp_pid
 			sleep $sleep_int
 		fi
 		send_pid=$(get_send_pid)
@@ -103,7 +105,38 @@ do_cleanup_failed()
 	sudo /bin/rm -rf $testdir/$testuser/Maildir/.Quarantine
 	sudo /bin/rm -rf $testdir/$testuser/Maildir/.Spam
 	sudo /bin/rm -rf $qmaildir/alias/Maildir/new/*
+	sudo /bin/rm -rf $qmaildir/alias/virtual/new/* $qmaildir/alias/virtual/cur/*
 	sudo /bin/rm -rf $sysconfdir/users
+}
+
+check_mail_count()
+{
+	no_delete=0
+	tx1=$(date +"%s.%4N")
+	if [ $# -ne 2 ] ; then
+		echo "check_mail_count dir count" 1>&2
+		failed=1
+		exit 1
+	fi
+	dir=$1
+	count=0
+	ret=1
+	while true
+	do
+		mcount=$(ls $dir/new/* $dir/cur/* 2>/dev/null | wc -l)
+		if [ $mcount -eq $2 ] ; then
+			break
+		fi
+		sleep 1
+		count=$(expr $count + 1)
+		if [ $count -gt 10 ] ; then
+			echo "check_mail_count: count=$count: Failed to receive Mail" 1>&2
+			return 1
+		fi
+	done
+	tx2=$(date +"%s.%4N")
+	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	return 0
 }
 
 check_mail()
@@ -175,6 +208,7 @@ check_mail_header()
 	done
 	tx2=$(date +"%s.%4N")
 	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	sudo chmod 644 $dir/new/$mail_file
 	header=$(822header -I $str < $dir/new/$mail_file)
 	if [ $# -eq 3 ] ; then
 		if [ $3 -eq 1 ] ; then
@@ -648,7 +682,6 @@ create_qmail_remote()
 start_tcpserver_smtp()
 {
 	t1=$(date +"%s.%4N")
-	echo
 	echo "Starting SMTP on port $smtp_port using tcpserver"
 	(
 	sudo env - \
@@ -744,6 +777,53 @@ start_tcpserver_smtp_unix()
 		echo "  testing SMTP on socket $smtp_socket using tcpserver failed [$secs sec]"
 		echo "$logdir/smtpd/smtpd.log"
 		cat $logdir/smtpd/smtpd.log
+		)|less
+		failed=1
+		exit 1
+	fi
+}
+
+start_tcpserver_qmtp()
+{
+	t1=$(date +"%s.%4N")
+	echo "Starting QMTP on port $qmtp_port using tcpserver"
+	(
+	sudo env - \
+		USE_QPWGR=1 \
+		BIGTODO=0 \
+		STARTTLS=1 \
+		CONFSPLIT=23 \
+		QUEUEDIR=$testdir/queue \
+		CONTROLDIR=$cntrldir \
+		QMAILQUEUE="$sbindir/qmail-queue" \
+		$tcpserver -u qmaild -g qmail -HR 0 $qmtp_port $qmail_qmtpd
+	) > $logdir/qmtpd/qmtpd.log 2>&1 &
+
+	count=0
+	tx1=$(date +"%s.%4N")
+	while true
+	do
+		qmtp_pid=$(/bin/ps -ef|grep -v sudo|grep $qmtp_port|grep qmail-qmtpd|awk '{print $2}')
+		if [ -n "$qmtp_pid" ] ; then
+			break
+		fi
+		sleep 1
+	done
+	tx2=$(date +"%s.%4N")
+	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	sudo kill -0 $qmtp_pid
+	if [ $? -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing QMTP on port %4d qmtp_port using tcpserver succeeded %40s [%.4f sec]\n" $qmtp_port " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		(
+		echo "  testing SMTP on port $smtp_port using tcpserver failed [$secs sec]"
+		echo "$logdir/smtpd/qmtpd.log"
+		cat $logdir/qmtpd/qmtpd.log
 		)|less
 		failed=1
 		exit 1
@@ -1680,7 +1760,7 @@ test_qmail_remote_smtps()
 	fi
 }
 
-terminate_smtp()
+terminate_smtp_qmtp()
 {
 	if [ -n "$1" ] ; then
 		sudo kill $*
@@ -2679,6 +2759,7 @@ do_setup()
 	mkdir -p $logdir/qmail-send
 	mkdir -p $logdir/svscan
 	mkdir -p $logdir/smtpd
+	mkdir -p $logdir/qmtpd
 	mkdir -p $testdir/tmp
 	chmod 1777 $testdir/tmp
 	mkdir -p $testdir/bin
@@ -2714,6 +2795,164 @@ srs_setup()
 		/bin/rm -f $cntrldir/srs_alwaysrewrite
 		/bin/rm -f $cntrldir/virtualdomains
 		sudo /bin/rm -f $qmaildir/alias/.qmail-srs-default
+	fi
+}
+
+virtual_setup()
+{
+	if [ $1 -eq 1 ] ; then
+		echo "$vdomain:virtual"  > $cntrldir/virtualdomains
+		if [ ! -d $qmaildir/alias/virtual ] ; then
+			sudo maildirmake $qmaildir/alias/virtual
+		fi
+		sudo chmod -R 0755 $qmaildir/alias/virtual
+		sudo chown -R alias:qmail $qmaildir/alias/virtual
+		sudo sh -c "echo "$qmaildir/alias/virtual/" > $qmaildir/alias/.qmail-virtual-default"
+		send_pid=$(get_send_pid)
+		if [ -n "$send_pid" ] ; then
+			sudo kill -1 $send_pid
+		fi
+	else
+		sudo /bin/rm -rf $qmaildir/alias/.qmail-virtual-default $qmaildir/alias/virtual
+		send_pid=$(get_send_pid)
+		if [ -n "$send_pid" ] ; then
+			sudo kill -1 $send_pid
+		fi
+	fi
+}
+
+test_maildirserial()
+{
+	for i in 1 2 3 4 5
+	do
+		t1=$(date +"%s.%4N")
+		(
+		echo "From: $user@$hostname"
+		echo "To: $user@$vdomain"
+		echo "Subject: Test No $i $$"
+		echo "Date: $(date -R)"
+		echo
+		echo "Test Message $i $$"
+		) | sudo $setuidgid -g qcerts $user env - \
+			QUEUEDIR=$testdir/queue \
+			QMAILQUEUE=$qmail_queue \
+			CONTROLDIR=$cntrldir \
+			BIGTODO=0 \
+			CONFSPLIT=23 \
+			$qmail_inject -f$user@$HOSTNAME $user@$vdomain
+		check_mail_header $qmaildir/alias/virtual Subject 0
+		s1=$sleep_secs
+		if [ -n "$header" ] ; then
+			subj_header=$header
+		else
+			subj_header=""
+		fi
+		check_mail_header $qmaildir/alias/virtual Delivered-To 0
+		s2=$sleep_secs
+		total=$(echo $s1 $s2 | awk '{printf("%0.4f\n", $1+$2)}')
+		if [ -n "$header" ] ; then
+			dto_header=$header
+		else
+			dto_header=""
+		fi
+		if [ -n "$mail_file" ] ; then
+			body=$(822body < $qmaildir/alias/virtual/new/$mail_file)
+			sudo sed -i "s/virtual-$user@$vdomain/virtual-$user@$HOSTNAME/" \
+				$qmaildir/alias/virtual/new/$mail_file
+			sudo mv $qmaildir/alias/virtual/new/$mail_file \
+				$qmaildir/alias/virtual/cur/$mail_file
+		fi
+		if [ -n "$mail_file" -a "$dto_header" = "Delivered-To: virtual-$user@$vdomain" -a "$subj_header" = "Subject: Test No $i $$"  -a "$body" = "Test Message $i $$" ] ; then
+			continue
+		else
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+			(
+			echo "  testing qmail-inject virtual user, qmail send+receive failed [$secs sec]"
+			echo "$logdir/smtpd/smtpd.log"
+			cat $logdir/smtpd/smtpd.log
+			echo "$logdir/qmail-send/qmail-send.log"
+			cat $logdir/qmail-send/qmail-send.log
+			)|less
+			failed=1
+			exit 1
+		fi
+	done
+	check_mail_count $qmaildir/alias/virtual 5
+	ret=$?
+	if [ $ret -eq 0 -a $mcount -eq 5 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $total $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing qmail-inject virtual user, qmail send+receive succeeded %38s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $total $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		echo "  testing qmail-inject virtual user, qmail send+receive failed [$secs sec]"
+		(
+		echo "ret=$ret, mcount1=$mcount"
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		echo "$logdir/qmail-send/qmail-send.log"
+		cat $logdir/qmail-send/qmail-send.log
+		)|less
+		failed=1
+		exit 1
+	fi
+
+	sudo mkdir $qmaildir/alias/virtual/bak
+	sudo cp -rp $qmaildir/alias/virtual/cur $qmaildir/alias/virtual/bak
+	sleep 1
+	t1=$(date +"%s.%4N")
+	echo "$HOSTNAME:127.0.0.1:$smtp_port $user@$HOSTNAME abcd12345678" > $cntrldir/smtproutes
+	sudo chown -R $user $qmaildir/alias/virtual
+	tcpclient 0 $smtp_port maildirserial -t1209600 $qmaildir/alias/virtual "virtual-" \
+		serialsmtp "virtual-" serialsmtp >$testdir/tmp/tcpclient.log 2>&1
+	check_mail_count $maildir 5
+	ret=$?
+	if [ $ret -eq 0 -a $mcount -eq 5 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing maildirserial, serialsmtp succeeded %58s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		echo "  testing maildirserial, serialsmtp failed [$secs sec]"
+		(
+		echo "ret=$ret, mcount=$mcount"
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		echo "$logdir/qmail-send/qmail-send.log"
+		cat $logdir/qmail-send/qmail-send.log
+		)|less
+		failed=1
+		exit 1
+	fi
+	sudo rm -rf $qmaildir/alias/virtual/new
+	sudo mv $qmaildir/alias/virtual/bak $qmaildir/alias/virtual/new
+	tcpclient 0 $smtp_port maildirserial -t1209600 $qmaildir/alias/virtual "virtual-" \
+		serialqmtp "virtual-" serialsmtp >$testdir/tmp/tcpclient.log 2>&1
+	check_mail_count $maildir 5
+	ret=$?
+	if [ $ret -eq 0 -a $mcount -eq 5 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "  testing maildirserial, serialqmtp succeeded %58s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		echo "  testing maildirserial, serialqmtp failed [$secs sec]"
+		(
+		echo "ret=$ret, mcount=$mcount"
+		echo "$logdir/smtpd/qmtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		echo "$logdir/qmail-send/qmail-send.log"
+		cat $logdir/qmail-send/qmail-send.log
+		)|less
+		failed=1
+		exit 1
 	fi
 }
 
@@ -3131,8 +3370,9 @@ do_without_svscan()
 	fi
 
 	# start smtp using tcpserver
+	echo
 	start_tcpserver_smtp
-	smtp_pid=$(/bin/ps -ef|grep $smtp_port|grep -v sudo|grep qmail-smtpd|awk '{print $2}')
+	start_tcpserver_qmtp
 	sleep $sleep_int
 
 	test_spawn_filter
@@ -3140,6 +3380,11 @@ do_without_svscan()
 	srs_setup 1
 	test_srs
 	srs_setup 0
+
+	virtual_setup 1
+	test_maildirserial
+	terminate_smtp_qmtp $qmtp_pid
+	virtual_setup 0
 
 	create_authsmtp
 	test_qmail_remote_auth "PLAIN"
@@ -3157,7 +3402,7 @@ do_without_svscan()
 	test_smtp_auth_plain
 	test_smtp_auth_cram_md5
 	test_tcpclient_script 1 # test smtp using tcpclient
-	terminate_smtp $smtp_pid
+	terminate_smtp_qmtp $smtp_pid
 
 	# start smtps using tcpserver
 	for i in TLSv1_2 TLSv1_3
@@ -3174,18 +3419,18 @@ do_without_svscan()
 		do
 			test_tcpclient_script 2 $j # test smtps using tcpclient
 		done
-		terminate_smtp $smtp_pid
+		terminate_smtp_qmtp $smtp_pid
 	done
 
 	start_tcpserver_smtp_unix
 	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
 	test_tcpclient_script 3 # test smtp using tcpclient
-	terminate_smtp $smtp_pid
+	terminate_smtp_qmtp $smtp_pid
 
 	start_tcpserver_smtps_unix
 	smtp_pid=$(/bin/ps -ef|grep $smtp_socket|grep qmail-smtpd|awk '{print $2}')
 	test_tcpclient_script 4 # test smtps using tcpclient
-	terminate_smtp $smtp_pid
+	terminate_smtp_qmtp $smtp_pid
 
 	# terminate qmail-send
 	terminate_send $send_pid
@@ -5131,6 +5376,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.26  2023-10-05 23:38:27+05:30  Cprogrammer
+# added tests for maildirserial, serialsmtp, serialqmtp
+#
 # Revision 1.25  2023-10-04 21:01:42+05:30  Cprogrammer
 # added test for invalid auth type
 #
