added test for for qmta-send

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.56 2023-12-15 23:06:18+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.57 2023-12-16 12:31:15+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -32,6 +32,7 @@ tmpdir=$testdir/tmp
 qmail_newu=$sbindir/qmail-newu
 qmail_start=$sbindir/qmail-start
 slowq_start=$sbindir/slowq-start
+qmta_send=$sbindir/qmta-send
 qmail_inject=$bindir/qmail-inject
 qmail_smtpd=$sbindir/qmail-smtpd
 qmail_qmqpd=$sbindir/qmail-qmqpd
@@ -99,13 +100,16 @@ do_cleanup_failed()
 			terminate_smtp_qmtp $smtp_pid
 		fi
 		[ -z "$send_pid" ] && send_pid=$(get_send_pid qmail-send $testdir/queue)
-		terminate_send "$send_pid"
+		terminate_send qmail-send "$send_pid"
 
 		[ -z "$slowq_pid1" ] && slowq_pid1=$(get_send_pid slowq-send $testdir/slowq1)
-		terminate_send "$slowq_pid1"
+		terminate_send slowq-send-1 "$slowq_pid1"
 
 		[ -z "$slowq_pid2" ] && slowq_pid2=$(get_send_pid slowq-send $testdir/slowq2)
-		terminate_send "$slowq_pid2"
+		terminate_send slowq-send-2 "$slowq_pid2"
+
+		[ -z "$qmta_pid" ] && qmta_pid=$(get_send_pid qmta-send $testdir/qmta)
+		terminate_send qmta-send "$qmta_pid"
 	fi
 	sudo /bin/rm -rf $servicedir $logdir $testdir/queue $testdir/slowq1 $testdir/slowq2 $testdir/qmta $testdir/domainqueue \
 		$testdir/bin $tmpdir $testdir/run $testdir/sleep.out $testdir/svscan.out $testdir/tcpclient.smtp \
@@ -353,19 +357,28 @@ setup_queue()
 		failed=1
 		exit 1
 	fi
-	sudo queue-fix -r -s 23 -b 0 $testdir/slowq1 && sudo queue-fix -r -s 23 -b 0 $testdir/slowq2
+	sudo queue-fix -m -s 23 -b 0 $testdir/qmta
 	ret2=$?
-	if [ $ret2 -eq 0 ] ; then
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
-		tcount=$(expr $tcount + 1)
-		printf "\r  testing create qmail queue succeeded for qmail-send, slowq-send %38s [%.4f sec]\n" " " $secs
-		print_pct
-	else
-		echo "testing create qmail queue failed for $testdir/slowq1|$testdir/slowq2"
+	if [ $ret2 -ne 0 ] ; then
+		echo "testing create qmail queue failed for $testdir/qmta"
 		failed=1
 		exit 1
 	fi
+
+	for i in 1 2
+	do
+		sudo queue-fix -r -s 23 -b 0 $testdir/slowq1 && sudo queue-fix -r -s 23 -b 0 $testdir/slowq$i
+		if [ $? -ne 0 ] ; then
+			echo "testing create qmail queue failed for $testdir/slowq1|$testdir/slowq"$i""
+			failed=1
+			exit 1
+		fi
+	done
+	t2=$(date +"%s.%4N")
+	secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+	tcount=$(expr $tcount + 1)
+	printf "\r  testing create qmail queue succeeded for qmail-send, slowq-send %38s [%.4f sec]\n" " " $secs
+	print_pct
 }
 
 setup_config()
@@ -637,7 +650,6 @@ run_qmail_send()
 {
 	create_qmail_getpw
 	if [ $# -eq 0 -o $# -gt 2 ] ; then
-		echo here1
 		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2 [silent]" 1>&2
 		return 1
 	fi
@@ -651,6 +663,7 @@ run_qmail_send()
 		todo_proc=0 # not used by qmail-send
 		opt="-s"
 		pcount=6
+		send_pid=""
 	elif [ "$1" = "slowq-send-1" ] ; then
 		start_pg=$slowq_start
 		pg1=slowq-send
@@ -660,6 +673,7 @@ run_qmail_send()
 		todo_proc=1
 		opt=""
 		pcount=5
+		slowq1_pid=""
 	elif [ "$1" = "slowq-send-2" ] ; then
 		start_pg=$slowq_start
 		pg1=slowq-send
@@ -669,9 +683,19 @@ run_qmail_send()
 		todo_proc=0
 		opt=""
 		pcount=4
+		slowq2_pid=""
+	elif [ "$1" = "qmta-send" ] ; then
+		start_pg=$qmta_send
+		pg1=qmta-send
+		pg2=qmail-send
+		logfn=qmta-send.log
+		queuedir=$testdir/qmta
+		todo_proc=0
+		opt="-d"
+		pcount=3
+		qmta_pid=""
 	else
-		echo here2 [$1]
-		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2 [silent]" 1>&2
+		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2|qmta-send [silent]" 1>&2
 		return 1
 	fi
 	t1=$(date +"%s.%4N")
@@ -706,10 +730,19 @@ run_qmail_send()
 		slowq_pid1=$pid
 	elif [ "$1" = "slowq-send-2" ] ; then
 		slowq_pid2=$pid
+	elif [ "$1" = "qmta-send" ] ; then
+		qmta_pid=$pid
 	fi
-	count=$(ps -ef | grep -E -v $pg2 | grep -E "$pg1|todo-proc|slowq-todo|qmail-lspawn|qmail-rspawn|qmail-clean" | grep $queuedir | wc -l)
+	if [ "$1" = "qmta-send" ] ; then
+		count=$(sudo pstree -ac $qmta_pid | wc -l)
+	else
+		count=$(ps -ef | grep -E -v $pg2 | grep -E "$pg1|todo-proc|slowq-todo|qmail-lspawn|qmail-rspawn|qmail-clean" | grep $queuedir | wc -l)
+	fi
 	tx2=$(date +"%s.%4N")
 	sleep_secs=$(echo $tx1 $tx2 | awk '{printf("%0.4f\n", $2-$1)}')
+	if [ -z "$pid" ] ; then
+		pid=0
+	fi
 	if [ -n "$pid" -a $pid -gt 0 -a -n "$count" -a $count -eq $pcount ] ; then
 		[ $silent -eq 1 ] && return 0
 		t2=$(date +"%s.%4N")
@@ -725,9 +758,12 @@ run_qmail_send()
 			"slowq-send-2")
 			printf "\r  testing %-10s startup without todo-processor  succeeded %41s [%.4f sec]\n" $pg1 " " $secs
 			;;
+			"qmta-send")
+			printf "\r  testing %-10s startup with int lrc daemons    succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			;;
 		esac
 	else
-		echo "testing $pg1 option ($1) startup failed "$pg1"_pid=$pid, count=$count"
+		echo "testing $pg1 option ($1) startup failed "$pg1"_pid=$pid, count=$count, pcount=$pcount"
 		echo "$pg1 log"
 		cat $logdir/$pg1/$logfn
 		failed=1
@@ -739,7 +775,7 @@ get_send_pid()
 {
 	count=0
 	if [ $# -ne 2 ] ; then
-		echo "get_send_pid qmail-send|slowq-send queuedir" 1>&2
+		echo "get_send_pid qmail-send|slowq-send|qmta-send queuedir" 1>&2
 		return
 	fi
 	pg=$1
@@ -749,6 +785,10 @@ get_send_pid()
 		logfn="slowq1-send.log"
 	elif [ "$1" = "slowq-send-2" ] ; then
 		logfn="slowq2-send.log"
+	elif [ "$1" = "qmta-send" ] ; then
+		logfn="qmta-send.log"
+		sudo fuser $2/lock/trigger 2>/dev/null|sed 's{ {{g'
+		return $?
 	fi
 	sleep_secs=0
 	while true
@@ -3008,10 +3048,25 @@ terminate_smtp_qmtp()
 
 terminate_send()
 {
-	if [ -n "$1" ] ; then
+	if [ -n "$2" ] ; then
+		shift
 		sudo kill $*
 		sleep $sleep_int
 	fi
+#	case $1 in
+#		"qmail-send")
+#		unset send_pid
+#		;;
+#		"slowq-send-1")
+#		unset slowq1_pid
+#		;;
+#		"slowq-send"-2)
+#		unset slowq2_pid
+#		;;
+#		"qmta-send")
+#		unset qmta_pid
+#		;;
+#	esac
 }
 
 start_tcpserver_smtps()
@@ -5324,9 +5379,11 @@ do_without_svscan()
 	run_qmail_send qmail-send
 	run_qmail_send slowq-send-1
 	run_qmail_send slowq-send-2
+	run_qmail_send qmta-send
 	test_qmail_inject $user $user $testdir/queue
 	test_qmail_inject $user $user $testdir/slowq1
 	test_qmail_inject $user $user $testdir/slowq2
+	test_qmail_inject $user $user $testdir/qmta
 	setup_assign # restore users/assign
 	test_alias
 
@@ -5432,9 +5489,10 @@ do_without_svscan()
 	terminate_smtp_qmtp $smtp_pid
 
 	# terminate qmail-send, slowq-send
-	terminate_send "$send_pid"
-	terminate_send "$slowq_pid1"
-	terminate_send "$slowq_pid2"
+	terminate_send qmail-send "$send_pid"
+	terminate_send slowq-send-1 "$slowq_pid1"
+	terminate_send slowq-send-2 "$slowq_pid2"
+	terminate_send qmta-send "$qmta_pid"
 }
 
 do_without_svscan2()
@@ -5445,9 +5503,11 @@ do_without_svscan2()
 	run_qmail_send qmail-send
 	run_qmail_send slowq-send-1
 	run_qmail_send slowq-send-2
+	run_qmail_send qmta-send
 	test_qmail_inject $user $user $testdir/queue
 	test_qmail_inject $user $user $testdir/slowq1
 	test_qmail_inject $user $user $testdir/slowq2
+	test_qmail_inject $user $user $testdir/qmta
 	echo
 	failed=1
 	exit 1
@@ -7803,7 +7863,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=280
+	total_tests=283
 fi
 failed=0
 do_setup
@@ -7865,6 +7925,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.57  2023-12-16 12:31:15+05:30  Cprogrammer
+# added test for qmta-send
+#
 # Revision 1.56  2023-12-15 23:06:18+05:30  Cprogrammer
 # added tests for slowq-send
 #
