added test for autoresponder

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,9 +1,10 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.6 2023-09-08 00:54:00+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.7 2023-09-08 15:42:28+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
+tuser=tuser
 myuid=$(id -u)
 mygid=$(id -g)
 real_domain=argos.indimail.org
@@ -52,20 +53,26 @@ do_cleanup_failed()
 	sudo /bin/rm -rf $testdir/sleep.out
 	sudo /bin/rm -rf $testdir/svscan.out
 	sudo /bin/rm -rf $testdir/tcpclient.smtp
+	sudo /bin/rm -rf $testdir/.vacation.dir/*
 	sudo /bin/rm -rf $sysconfdir/users
 }
 
 check_mail()
 {
+	if [ $# -eq 1 ] ; then
+		dir=$1
+	else
+		dir=$maildir
+	fi
 	count=0
 	ret=1
 	(
 	while true
 	do
-		mcount=$(ls $maildir/new | wc -l)
+		mcount=$(ls $dir/new | wc -l)
 		if [ $mcount -gt 0 ] ; then
-			mail_file=$(ls -lt $maildir/new|head -2|tail -1|awk '{print $9}')
-			/bin/rm -f $maildir/new/$mail_file
+			mail_file=$(ls -lt $dir/new|head -2|tail -1|awk '{print $9}')
+			/bin/rm -f $dir/new/$mail_file
 			return 0
 		fi
 		sleep 1
@@ -130,12 +137,16 @@ setup_maildir()
 	if [ -d $maildir/new ] ; then
 		find $maildir/new -type f -exec /bin/rm -f {} \;
 	fi
+	if [ -d $testdir/tuser/Maildir/new ] ; then
+		find $testdir/tuser/Maildir/new -type f -exec /bin/rm -f {} \;
+	fi
 	mkdir -p $cntrldir
 	mkdir -p $sysconfdir/users
 	echo "Creating $maildir" 1>&2
 	for i in cur new tmp
 	do
 		mkdir -p $maildir/$i
+		mkdir -p $testdir/tuser/Maildir/$i
 	done
 }
 
@@ -145,6 +156,8 @@ setup_assign()
 	(
 	echo "=$user:$user:$myuid:$mygid:$testdir/$user:::"
 	echo "+$user-:$user:$myuid:$mygid:$testdir/$user:-::"
+	echo "=tuser:tuser:$myuid:$mygid:$testdir/tuser:::"
+	echo "+tuser-:tuser:$myuid:$mygid:$testdir/tuser:-::"
 	echo "."
 	) > $sysconfdir/users/assign
 	echo "Creating $sysconfdir/users/cdb" 1>&2
@@ -339,20 +352,19 @@ test_qmail_inject()
 {
 	echo "Starting qmail-inject"
 	(
-	echo "From: $user"
-	echo "To: $user"
+	echo "From: $2"
+	echo "To: $3"
 	echo "Subject: Test"
 	echo "Date: $(date -R)"
 	echo
 	echo "Test message"
-	) | sudo $setuidgid -g qcerts $user env - \
+	) | sudo $setuidgid -g qcerts $1 env - \
 		QUEUEDIR=$testdir/queue \
 		QMAILQUEUE=$qmail_queue \
 		CONTROLDIR=$cntrldir \
 		BIGTODO=0 \
 		CONFSPLIT=23 \
-		$qmail_inject $user
-
+		$qmail_inject $3
 	check_mail
 	if [ $? -eq 0 ] ; then
 		tcount=$(expr $tcount + 1)
@@ -361,7 +373,7 @@ test_qmail_inject()
 		sudo kill $send_pid
 		(
 		echo "  testing qmail-inject, qmail send+receive failed"
-		$logdir/qmail-send/qmail-send.log
+		cat $logdir/qmail-send/qmail-send.log
 		) | less
 		exit 1
 	fi
@@ -1756,7 +1768,7 @@ do_without_svscan()
 	# use qmail-start to start qmail-send
 	run_qmail_send
 	send_pid=$(get_send_pid)
-	test_qmail_inject
+	test_qmail_inject $user $user $user
 
 	# start smtp using tcpserver
 	start_tcpserver_smtp
@@ -1819,6 +1831,8 @@ do_svscan_without_svscanlog()
 	svpid=$(sed -n '$p' $servicedir/.svscan.pid)
 	test_smtps "testing mail using SMTPS by qmail-smtpd"
 	test_recipients
+	do_autoresponder
+	do_qmail_qfilter
 	test_stop_smtps
 	test_stop_supervise
 	test_restart_service_using_hup
@@ -1914,6 +1928,68 @@ do_qmail_qfilter()
 	return 1
 }
 
+do_autoresponder()
+{
+	if [ -d $testdir/.vacation.dir ] ; then
+		/bin/rm -f $testdir/.vacation.dir/*
+	else
+		mkdir -p $testdir/.vacation.dir
+	fi
+	echo "I'm on leave" > $testdir/.vacation.msg
+	(
+	echo "|/usr/bin/autoresponder -q $testdir/.vacation.msg $testdir/.vacation.dir" 
+	echo "$testdir/tuser/Maildir/"
+	) > $testdir/tuser/.qmail
+	subject="Testing Autoresponder"
+	(
+	echo "From: $user@$real_domain"
+	echo "To: tuser@$real_domain"
+	echo "Subject: $subject"
+	echo "Date: $(date -R)"
+	echo
+	echo "Test message"
+	) | sudo $setuidgid -g qcerts $user env - \
+		QUEUEDIR=$testdir/queue \
+		QMAILQUEUE=$qmail_queue \
+		CONTROLDIR=$cntrldir \
+		BIGTODO=0 \
+		CONFSPLIT=23 \
+	$qmail_inject -f$user@$real_domain tuser
+	reply_subject="Subject: Autoreply: Re: $subject"
+	count=0
+	ret=1
+	subject=""
+	while true
+	do
+		mcount=$(ls $maildir/new | wc -l)
+		if [ $mcount -gt 0 ] ; then
+			mail_file=$(ls -lt $maildir/new|head -2|tail -1|awk '{print $9}')
+			subject=$(grep ^Subject: $maildir/new/$mail_file)
+			/bin/rm -f $maildir/new/$mail_file
+			break
+		fi
+		sleep 1
+		count=$(expr "$count" + 1)
+		if [ $count -gt 5 ] ; then
+			echo "Failed to receive Mail" 1>&2
+			break
+		fi
+	done
+	if [ "$reply_subject" = "$subject" ] ; then
+		tcount=$(expr $tcount + 1)
+		echo "  testing autoresponder succeeded"
+	else
+		sudo kill $send_pid $smtp_pid
+		(
+		echo "  testing autoresponder failed"
+		echo "Expected subject as $reply_subject but got $subject"
+		echo "qmail-send.log"
+		cat $logdir/qmail-send/qmail-send.log
+		) |less
+		exit 1
+	fi
+}
+
 sudo ls /tmp > /dev/null 2>&1
 if [ $? -ne 0 ] ; then
 	echo "This script requires sudo privileges" 1>&2
@@ -1927,7 +2003,6 @@ log_type=2
 do_svscan_without_svscanlog
 shutdown_svscan $svpid
 do_svscan_with_svscanlog
-do_qmail_qfilter
 shutdown_svscan $svpid
 
 wait
@@ -1950,6 +2025,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.7  2023-09-08 15:42:28+05:30  Cprogrammer
+# added test for autoresponder
+#
 # Revision 1.6  2023-09-08 00:54:00+05:30  Cprogrammer
 # added test for qmail-qfilter
 #
