fix badhelo check
1. qregex.c: fix wildmat when pattern file is missing
2. smtpd.c: fix nodnscheck for helo/ehlo
3. test-indimail-mta: added badhelo test

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.45 2023-11-01 21:59:39+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.47 2023-11-03 05:25:26+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -445,6 +445,10 @@ setup_config()
 	echo @$HOSTNAME
 	echo @$srs_domain
 	echo @$vdomain
+	echo israel
+	echo palestine
+	echo argos.indimail.org
+	echo serialsmtp
 	)                                         > $cntrldir/nodnscheck
 }
 
@@ -853,6 +857,7 @@ start_tcpserver_smtp()
 		REJECTSPAM=0 \
 		MAKE_SEEKABLE=1 \
 		DKIMVERIFY="" \
+		BADHELOCHECK=1 \
 		$tcpserver -u qmaild -g qmail -HR 0 $smtp_port $qmail_smtpd $HOSTNAME \
 			$testdir/bin/authsmtp /sbin/sys-checkpwd /bin/false
 	) > $logdir/smtpd/smtpd.log 2>&1 &
@@ -1991,7 +1996,7 @@ test_smtp_chk_sender()
 
 	# First: This should work
 	# because remote mail will be redirected
-	# to $HOSTNAME using $testdir/bin/qmail-remote 
+	# to $HOSTNAME using $testdir/bin/qmail-remote
 	# Also, $testdir/bin/qmail-remote changes the recipient
 	# to $testuser@$HOSTNAME
 	#create_qmail_remote $testuser@$HOSTNAME
@@ -4531,6 +4536,44 @@ test_qmail_multi()
 	/bin/rm -rf $testdir/variables
 }
 
+test_badhelo()
+{
+	t1=$(date +"%s.%4N")
+	echo "*israel*" > $cntrldir/badhelo
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server 127.0.0.1 --port $smtp_port \
+		-h israel >$tmpdir/swaks.$$
+	ret1=$?
+	l1=$(sed -n 1p < $tmpdir/swaks.$$)
+	echo $l1 | grep ".*553 sorry, your HELO/EHLO greeting is in my badhelo list (#5.7.1)">/dev/null
+	ret2=$?
+	check_mail 2>/dev/null
+	ret3=$?
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server 127.0.0.1 --port $smtp_port \
+		-h palestine >$tmpdir/swaks.$$
+	ret4=$?
+	check_mail 2>/dev/null
+	ret5=$?
+	/bin/rm -f $tmpdir/swaks.$$
+
+	if [ $ret1 -ne 0 -a $ret2 -eq 0 -a $ret3 -ne 0 -a $ret4 -eq 0 -a $ret5 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing SMTP badhelo check succeeded %65s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		echo "ret1=$ret1, ret2=$ret2, ret3=$ret3, ret4=$ret4, ret5=$ret5, l1=[$l1]"
+		echo "  testing SMTP badhelo check failed [#secs sec]"
+		(
+		echo "$logdir/smtpd/smtpd.log"
+		cat $logdir/smtpd/smtpd.log
+		)|less
+		failed=1
+		exit 1
+	fi
+	/bin/rm -f $cntrldir/badhelo
+}
+
 do_without_svscan()
 {
 	printf "\r%118s\n" " "
@@ -4574,11 +4617,11 @@ do_without_svscan()
 	# start qmtp using tcpserver
 	start_tcpserver_qmtp
 	sleep $sleep_int
-
-	test_spawn_filter
-
-	create_authsmtp
 	create_qmail_remote $testuser@$HOSTNAME
+
+	test_badhelo
+	test_spawn_filter
+	create_authsmtp
 	test_domainqueue
 	test_spamfilter
 	test_qhpsi
@@ -6978,7 +7021,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=258
+	total_tests=260
 fi
 failed=0
 do_setup
@@ -7039,6 +7082,12 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.47  2023-11-03 05:25:26+05:30  Cprogrammer
+# added badhelo test
+#
+# Revision 1.46  2023-11-02 06:31:01+05:30  Cprogrammer
+# fixed QMAILREMOTE
+#
 # Revision 1.45  2023-11-01 21:59:39+05:30  Cprogrammer
 # added test for domainqueue
 #
