added tests for qmta-send

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.58 2023-12-16 22:21:07+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.59 2023-12-17 21:06:27+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -82,6 +82,35 @@ print_pct()
 	printf "%90s Test No %5d [%6.2f   %%]" " " $tcount $pct
 }
 
+terminate_send()
+{
+	if [ -n "$2" ] ; then
+		shift
+		sudo kill $*
+		sleep $sleep_int
+	fi
+	case $1 in
+		"qmail-send")
+		unset send_pid
+		;;
+		"qmail-send-2")
+		unset send_pid2
+		;;
+		"slowq-send-1")
+		unset slowq_pid1
+		;;
+		"slowq-send"-2)
+		unset slowq_pid2
+		;;
+		"qmta-send-1")
+		unset qmta_pid1
+		;;
+		"qmta-send-2")
+		unset qmta_pid2
+		;;
+	esac
+}
+
 do_cleanup_failed()
 {
 	if [ $failed -eq 0 ] ; then
@@ -108,8 +137,11 @@ do_cleanup_failed()
 		[ -z "$slowq_pid2" ] && slowq_pid2=$(get_send_pid slowq-send $testdir/slowq2)
 		terminate_send slowq-send-2 "$slowq_pid2"
 
-		[ -z "$qmta_pid" ] && qmta_pid=$(get_send_pid qmta-send $testdir/qmta)
-		terminate_send qmta-send "$qmta_pid"
+		[ -z "$qmta_pid1" ] && qmta_pid1=$(get_send_pid qmta-send $testdir/qmta1)
+		terminate_send qmta-send "$qmta_pid1"
+
+		[ -z "$qmta_pid2" ] && qmta_pid2=$(get_send_pid qmta-send $testdir/qmta2)
+		terminate_send qmta-send "$qmta_pid2"
 	fi
 	sudo /bin/rm -rf $servicedir $logdir $testdir/queue $testdir/slowq1 $testdir/slowq2 $testdir/qmta $testdir/domainqueue \
 		$testdir/bin $tmpdir $testdir/run $testdir/sleep.out $testdir/svscan.out $testdir/tcpclient.smtp \
@@ -351,16 +383,20 @@ setup_queue()
 {
 	t1=$(date +"%s.%4N")
 	sudo queue-fix -s 23 -b 0 $testdir/queue
-	ret1=$?
-	if [ $ret1 -ne 0 ] ; then
+	if [ $? -ne 0 ] ; then
 		echo "testing create qmail queue failed for $testdir/queue"
 		failed=1
 		exit 1
 	fi
-	sudo queue-fix -m -s 23 -b 0 $testdir/qmta
-	ret2=$?
-	if [ $ret2 -ne 0 ] ; then
-		echo "testing create qmail queue failed for $testdir/qmta"
+	sudo queue-fix -m -s 23 -b 0 $testdir/qmta1
+	if [ $? -ne 0 ] ; then
+		echo "testing create qmail queue failed for $testdir/qmta1"
+		failed=1
+		exit 1
+	fi
+	sudo queue-fix -s 23 -b 0 $testdir/qmta2
+	if [ $? -ne 0 ] ; then
+		echo "testing create qmail queue failed for $testdir/qmta2"
 		failed=1
 		exit 1
 	fi
@@ -377,7 +413,7 @@ setup_queue()
 	t2=$(date +"%s.%4N")
 	secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 	tcount=$(expr $tcount + 1)
-	printf "\r  testing create qmail queue succeeded for qmail-send, slowq-send %38s [%.4f sec]\n" " " $secs
+	printf "\r  testing create qmail queue succeeded for qmail-send, slowq-send, qmta-send %27s [%.4f sec]\n" " " $secs
 	print_pct
 }
 
@@ -650,7 +686,7 @@ run_qmail_send()
 {
 	create_qmail_getpw
 	if [ $# -eq 0 -o $# -gt 2 ] ; then
-		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2 [silent]" 1>&2
+		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2|qmta-send-1|qmta-send-2 [silent]" 1>&2
 		return 1
 	fi
 	[ $# -eq 2 ] && silent=1 || silent=0
@@ -673,7 +709,7 @@ run_qmail_send()
 		todo_proc=1
 		opt=""
 		pcount=5
-		slowq1_pid=""
+		slowq_pid1=""
 	elif [ "$1" = "slowq-send-2" ] ; then
 		start_pg=$slowq_start
 		pg1=slowq-send
@@ -683,19 +719,29 @@ run_qmail_send()
 		todo_proc=0
 		opt=""
 		pcount=4
-		slowq2_pid=""
-	elif [ "$1" = "qmta-send" ] ; then
+		slowq_pid2=""
+	elif [ "$1" = "qmta-send-1" ] ; then
 		start_pg=$qmta_send
 		pg1=qmta-send
 		pg2=qmail-send
 		logfn=qmta-send.log
-		queuedir=$testdir/qmta
+		queuedir=$testdir/qmta1
 		todo_proc=0
 		opt="-d"
 		pcount=3
-		qmta_pid=""
+		qmta_pid1=""
+	elif [ "$1" = "qmta-send-2" ] ; then
+		start_pg=$qmta_send
+		pg1=qmta-send
+		pg2=qmail-send
+		logfn=qmta-send.log
+		queuedir=$testdir/qmta2
+		todo_proc=0
+		opt="-dlrc"
+		pcount=4
+		qmta_pid2=""
 	else
-		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2|qmta-send [silent]" 1>&2
+		echo "run_qmail_send qmail-send|slowq-send-1|slowq-send-2|qmta-send-1|qmta-send-2 [silent]" 1>&2
 		return 1
 	fi
 	t1=$(date +"%s.%4N")
@@ -704,7 +750,7 @@ run_qmail_send()
 	exec 1>$logdir/$pg1/$logfn
 	exec 2>$logdir/$pg1/$logfn
 	exec 0<&2
-	sudo env - \
+	exec sudo env - \
 		PATH=/bin:/usr/sbin \
 		BIGTODO=0 \
 		USE_QPWGR=1 \
@@ -730,11 +776,15 @@ run_qmail_send()
 		slowq_pid1=$pid
 	elif [ "$1" = "slowq-send-2" ] ; then
 		slowq_pid2=$pid
-	elif [ "$1" = "qmta-send" ] ; then
-		qmta_pid=$pid
+	elif [ "$1" = "qmta-send-1" ] ; then
+		qmta_pid1=$pid
+	elif [ "$1" = "qmta-send-2" ] ; then
+		qmta_pid2=$pid
 	fi
-	if [ "$1" = "qmta-send" ] ; then
-		count=$(sudo pstree -ac $qmta_pid | wc -l)
+	if [ "$1" = "qmta-send-1" ] ; then
+		count=$(sudo pstree -ac $qmta_pid1 | wc -l)
+	elif [ "$1" = "qmta-send-2" ] ; then
+		count=$(sudo pstree -ac $qmta_pid2 | wc -l)
 	else
 		count=$(ps -ef | grep -E -v $pg2 | grep -E "$pg1|todo-proc|slowq-todo|qmail-lspawn|qmail-rspawn|qmail-clean" | grep $queuedir | wc -l)
 	fi
@@ -750,16 +800,19 @@ run_qmail_send()
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		case "$1" in
 			"qmail-send")
-			printf "\r  testing %-10s startup with external todo-proc succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			printf "\r  testing %-10s startup with external todo-processor succeeded %36s [%.4f sec]\n" $pg1 " " $secs
 			;;
 			"slowq-send-1")
-			printf "\r  testing %-10s startup with    todo-processor  succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			printf "\r  testing %-10s startup with internal todo-processor succeeded %36s [%.4f sec]\n" $pg1 " " $secs
 			;;
 			"slowq-send-2")
-			printf "\r  testing %-10s startup without todo-processor  succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			printf "\r  testing %-10s startup without       todo-processor succeeded %36s [%.4f sec]\n" $pg1 " " $secs
 			;;
-			"qmta-send")
-			printf "\r  testing %-10s startup with int lrc daemons    succeeded %41s [%.4f sec]\n" $pg1 " " $secs
+			"qmta-send-1")
+			printf "\r  testing %-10s startup with internal lrc daemons    succeeded %36s [%.4f sec]\n" $pg1 " " $secs
+			;;
+			"qmta-send-2")
+			printf "\r  testing %-10s startup with external lrc daemons    succeeded %36s [%.4f sec]\n" $pg1 " " $secs
 			;;
 		esac
 	else
@@ -883,7 +936,7 @@ test_domainqueue()
 	exec 1>$logdir/qmail-send/qmail-send2.log
 	exec 2>&1
 	exec 0<&2
-	sudo env - PATH=/bin:/usr/sbin \
+	exec sudo env - PATH=/bin:/usr/sbin \
 			USE_QPWGR=1 \
 			BIGTODO=0 \
 			CONFSPLIT=23 \
@@ -896,7 +949,8 @@ test_domainqueue()
 			PASSWD_FILE=$testdir/etc/passwd \
 		$qmail_start -s ./Maildir/
 	) &
-	send_pid2=$(jobs -r -p | tail -1)
+	job_pid=$(jobs -r -p | tail -1)
+	send_pid2=$(get_send_pid qmail-send $testdir/domainqueue)
 
 	(
 	echo
@@ -941,7 +995,8 @@ test_domainqueue()
 		echo $logdir/qmail-send/qmail-send.log
 		) |less
 		/bin/rm -f $cntrldir/domainqueue $cntrldir/smtproutes
-		sudo kill $send_pid2
+		terminate_send qmail-send-2 $send_pid2
+		sudo kill $job_pid 2>/dev/null
 		failed=1
 		exit 1
 	fi
@@ -964,7 +1019,8 @@ test_domainqueue()
 	else
 		body=""
 	fi
-	sudo kill $send_pid2
+	terminate_send qmail-send-2 $send_pid2
+	sudo kill $job_pid 2>/dev/null
 	if [ "$body" = "$$: Testing qmail-inject domainqueue" -a $ret -eq 0 ] ; then
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
@@ -3044,29 +3100,6 @@ terminate_smtp_qmtp()
 	else
 		sleep_secs=0
 	fi
-}
-
-terminate_send()
-{
-	if [ -n "$2" ] ; then
-		shift
-		sudo kill $*
-		sleep $sleep_int
-	fi
-#	case $1 in
-#		"qmail-send")
-#		unset send_pid
-#		;;
-#		"slowq-send-1")
-#		unset slowq1_pid
-#		;;
-#		"slowq-send"-2)
-#		unset slowq2_pid
-#		;;
-#		"qmta-send")
-#		unset qmta_pid
-#		;;
-#	esac
 }
 
 start_tcpserver_smtps()
@@ -5379,11 +5412,13 @@ do_without_svscan()
 	run_qmail_send qmail-send
 	run_qmail_send slowq-send-1
 	run_qmail_send slowq-send-2
-	run_qmail_send qmta-send
+	run_qmail_send qmta-send-1
+	run_qmail_send qmta-send-2
 	test_qmail_inject $user $user $testdir/queue
 	test_qmail_inject $user $user $testdir/slowq1
 	test_qmail_inject $user $user $testdir/slowq2
-	test_qmail_inject $user $user $testdir/qmta
+	test_qmail_inject $user $user $testdir/qmta1
+	test_qmail_inject $user $user $testdir/qmta2
 	setup_assign # restore users/assign
 	test_alias
 
@@ -5492,7 +5527,8 @@ do_without_svscan()
 	terminate_send qmail-send "$send_pid"
 	terminate_send slowq-send-1 "$slowq_pid1"
 	terminate_send slowq-send-2 "$slowq_pid2"
-	terminate_send qmta-send "$qmta_pid"
+	terminate_send qmta-send "$qmta_pid1"
+	terminate_send qmta-send "$qmta_pid2"
 }
 
 do_without_svscan2()
@@ -7863,7 +7899,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=282
+	total_tests=284
 fi
 failed=0
 do_setup
@@ -7925,6 +7961,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.59  2023-12-17 21:06:27+05:30  Cprogrammer
+# added tests for qmta-send
+#
 # Revision 1.58  2023-12-16 22:21:07+05:30  Cprogrammer
 # updated test script
 #
