added tests for envheader, filterargs without local/remote directive

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.64 2024-02-07 22:55:53+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.65 2024-02-09 15:53:31+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -823,6 +823,7 @@ run_qmail_send()
 	elif [ "$1" = "qmta-send-2" ] ; then
 		qmta_pid2=$pid
 	fi
+	sleep $sleep_int
 	if [ "$1" = "qmta-send-1" ] ; then
 		count=$(sudo pstree -ac $qmta_pid1 | wc -l)
 	elif [ "$1" = "qmta-send-2" ] ; then
@@ -1105,6 +1106,8 @@ do_qmail_inject()
 	echo "Date: $(date -R)"
 	echo "X-Remove-Header1: This header will be removed"
 	echo "X-Remove-Header2: This header will also be removed"
+	echo "X-Env-Header1: This is env-header1"
+	echo "X-Env-Header2: This is env-header2"
 	echo "X-Log-Test: Test Header"
 	echo
 	echo "$4"
@@ -5058,7 +5061,6 @@ test_direct_spawn_filter()
 			echo 1 > $testdir/variables/MATCH_SENDER_DOMAIN
 		fi
 
-		t1=$(date +"%s.%4N")
 		(
 			echo "From: $user@$local_domain1"
 			echo "To: $user@$local_domain2"
@@ -5068,6 +5070,7 @@ test_direct_spawn_filter()
 			echo "Test message from abcd"
 		) > $tmpdir/mail.txt
 		# qmail-local [ -nN ] user homedir local dash ext domain sender defaultdelivery qqeh
+		t1=$(date +"%s.%4N")
 		envdir -c $testdir/variables sh -c \
 			"exec -a qmail-local $sbindir/spawn-filter -- $user $testdir/$user $user \"\" \"\" $local_domain2 $user@$local_domain1 ./Maildir/ \"\"" < $tmpdir/mail.txt > $tmpdir/mail.out
 		body=$($e822body < $tmpdir/mail.out)
@@ -5100,6 +5103,7 @@ test_direct_spawn_filter()
 			echo body=$body, subject=$subject
 			/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt $cntrldir/filterargs \
 				$testdir/bin/filter1 $testdir/bin/filter2 $testdir/bin/spawn-cat
+			exit 1
 		fi
 		/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt
 	done
@@ -5128,7 +5132,6 @@ test_direct_spawn_filter()
 			echo 1 > $testdir/variables/MATCH_RECIPIENT_DOMAIN
 		fi
 
-		t1=$(date +"%s.%4N")
 		(
 			echo "From: $user@$remote_domain1"
 			echo "To: $user@$remote_domain2"
@@ -5140,6 +5143,7 @@ test_direct_spawn_filter()
 		# qmail-remote host sender qqeh size recip
 		#exec -a qmail-remote $sbindir/spawn-filter $1  postmaster@$1 postmaster@$1
 		size=$(ls -l $tmpdir/mail.txt|awk '{print $5}')
+		t1=$(date +"%s.%4N")
 		envdir -c $testdir/variables sh -c \
 			"exec -a qmail-remote $sbindir/spawn-filter $remote_domain2 $user@$remote_domain1 \"\" $size $user@$remote_domain2" < $tmpdir/mail.txt > $tmpdir/mail.out
 		body=$($e822body < $tmpdir/mail.out)
@@ -5149,25 +5153,25 @@ test_direct_spawn_filter()
 			secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1)}')
 			tcount=$(expr $tcount + 1)
 			if [ $i -eq 1 ] ; then
-				printf "\r  testing spawn-filter REGEXP  qmail-remote (recipient-match) succeeded %32s [%.4f sec]\n" " " $secs
-			elif [ $i -eq 2 ] ; then
-				printf "\r  testing spawn-filter wildmat qmail-remote (recipient-match) succeeded %32s [%.4f sec]\n" " " $secs
-			elif [ $i -eq 3 ] ; then
 				printf "\r  testing spawn-filter REGEXP  qmail-remote (sender-match)    succeeded %32s [%.4f sec]\n" " " $secs
-			elif [ $i -eq 4 ] ; then
+			elif [ $i -eq 2 ] ; then
 				printf "\r  testing spawn-filter wildmat qmail-remote (sender-match)    succeeded %32s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 3 ] ; then
+				printf "\r  testing spawn-filter REGEXP  qmail-remote (recipient-match) succeeded %32s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 4 ] ; then
+				printf "\r  testing spawn-filter wildmat qmail-remote (recipient-match) succeeded %32s [%.4f sec]\n" " " $secs
 			fi
 			print_pct
 		else
 			printf "\r%118s\n" " "
 			if [ $i -eq 1 ] ; then
-				echo "testing spawn-filter qmail-remote REGEXP (recipient-match) failed"
-			elif [ $i -eq 2 ] ; then
-				echo "testing spawn-filter qmail-remote wildmat (recipient-match) failed"
-			elif [ $i -eq 3 ] ; then
 				echo "testing spawn-filter qmail-remote REGEXP (sender-match) failed"
-			elif [ $i -eq 4 ] ; then
+			elif [ $i -eq 2 ] ; then
 				echo "testing spawn-filter qmail-remote wildmat (sender-match) failed"
+			elif [ $i -eq 3 ] ; then
+				echo "testing spawn-filter qmail-remote REGEXP (recipient-match) failed"
+			elif [ $i -eq 4 ] ; then
+				echo "testing spawn-filter qmail-remote wildmat (recipient-match) failed"
 			fi
 			echo body=$body, subject=$subject
 			/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt $cntrldir/filterargs \
@@ -5175,6 +5179,139 @@ test_direct_spawn_filter()
 			exit 1
 		fi
 		/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt
+	done
+	/bin/rm -f $testdir/variables/MATCH_SENDER_DOMAIN $testdir/variables/MATCH_RECIPIENT_DOMAIN
+	for i in 1 2 3 4
+	do
+		sub1=$(echo $local_domain1 | cut -d. -f2-)
+		sub2=$(echo $local_domain2 | cut -d. -f2-)
+		if [ $i -eq 1 -o $i -eq 3 ] ; then
+			(
+				echo ".*\.$sub1:$testdir/bin/filter1"
+				echo ".*\.$sub2:$testdir/bin/filter2"
+			) > $cntrldir/filterargs
+			echo 1 > $testdir/variables/QREGEX
+		else
+			(
+				echo "*.$sub1:$testdir/bin/filter1"
+				echo "*.$sub2:$testdir/bin/filter2"
+			) > $cntrldir/filterargs
+			echo 0 > $testdir/variables/QREGEX
+		fi
+		if [ "$i" -eq 1 -o "$i" -eq 2 ] ; then
+			lfilter=filter2
+			rfilter=filter1
+			> $testdir/variables/MATCH_RECIPIENT_DOMAIN
+			> $testdir/variables/MATCH_SENDER_DOMAIN
+		elif [ "$i" -eq 3 -o "$i" -eq 4 ] ; then
+			lfilter=filter1
+			rfilter=filter2
+			echo 1 > $testdir/variables/MATCH_RECIPIENT_DOMAIN
+			echo 1 > $testdir/variables/MATCH_SENDER_DOMAIN
+		fi
+		(
+			echo "From: $user@$local_domain1"
+			echo "To: $user@$local_domain2"
+			echo "Subject: Test message using qmail-inject"
+			echo "Date: $(date -R)"
+			echo
+			echo "Test message from abcd"
+		) > $tmpdir/mail.txt
+		t1=$(date +"%s.%4N")
+		envdir -c $testdir/variables sh -c \
+			"exec -a qmail-local $sbindir/spawn-filter -- $user \ $testdir/$user $user \"\" \"\" $local_domain2 $user@$local_domain1 ./Maildir/ \"\"" < $tmpdir/mail.txt > $tmpdir/mail.out
+		body=$($e822body < $tmpdir/mail.out)
+		subject=$($e822header -I Subject < $tmpdir/mail.out)
+		if [ "$body" = "Test message from $HOSTNAME" -a "$subject" = "Subject: Testing spawn-filter using $lfilter" ] ; then
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1)}')
+			tcount=$(expr $tcount + 1)
+			if [ $i -eq 1 ] ; then
+				printf "\r  testing spawn-filter REGEXP  qmail-local  (recipient-match) no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 2 ] ; then
+				printf "\r  testing spawn-filter wildmat qmail-local  (recipient-match) no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 3 ] ; then
+				printf "\r  testing spawn-filter REGEXP  qmail-local  (sender-match)    no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 4 ] ; then
+				printf "\r  testing spawn-filter wildmat qmail-local  (sender-match)    no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			fi
+			print_pct
+		else
+			printf "\r%118s\n" " "
+			if [ $i -eq 1 ] ; then
+				echo "testing spawn-filter qmail-local REGEXP (recipient-match) no local/remote directive failed"
+			elif [ $i -eq 2 ] ; then
+				echo "testing spawn-filter qmail-local wildmat (recipient-match) no local/remote directive failed"
+			elif [ $i -eq 3 ] ; then
+				echo "testing spawn-filter qmail-local REGEXP (sender-match) no local/remote directive failed"
+			elif [ $i -eq 4 ] ; then
+				echo "testing spawn-filter qmail-local wildmat (sender-match) no local/remote directive failed"
+			fi
+			echo body=$body, subject=$subject
+			/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt $cntrldir/filterargs \
+				$testdir/bin/filter1 $testdir/bin/filter2 $testdir/bin/spawn-cat
+			exit 1
+		fi
+
+		sub1=$(echo $remote_domain1 | cut -d. -f2-)
+		sub2=$(echo $remote_domain2 | cut -d. -f2-)
+		(
+			echo "From: $user@$remote_domain1"
+			echo "To: $user@$remote_domain2"
+			echo "Subject: Test message using qmail-inject"
+			echo "Date: $(date -R)"
+			echo
+			echo "Test message from abcd"
+		) > $tmpdir/mail.txt
+		if [ $i -eq 1 -o $i -eq 3 ] ; then
+			(
+				echo ".*\.$sub1:$testdir/bin/filter1"
+				echo ".*\.$sub2:$testdir/bin/filter2"
+			) > $cntrldir/filterargs
+			echo 1 > $testdir/variables/QREGEX
+		else
+			(
+				echo "*.$sub1:$testdir/bin/filter1"
+				echo "*.$sub2:$testdir/bin/filter2"
+			) > $cntrldir/filterargs
+			echo 0 > $testdir/variables/QREGEX
+		fi
+		t1=$(date +"%s.%4N")
+		size=$(ls -l $tmpdir/mail.txt|awk '{print $5}')
+		envdir -c $testdir/variables sh -c \
+			"exec -a qmail-remote $sbindir/spawn-filter $remote_domain2 $user@$remote_domain1 \"\" $size $user@$remote_domain2" < $tmpdir/mail.txt > $tmpdir/mail.out
+		body=$($e822body < $tmpdir/mail.out)
+		subject=$($e822header -I Subject < $tmpdir/mail.out)
+		if [ "$body" = "Test message from $HOSTNAME" -a "$subject" = "Subject: Testing spawn-filter using $rfilter" ] ; then
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 | awk '{printf("%0.4f\n", $2-$1)}')
+			tcount=$(expr $tcount + 1)
+			if [ $i -eq 1 ] ; then
+				printf "\r  testing spawn-filter REGEXP  qmail-remote (sender-match)    no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 2 ] ; then
+				printf "\r  testing spawn-filter wildmat qmail-remote (sender-match)    no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 3 ] ; then
+				printf "\r  testing spawn-filter REGEXP  qmail-remote (recipient-match) no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			elif [ $i -eq 4 ] ; then
+				printf "\r  testing spawn-filter wildmat qmail-remote (recipient-match) no local/remote directive succeeded %6s [%.4f sec]\n" " " $secs
+			fi
+			print_pct
+		else
+			printf "\r%118s\n" " "
+			if [ $i -eq 1 ] ; then
+				echo "testing spawn-filter qmail-remote REGEXP (sender-match) no local/remote directive failed"
+			elif [ $i -eq 2 ] ; then
+				echo "testing spawn-filter qmail-remote wildmat (sender-match) no local/remote directive failed"
+			elif [ $i -eq 3 ] ; then
+				echo "testing spawn-filter qmail-remote REGEXP (recipient-match) no local/remote directive failed"
+			elif [ $i -eq 4 ] ; then
+				echo "testing spawn-filter qmail-remote wildmat (recipient-match) no local/remote directive failed"
+			fi
+			echo body=$body, subject=$subject
+			/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt $cntrldir/filterargs \
+				$testdir/bin/filter1 $testdir/bin/filter2 $testdir/bin/spawn-cat
+			exit 1
+		fi
 	done
 	/bin/rm -f $tmpdir/mail.out $tmpdir/mail.txt $cntrldir/filterargs \
 		$testdir/bin/filter1 $testdir/bin/filter2 $testdir/bin/spawn-cat
@@ -6637,42 +6774,42 @@ test_qmail_queue()
 	/bin/rm -f $cntrldir/extraqueue
 
 	if [ ! -f /etc/debian_version ] ; then
-	# test logheader
-	t1=$(date +"%s.%4N")
-	echo "X-Log-Test" > $cntrldir/logheaders
-	exec 45>$tmpdir/logheaderfd
-	echo 45 > $testdir/variables/LOGHEADERFD
-	do_qmail_inject $user@$HOSTNAME $user@$HOSTNAME "Testing logheader" "Test Message for logheader"
-	check_mail_header $maildir X-Remove-Header1 0
-	h4=$header
-	s1=$sleep_secs
-	check_mail_header $maildir X-Remove-Header2 0
-	h5=$header
-	s2=$sleep_secs
-	h=$(cat $tmpdir/logheaderfd)
-	if [ "$h" = "X-Log-Test: Test Header" ] ; then
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
-		tcount=$(expr $tcount + 1)
-		printf "\r  testing mail for logheader feature succeeded %57s [%.4f sec]\n" " " $secs
-		print_pct
-	else
-		echo "h=[$h] h4=[$h4] h5=[$h5]"
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
-		printf "\r%118s\n" " "
-		echo "  testing mail for logheader feature failed [$secs sec]"
-		failed=1
+		# test logheader
+		t1=$(date +"%s.%4N")
+		echo "X-Log-Test" > $cntrldir/logheaders
+		exec 45>$tmpdir/logheaderfd
+		echo 45 > $testdir/variables/LOGHEADERFD
+		do_qmail_inject $user@$HOSTNAME $user@$HOSTNAME "Testing logheader" "Test Message for logheader"
+		check_mail_header $maildir X-Remove-Header1 0
+		h4=$header
+		s1=$sleep_secs
+		check_mail_header $maildir X-Remove-Header2 0
+		h5=$header
+		s2=$sleep_secs
+		h=$(cat $tmpdir/logheaderfd)
+		if [ "$h" = "X-Log-Test: Test Header" ] ; then
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+			tcount=$(expr $tcount + 1)
+			printf "\r  testing mail for logheader feature succeeded %57s [%.4f sec]\n" " " $secs
+			print_pct
+		else
+			echo "h=[$h] h4=[$h4] h5=[$h5]"
+			t2=$(date +"%s.%4N")
+			secs=$(echo $t1 $t2 $s1 $s2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+			printf "\r%118s\n" " "
+			echo "  testing mail for logheader feature failed [$secs sec]"
+			failed=1
+			/bin/rm -f $cntrldir/logheaders
+			exit 1
+		fi
+		check_mail
 		/bin/rm -f $cntrldir/logheaders
-		exit 1
-	fi
-	check_mail
-	/bin/rm -f $cntrldir/logheaders
-	if [ "$h4" = "X-Remove-Header1: This header will be removed" -a "$h5" = "X-Remove-Header2: This header will also be removed" ] ; then
-		ret1=0
-	else
-		ret1=1
-	fi
+		if [ "$h4" = "X-Remove-Header1: This header will be removed" -a "$h5" = "X-Remove-Header2: This header will also be removed" ] ; then
+			ret1=0
+		else
+			ret1=1
+		fi
 	fi
 
 	# test removeheaders
@@ -6710,7 +6847,59 @@ test_qmail_queue()
 	fi
 	check_mail
 	/bin/rm -f $cntrldir/removeheaders
-	/bin/rm -rf $testdir/variables
+
+	# test envheaders
+	t1=$(date +"%s.%4N")
+	(
+	echo "X-Env-Header1"
+	echo "X-Env-Header2"
+	echo "Subject"
+	) > $cntrldir/envheaders
+
+	(
+	echo "#!/bin/sh"
+	echo "if [ "\$X_Env_Header1" != "This is env-header1" ] ; then"
+	echo "  echo \"This email does not contain X_Env_Header1\" 1>&2"
+	echo "  exit 100"
+	echo "fi"
+	echo "if [ "\$X_Env_Header2" != "This is env-header2" ] ; then"
+	echo "  echo \"This email does not contain X_Env_Header2\" 1>&2"
+	echo "  exit 100"
+	echo "fi"
+	echo "echo \"X-Env-Header3: This is env-header3\""
+	echo "exec /bin/cat"
+	) > $testdir/bin/envheaders.sh
+	chmod +x $testdir/bin/envheaders.sh
+	echo ".*:local:$testdir/bin/envheaders.sh" > $cntrldir/filterargs
+	do_qmail_inject $user@$HOSTNAME $testuser@$HOSTNAME "Testing envheaders" "Test Message for envheaders"
+	check_mail_header $testdir/$testuser/Maildir X-Env-Header1 0
+	ret1=$?
+	s1=$sleep_secs
+	h1=$header
+	check_mail_header $testdir/$testuser/Maildir X-Env-Header2 0
+	s2=$sleep_secs
+	h2=$header
+	check_mail_header $testdir/$testuser/Maildir X-Env-Header3 0
+	s3=$sleep_secs
+	h3=$header
+	if [ $ret1 -eq 0 -a "$h1" = "X-Env-Header1: This is env-header1" -a "$h2" = "X-Env-Header2: This is env-header2" -a "$h3" = "X-Env-Header3: This is env-header3" ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $s1 $s2 $s3 | awk '{printf("%0.4f\n", $2-$1-$3-$4-$5)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing mail for envheaders feature succeeded %56s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		printf "\r%118s\n" " "
+		echo "ret=$ret1, h1=$h1, h2=$h2, h3=[$h3]"
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $s1 $s2 $s3 | awk '{printf("%0.4f\n", $2-$1-$3-$4-$5)}')
+		echo "  testing mail for envheaders feature failed [$secs sec]"
+		failed=1
+		/bin/rm -rf $testdir/variables $testdir/bin/envheaders.sh $cntrldir/filterargs
+		exit 1
+	fi
+	check_mail $testdir/$testuser/Maildir
+	/bin/rm -rf $testdir/variables $testdir/bin/envheaders.sh $cntrldir/filterargs
 }
 
 test_dkim()
@@ -7937,6 +8126,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.65  2024-02-09 15:53:31+05:30  Cprogrammer
+# added tests for envheader, filterargs without local/remote directive
+#
 # Revision 1.64  2024-02-07 22:55:53+05:30  Cprogrammer
 # added additional spawn-filter tests
 #
