test-indimail-mta: fixed indentation

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.82 2024-12-12 21:24:18+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.83 2025-02-02 16:41:13+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -803,7 +803,7 @@ run_qmail_send()
 	exec 1>$logdir/$pg1/$logfn
 	exec 2>$logdir/$pg1/$logfn
 	exec 0<&2
-	unset MATCH_RECIPIENT_DOMAIN MATCH_SENDER_DOMAIN QREGEX
+	unset QREGEX MATCH_RECIPIENT_DOMAIN MATCH_SENDER_DOMAIN
 	if [ $# -eq 2 ] ; then
 		case "$2" in
 			1)
@@ -832,9 +832,8 @@ run_qmail_send()
 	echo "$sbindir/spawn-filter"    > $testdir/variables/QMAILLOCAL
 	echo "$sbindir/spawn-filter"    > $testdir/variables/QMAILREMOTE
 	echo "$sbindir/rd-remote"       > $testdir/variables/QREMOTE
-	echo "$QREGEX"                  > $testdir/variables/QREGEX
 
-	[ -n "$QREGEX" ] && echo 1 > $testdir/variables/QREGEX || > $testdir/variables/QREGEX
+	[ -n "$QREGEX" ]                 && echo 1 > $testdir/variables/QREGEX                 || > $testdir/variables/QREGEX
 	[ -n "$MATCH_RECIPIENT_DOMAIN" ] && echo 1 > $testdir/variables/MATCH_RECIPIENT_DOMAIN || > $testdir/variables/MATCH_RECIPIENT_DOMAIN
 	[ -n "$MATCH_SENDER_DOMAIN" ]    && echo 1 > $testdir/variables/MATCH_SENDER_DOMAIN    || > $testdir/variables/MATCH_SENDER_DOMAIN
 	# for ezmlm
@@ -4882,9 +4881,10 @@ test_alias()
 	done
 }
 
-test_rspawn_spawn_filter()
+test_lspawn_rspawn_filter()
 {
 	# test QMAILLOCAL through qmail-lspawn. Default is to match recipient domain in filterargs
+	# hence filter 2 should be in effect
 	(
 	echo "#!/bin/sh"
 	echo "sed -e 's/abcd/$HOSTNAME/' -e 's/Subject: .*/Subject: Testing spawn-filter using filter1/'"
@@ -4896,18 +4896,19 @@ test_rspawn_spawn_filter()
 	echo "exit 0"
 	) > $testdir/bin/filter2
 	chmod +x $testdir/bin/filter1 $testdir/bin/filter2
-	sub1=$(echo $local_domain1 | cut -d. -f2-)
-	sub2=$(echo $local_domain2 | cut -d. -f2-)
+
+	sub1=$(echo $local_domain1 | cut -d. -f2-) # sender    domain
+	sub2=$(echo $local_domain2 | cut -d. -f2-) # recipient domain
 	if [ $1 -eq 1 ] ; then # regular exp for pattern match
-	(
-	echo ".*\.$sub1:local:$testdir/bin/filter1"
-	echo ".*\.$sub2:local:$testdir/bin/filter2"
-	) > $cntrldir/filterargs
+		(
+		echo ".*\.$sub1:local:$testdir/bin/filter1"
+		echo ".*\.$sub2:local:$testdir/bin/filter2"
+		) > $cntrldir/filterargs
 	else # wildmat for pattern match
-	(
-	echo "*.$sub1:local:$testdir/bin/filter1"
-	echo "*.$sub2:local:$testdir/bin/filter2"
-	) > $cntrldir/filterargs
+		(
+		echo "*.$sub1:local:$testdir/bin/filter1"
+		echo "*.$sub2:local:$testdir/bin/filter2"
+		) > $cntrldir/filterargs
 	fi
 
 	t1=$(date +"%s.%4N")
@@ -4939,17 +4940,17 @@ test_rspawn_spawn_filter()
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		tcount=$(expr $tcount + 1)
 		if [ $1 -eq 1 ] ; then
-		printf "\r  testing spawn-filter REGEXP  qmail-lspawn using QMAILLOCAL  (recipient-match) succeeded %14s [%.4f sec]\n" " " $secs
+			printf "\r  testing spawn-filter REGEXP  qmail-lspawn using QMAILLOCAL  (recipient-match) succeeded %14s [%.4f sec]\n" " " $secs
 		else
-		printf "\r  testing spawn-filter wildmat qmail-lspawn using QMAILLOCAL  (recipient-match) succeeded %14s [%.4f sec]\n" " " $secs
+			printf "\r  testing spawn-filter wildmat qmail-lspawn using QMAILLOCAL  (recipient-match) succeeded %14s [%.4f sec]\n" " " $secs
 		fi
 		print_pct
 	else
 		printf "\r%118s\n" " "
 		if [ $1 -eq 1 ] ; then
-		echo "testing spawn-filter REGEXP qmail-lspawn using (recipient-match) QMAILLOCAL failed"
+			echo "testing spawn-filter REGEXP qmail-lspawn using (recipient-match) QMAILLOCAL failed"
 		else
-		echo "testing spawn-filter wildmat qmail-lspawn using (recipient-match) QMAILLOCAL failed"
+			echo "testing spawn-filter wildmat qmail-lspawn using (recipient-match) QMAILLOCAL failed"
 		fi
 		(
 		echo "body=[$body], subject=[$subject]"
@@ -4979,17 +4980,17 @@ test_rspawn_spawn_filter()
 	sub1=$(echo $remote_domain1 | cut -d. -f2-)
 	sub2=$(echo $remote_domain2 | cut -d. -f2-)
 	if [ $1 -eq 1 ] ; then # regular exp for pattern match
-	echo ".*:d:$testuser@$HOSTNAME:remote"    > $cntrldir/redirectremote
-	(
-	echo ".*\.$sub1:remote:$testdir/bin/filter1"
-	echo ".*\.$sub2:remote:$testdir/bin/filter2"
-	) > $cntrldir/filterargs
+		echo ".*:d:$testuser@$HOSTNAME:remote"    > $cntrldir/redirectremote
+		(
+		echo ".*\.$sub1:remote:$testdir/bin/filter1"
+		echo ".*\.$sub2:remote:$testdir/bin/filter2"
+		) > $cntrldir/filterargs
 	else # wildmat for pattern match
-	echo "*:d:$testuser@$HOSTNAME:remote"    > $cntrldir/redirectremote
-	(
-	echo "*.$sub1:remote:$testdir/bin/filter1"
-	echo "*.$sub2:remote:$testdir/bin/filter2"
-	) > $cntrldir/filterargs
+		echo "*:d:$testuser@$HOSTNAME:remote"    > $cntrldir/redirectremote
+		(
+		echo "*.$sub1:remote:$testdir/bin/filter1"
+		echo "*.$sub2:remote:$testdir/bin/filter2"
+		) > $cntrldir/filterargs
 	fi
 
 	(
@@ -5021,22 +5022,25 @@ test_rspawn_spawn_filter()
 		body=""
 		subject=""
 	fi
+	rd_remote_flag=0
 	if [ "$body" = "Test message from $HOSTNAME" -a "$subject" = "Subject: Testing spawn-filter using filter1" ] ; then
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
 		tcount=$(expr $tcount + 1)
 		if [ $1 -eq 1 ] ; then
-		printf "\r  testing spawn-filter REGEXP  qmail-rspawn using QMAILREMOTE (sender-match)    succeeded %14s [%.4f sec]\n" " " $secs
+			rd_remote_flag=1
+			printf "\r  testing spawn-filter REGEXP  qmail-rspawn using QMAILREMOTE (sender-match)    succeeded %14s [%.4f sec]\n" " " $secs
 		else
-		printf "\r  testing spawn-filter wildmat qmail-rspawn using QMAILREMOTE (sender-match)    succeeded %14s [%.4f sec]\n" " " $secs
+			rd_remote_flag=1
+			printf "\r  testing spawn-filter wildmat qmail-rspawn using QMAILREMOTE (sender-match)    succeeded %14s [%.4f sec]\n" " " $secs
 		fi
 		print_pct
 	else
 		printf "\r%118s\n" " "
 		if [ $1 -eq 1 ] ; then
-		echo "testing spawn-filter REGEXP qmail-rspawn using QMAILREMOTE (sender-match) failed"
+			echo "testing spawn-filter REGEXP qmail-rspawn using QMAILREMOTE (sender-match) failed"
 		else
-		echo "testing spawn-filter wildmat qmail-rspawn using QMAILREMOTE (sender-match) failed"
+			echo "testing spawn-filter wildmat qmail-rspawn using QMAILREMOTE (sender-match) failed"
 		fi
 		(
 		echo "body=$body, subject=$subject"
@@ -5057,6 +5061,30 @@ test_rspawn_spawn_filter()
 		exit 1
 	fi
 	/bin/rm -f $cntrldir/filterargs $cntrldir/smtproutes $testdir/bin/filter1 $testdir/bin/filter2
+	if [ $rd_remote_flag -eq 1 ] ; then
+		printf "\r  testing rd-remote qmail-rspawn using QREMOTE succeeded %47s [%.4f sec]\n" " " $secs
+		print_pct
+		tcount=$(expr $tcount + 1)
+	else
+		printf "\r%118s\n" " "
+		echo "testing rd-remote qmail-rspawn using QREMOTE failed"
+		(
+		echo "body=$body, subject=$subject"
+		if [ $log_type -eq 1 ] ; then
+			echo "$logdir/smtpd/smtpd.log"
+			cat $logdir/smtpd/smtpd.log
+			echo "$logdir/qmail-send/qmail-send.log"
+			cat $logdir/qmail-send/qmail-send.log
+		elif [ -f $logdir/qmail-send/current ] ; then
+			echo "$logdir/smtpd/current"
+			cat $logdir/smtpd/current
+			echo "$logdir/qmail-send/current"
+			cat $logdir/qmail-send/current
+		fi
+		)|less
+		failed=1
+		exit 1
+	fi
 }
 
 test_direct_spawn_filter()
@@ -6277,7 +6305,7 @@ do_without_svscan()
 	test_direct_spawn_filter
 	for i in 1 2
 	do
-		test_rspawn_spawn_filter $i
+		test_lspawn_rspawn_filter $i
 		if [ $i -eq 1 ] ; then
 			terminate_send qmail-send "$send_pid"
 			send_pid=""
@@ -8995,7 +9023,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=325
+	total_tests=327
 fi
 failed=0
 do_setup
@@ -9050,6 +9078,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.83  2025-02-02 16:41:13+05:30  Cprogrammer
+# fixed indentation at few places
+#
 # Revision 1.82  2024-12-12 21:24:18+05:30  Cprogrammer
 # updated test script for svscan log
 #
