added test for domainqueue

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.44 2023-10-30 21:10:56+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.45 2023-11-01 21:59:39+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -104,6 +104,7 @@ do_cleanup_failed()
 	sudo /bin/rm -rf $servicedir
 	sudo /bin/rm -rf $logdir
 	sudo /bin/rm -rf $testdir/queue
+	sudo /bin/rm -rf $testdir/domainqueue
 	sudo /bin/rm -rf $testdir/bin
 	sudo /bin/rm -rf $tmpdir
 	sudo /bin/rm -rf $testdir/run
@@ -581,6 +582,17 @@ test_tcpclient_script()
 	fi
 }
 
+# redirect remote mail to $1
+create_qmail_remote()
+{
+	# qmail-remote host sender qqeh size recip [ recip ... ]
+	(
+	echo "#!/bin/sh"
+	echo "exec $qmail_remote $HOSTNAME \"\$2\" \"\$3\" \"\$4\" \"$1\""
+	) > $testdir/bin/qmail-remote
+	chmod +x $testdir/bin/qmail-remote
+}
+
 run_qmail_send()
 {
 	(
@@ -599,7 +611,6 @@ run_qmail_send()
 	echo "fi"
 	) > $testdir/bin/qmail-getpw
 	chmod 755 $testdir/bin/qmail-getpw
-	create_qmail_remote $testuser@$HOSTNAME
 	(
 	exec 1>$logdir/qmail-send/qmail-send.log
 	exec 2>$logdir/qmail-send/qmail-send.log
@@ -710,6 +721,70 @@ test_qmail_inject()
 	done
 }
 
+test_domainqueue()
+{
+	echo "gmail.com:QUEUEDIR=$testdir/domainqueue" > $cntrldir/domainqueue
+	(
+	echo "$HOSTNAME:127.0.0.1:$smtp_port"
+	echo "gmail.com:127.0.0.1:$smtp_port"
+	) > $cntrldir/smtproutes
+	sudo queue-fix -s 23 -b 0 $testdir/domainqueue
+	# redirect remote mail from gmail.com to $testuser@$HOSTNAME
+	(
+	exec 1>$logdir/qmail-send/qmail-send2.log
+	exec 2>$logdir/qmail-send/qmail-send2.log
+	exec 0<&2
+	sudo env - PATH=/bin:/usr/sbin \
+			USE_QPWGR=1 \
+			BIGTODO=0 \
+			CONFSPLIT=23 \
+			CONTROLDIR=$cntrldir \
+			CERTDIR=$certdir \
+			QUEUEDIR=$testdir/domainqueue \
+			ASSIGNDIR=$testdir/etc/users \
+			QMAILREMOTE=$sbindir/spawn-filter \
+			QREMOTE=$testdir/bin/qmail-remote \
+			PASSWD_FILE=$testdir/etc/passwd \
+		$qmail_start -s ./Maildir/
+	) &
+	send_pid2=$(jobs -r -p | tail -1)
+
+	(
+	echo
+	echo "Testing domainqueue"
+	) > $tmpdir/mail.txt
+	swaks -S --data - --to $user@$ext_domain --from $user@$HOSTNAME --server localhost \
+		--port $smtp_port --a LOGIN -au $user@$HOSTNAME -ap "abcd12345678" \
+		< $tmpdir/mail.txt >$tmpdir/swaks.$$
+	/bin/rm -f $tmpdir/mail.txt
+	t1=$(date +"%s.%4N")
+	check_mail $testdir/$testuser/Maildir 1 2>/dev/null
+	ret=$?
+	if [ -n "$mail_file" ] ; then
+		body=$($e822body < $testdir/$testuser/Maildir/new/$mail_file)
+		/bin/rm -f $testdir/$testuser/Maildir/new/$mail_file
+	else
+		body=""
+	fi
+	sudo kill $send_pid2
+	if [ "$body" = "Testing domainqueue" -a $ret -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing SMTP domainqueue succeeded %67s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		echo "body=[$body], ret=$ret"
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		printf "\r%118s\n" " "
+		echo "  testing SMTP domainqueue failed [$secs sec]"
+		failed=1
+		exit 1
+	fi
+	/bin/rm -f $cntrldir/domainqueue $cntrldir/smtproutes
+}
+
 do_qmail_inject()
 {
 	# $1 : From
@@ -755,16 +830,6 @@ create_authsmtp()
 	echo "exec \$*"
 	) > $testdir/bin/authsmtp
 	chmod +x $testdir/bin/authsmtp
-}
-
-create_qmail_remote()
-{
-	# qmail-remote host sender qqeh size recip [ recip ... ]
-	(
-	echo "#!/bin/sh"
-	echo "exec $qmail_remote $HOSTNAME \"\$2\" \"\$3\" \"\$4\" \"$1\""
-	) > $testdir/bin/qmail-remote
-	chmod +x $testdir/bin/qmail-remote
 }
 
 start_tcpserver_smtp()
@@ -1649,7 +1714,6 @@ test_qqeh()
 		exit 1
 	fi
 
-	create_qmail_remote $testuser@$HOSTNAME
 	echo "$HOSTNAME:127.0.0.1:$smtp_port" > $cntrldir/smtproutes
 	t1=$(date +"%s.%4N")
 	(
@@ -1930,7 +1994,7 @@ test_smtp_chk_sender()
 	# to $HOSTNAME using $testdir/bin/qmail-remote 
 	# Also, $testdir/bin/qmail-remote changes the recipient
 	# to $testuser@$HOSTNAME
-	create_qmail_remote $testuser@$HOSTNAME
+	#create_qmail_remote $testuser@$HOSTNAME
 	# we require authenticted SMTP because of CHECKSENDER
 	find $testdir/$testuser/Maildir -type f -exec /bin/rm -f {} \;
 	echo "$HOSTNAME:127.0.0.1:$smtp_port $user@$HOSTNAME abcd12345678" > $cntrldir/smtproutes
@@ -4513,6 +4577,9 @@ do_without_svscan()
 
 	test_spawn_filter
 
+	create_authsmtp
+	create_qmail_remote $testuser@$HOSTNAME
+	test_domainqueue
 	test_spamfilter
 	test_qhpsi
 	test_qqeh
@@ -4529,7 +4596,6 @@ do_without_svscan()
 	terminate_smtp_qmtp $qmtp_pid
 	virtual_setup 0
 
-	create_authsmtp
 	test_qmail_remote_auth "PLAIN"
 	test_qmail_remote_auth "LOGIN"
 	test_qmail_remote_auth "CRAM-MD5"
@@ -6973,6 +7039,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.45  2023-11-01 21:59:39+05:30  Cprogrammer
+# added test for domainqueue
+#
 # Revision 1.44  2023-10-30 21:10:56+05:30  Cprogrammer
 # added test for smtp access list
 #
