bug - error in regexp treated as match

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -5026,27 +5026,9 @@ test_spf()
 
 test_qmail_queue()
 {
+	# sender rule
 	t1=$(date +"%s.%4N")
-	echo "F:!.*@$HOSTNAME:$incarchive@$HOSTNAME" > $cntrldir/mailarchive
-	do_qmail_inject $user@$vdomain $user@$HOSTNAME "Test Mail Archival" "Test Message for Mail Archival"
-	check_mail $testdir/$incarchive/Maildir
-	if [ $? -eq 0 ] ; then
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
-		tcount=$(expr $tcount + 1)
-		printf "\r  testing incoming mail archival with sender based rule succeeded %38s [%.4f sec]\n" " " $secs
-		print_pct
-	else
-		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
-		printf "\r%118s\n" " "
-		echo "  testing incoming mail archival with sender based rule failed [$secs sec]"
-		failed=1
-		exit 1
-	fi
-
-	t1=$(date +"%s.%4N")
-	echo "F:.*@$HOSTNAME:$outarchive@$HOSTNAME" > $cntrldir/mailarchive
+	echo "F:.*@$HOSTNAME$:$outarchive@$HOSTNAME" > $cntrldir/mailarchive
 	do_qmail_inject $user@$HOSTNAME $user@$HOSTNAME "Test outgoing Mail Archival" "Test Message to test outgoing Mail Archival"
 	check_mail $testdir/$outarchive/Maildir
 	if [ $? -eq 0 ] ; then
@@ -5064,8 +5046,29 @@ test_qmail_queue()
 		exit 1
 	fi
 
+	# sender negative rule
 	t1=$(date +"%s.%4N")
-	echo "T:.*@$HOSTNAME:$incarchive@$HOSTNAME" > $cntrldir/mailarchive
+	echo "F:!.*@$HOSTNAME$:$incarchive@$HOSTNAME" > $cntrldir/mailarchive
+	do_qmail_inject $user@$vdomain $user@$HOSTNAME "Test Mail Archival" "Test Message for Mail Archival"
+	check_mail $testdir/$incarchive/Maildir
+	if [ $? -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing incoming mail archival with sender based rule succeeded %38s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		printf "\r%118s\n" " "
+		echo "  testing incoming mail archival with sender based rule failed [$secs sec]"
+		failed=1
+		exit 1
+	fi
+
+	# recipient rule
+	t1=$(date +"%s.%4N")
+	echo "T:.*@$HOSTNAME$:$incarchive@$HOSTNAME" > $cntrldir/mailarchive
 	do_qmail_inject $user@$vdomain $user@$HOSTNAME "Test incoming Mail Archival" "Test Message to test incoming Mail Archival"
 	check_mail $testdir/$incarchive/Maildir
 	if [ $? -eq 0 ] ; then
@@ -5083,9 +5086,10 @@ test_qmail_queue()
 		exit 1
 	fi
 
+	# receipient negative rule
 	t1=$(date +"%s.%4N")
 	virtual_setup 1
-	echo "T:!.*@$HOSTNAME:$outarchive@$HOSTNAME" > $cntrldir/mailarchive
+	echo "T:!.*@$HOSTNAME$:$outarchive@$HOSTNAME" > $cntrldir/mailarchive
 	do_qmail_inject $user@$HOSTNAME $user@$vdomain "Testing outgoing Mail Archival" "Test Message to test outgoing Mail Archival"
 	check_mail $testdir/$outarchive/Maildir
 	if [ $? -eq 0 ] ; then
@@ -5106,6 +5110,27 @@ test_qmail_queue()
 	virtual_setup 0
 	/bin/rm -f $cntrldir/mailarchive
 
+	# invalid regex in mailarchive
+	t1=$(date +"%s.%4N")
+	echo "T:*@$vdomain$:$incarchive@$HOSTNAME" > $cntrldir/mailarchive
+	do_qmail_inject $user@$vdomain $user@$HOSTNAME "Test incoming Mail Archival" "Test Message to test incoming Mail Archival"
+	check_mail $testdir/$incarchive/Maildir 2>/dev/null
+	if [ $? -ne 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 1)
+		printf "\r  testing mail archival with invalid recipient based rule succeeded %36s [%.4f sec]\n" " " $secs
+		print_pct
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		printf "\r%118s\n" " "
+		echo "  testing mail archival with invalid recipient based rule failed [$secs sec]"
+		failed=1
+		exit 1
+	fi
+
+	# test extra queue
 	t1=$(date +"%s.%4N")
 	(
 	echo "$incarchive"
@@ -5135,6 +5160,7 @@ test_qmail_queue()
 	fi
 	/bin/rm -f $cntrldir/extraqueue
 
+	# test logheader
 	t1=$(date +"%s.%4N")
 	echo "X-Log-Test" > $cntrldir/logheaders
 	exec 45>/tmp/logheaderfd
@@ -5170,6 +5196,7 @@ test_qmail_queue()
 		ret1=1
 	fi
 
+	# test removeheaders
 	t1=$(date +"%s.%4N")
 	(
 	echo "X-Remove-Header1"
@@ -6705,7 +6732,7 @@ fi
 if [ -f $testdir/qtotal.count ] ; then
 	total_tests=$(cat $testdir/qtotal.count)
 else
-	total_tests=247
+	total_tests=248
 fi
 failed=0
 do_setup
