added tests for qmail-smtpd MASQUERADE option

diff --git a/indimail-mta-x/tests/test-indimail-mta b/indimail-mta-x/tests/test-indimail-mta
--- a/indimail-mta-x/tests/test-indimail-mta
+++ b/indimail-mta-x/tests/test-indimail-mta
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: test-indimail-mta,v 1.29 2023-10-07 08:43:39+05:30 Cprogrammer Exp mbhangui $
+# $Id: test-indimail-mta,v 1.30 2023-10-11 14:55:19+05:30 Cprogrammer Exp mbhangui $
 #
 start=$(date +'%s')
 user=$(whoami)
@@ -685,6 +685,8 @@ create_authsmtp()
 	echo "echo \$var | tr [\" \"] [\"\\0\"] 1>&4"
 	echo "if [ \"\$user\" = \"$user@$HOSTNAME\" -a \"\$pass\" = \"abcd12345678\" ] ; then"
 	echo "	exit 0"
+	echo "elif [ \"\$user\" = \"$testuser@$HOSTNAME\" -a \"\$pass\" = \"abcd87654321\" ] ; then"
+	echo "	exit 0"
 	echo "fi"
 	echo "exec \$*"
 	) > $testdir/bin/authsmtp
@@ -1244,7 +1246,7 @@ test_smtp_chk_sender()
 	ret2=$?
 	s1=$sleep_secs
 
-	# Second: This should be denied
+	# Second: This should be denied without MASQUERADE
 	swaks -S --to $user@$HOSTNAME --from $user@$ext_domain --server localhost \
 		--port $smtp_port --a LOGIN -au $user@$HOSTNAME -ap "abcd12345678" >$testdir/tmp/swaks.$$
 	ret3=$?
@@ -1276,6 +1278,7 @@ test_smtp_chk_sender()
 	else
 		ret7=1
 	fi
+
 	if [ $ret1 -eq 0 -a $ret2 -eq 0 -a $ret3 -ne 0 -a $ret4 -eq 0 -a $ret5 -eq 0 -a $ret6 -ne 0 -a $ret7 -eq 0 ] ; then
 		t2=$(date +"%s.%4N")
 		secs=$(echo $t1 $t2 $s1 $s2 $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-$4-$5)}')
@@ -1299,6 +1302,82 @@ test_smtp_chk_sender()
 		exit 1
 	fi
 
+	# fifth: This should be allowed with MASQUERADE
+	echo "" > $servicedir/smtpd/variables/MASQUERADE
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
+	t1=$(date +"%s.%4N")
+	swaks -S --to $user@$HOSTNAME --from $user@$ext_domain --server localhost \
+		--port $smtp_port --a LOGIN -au $user@$HOSTNAME -ap "abcd12345678" > $testdir/tmp/swaks.$$
+	check_mail
+	ret1=$?
+	if [ $ret1 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		tcount=$(expr $tcount + 4)
+		printf "  testing MASQUERADE any option succeeded %62s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $sleep_secs | awk '{printf("%0.4f\n", $2-$1-$3)}')
+		echo "  testing MASQUERADE any option failed [$secs sec]"
+		(
+		echo "$logdir/smtpd/current"
+		cat $logdir/smtpd/current
+		echo "$logdir/qmail-send/current"
+		cat $logdir/qmail-send/current
+		)|less
+		failed=1
+		exit 1
+	fi
+
+	# sixth: This should be denied with MASQUERADE
+	echo $testuser@$HOSTNAME > $servicedir/smtpd/variables/MASQUERADE
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
+
+	t1=$(date +"%s.%4N")
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost \
+		--port $smtp_port --a LOGIN -au $testuser@$HOSTNAME -ap "abcd87654321" >$testdir/tmp/swaks.$$
+	ret1=$?
+	l1=$(sed -n 1p < $testdir/tmp/swaks.$$)
+	if [ $ret1 -eq 0 ] ; then
+		check_mail
+	fi
+	echo "$l1" | grep ".*553 sorry, this MTA does not accept masquerading/forging, auth <$testuser@$HOSTNAME> #5.7.1" > /dev/null
+	ret2=$?
+
+	# seventh: This should be allowed with MASQUERADE
+	echo $user@$HOSTNAME > $servicedir/smtpd/variables/MASQUERADE
+	sudo svc -r $servicedir/smtpd
+	sleep 2
+	swaks -S --to $user@$HOSTNAME --from $user@$HOSTNAME --server localhost \
+		--port $smtp_port --a LOGIN -au $testuser@$HOSTNAME -ap "abcd87654321"
+	ret3=$?
+	check_mail
+	ret4=$?
+	s1=$sleep_secs
+	/bin/rm -f $testdir/tmp/swaks.$$
+
+	if [ $ret1 -ne 0 -a $ret2 -eq 0 -a $ret3 -eq 0 -a $ret4 -eq 0 ] ; then
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $s1 2 | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		tcount=$(expr $tcount + 4)
+		printf "  testing MASQUERADE user option succeeded %61s [%.4f sec]\n" " " $secs
+	else
+		t2=$(date +"%s.%4N")
+		secs=$(echo $t1 $t2 $s1 $s2 $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-$4-$5)}')
+		echo "  testing MASQUERADE user option failed %61s [$secs sec]"
+		(
+		echo "ret1=$ret1, ret2=$ret2, ret3=$ret3, ret4=$ret4"
+		echo "$logdir/smtpd/current"
+		cat $logdir/smtpd/current
+		echo "$logdir/qmail-send/current"
+		cat $logdir/qmail-send/current
+		)|less
+		failed=1
+		exit 1
+	fi
+
 	t1=$(date +"%s.%4N")
 	# now test checksenderdomains
 	touch $cntrldir/chksenderdomains
@@ -1310,28 +1389,36 @@ test_smtp_chk_sender()
 	/bin/rm -f $testdir/tmp/swaks.$$
 
 	echo "@$HOSTNAME" > $cntrldir/chksenderdomains
+	/bin/rm -f $servicedir/smtpd/variables/MASQUERADE
 	sudo svc -r $servicedir/smtpd
 	sleep $sleep_int
 	# second: This should be denied
 	swaks -S --to $user@$HOSTNAME --from $user@$ext_domain --server localhost \
 		--port $smtp_port --a LOGIN -au $user@$HOSTNAME -ap "abcd12345678" >$testdir/tmp/swaks.$$
 	ret2=$?
-	/bin/rm -f $cntrldir/chksenderdomains $testdir/tmp/swaks.$$
-	> $servicedir/smtpd/variables/CHECKSENDER
-	sudo svc -r $servicedir/smtpd
-	sleep $sleep_int
 	if [ $ret1 -eq 0 -a $ret2 -ne 0 ] ; then
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-(2*$4))}')
+		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
 		tcount=$(expr $tcount + 4)
 		printf "  testing chksender control file succeeded %61s [%.4f sec]\n" " " $secs
 	else
 		t2=$(date +"%s.%4N")
-		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-(2*$4))}')
-		echo "  testing chksender control file failed    [$secs sec]"
+		secs=$(echo $t1 $t2 $sleep_secs $sleep_int | awk '{printf("%0.4f\n", $2-$1-$3-$4)}')
+		echo "  testing chksender control file failed [$secs sec]"
+		(
+		echo "ret1=$ret1, ret2=$ret2"
+		echo "$logdir/smtpd/current"
+		cat $logdir/smtpd/current
+		echo "$logdir/qmail-send/current"
+		cat $logdir/qmail-send/current
+		)|less
 		failed=1
 		exit 1
 	fi
+	/bin/rm -f $cntrldir/chksenderdomains $testdir/tmp/swaks.$$
+	> $servicedir/smtpd/variables/CHECKSENDER
+	sudo svc -r $servicedir/smtpd
+	sleep $sleep_int
 }
 
 test_smtp_surbl()
@@ -5465,6 +5552,9 @@ exit 0
 
 #
 # $Log: test-indimail-mta,v $
+# Revision 1.30  2023-10-11 14:55:19+05:30  Cprogrammer
+# added test for MASQUERADE
+#
 # Revision 1.29  2023-10-07 08:43:39+05:30  Cprogrammer
 # reduce test time
 #
