fixed cronlist.q path

diff --git a/indimail-mta-2.3/indimail-mta.spec.in b/indimail-mta-2.3/indimail-mta.spec.in
--- a/indimail-mta-2.3/indimail-mta.spec.in
+++ b/indimail-mta-2.3/indimail-mta.spec.in
@@ -1,6 +1,6 @@
 #
 #
-# $Id: indimail-mta.spec.in,v 1.131 2018-01-24 12:58:38+05:30 Cprogrammer Exp mbhangui $
+# $Id: indimail-mta.spec.in,v 1.132 2018-01-26 12:05:14+05:30 Cprogrammer Exp mbhangui $
 %undefine _missing_build_ids_terminate_build
 %global _unpackaged_files_terminate_build 1
 %global debug_package %{nil}
@@ -588,6 +588,8 @@ do
   echo ../certs/$i 1>&3
   $TOUCH %{buildroot}%{qsysconfdir}/certs/$i
 done
+echo "%ghost %config(missingok)                         %{qsysconfdir}/resolv.conf"
+echo ../resolv.conf 1>&3
 ) > config_files.list 3>%{buildroot}%{qsysconfdir}/controlfiles.q
 
 %if %{undefined suse_version} && %{undefined sles_version}
@@ -1639,19 +1641,19 @@ if [ -f %{_prefix}/bin/svok ] ; then
       /bin/systemctl stop svscan > /dev/null 2>&1
     elif test -x %{_prefix}/sbin/initsvc
     then
-      if [ -x /etc/init.d/indimail ] ; then
-        %{_prefix}/sbin/initsvc -status || /etc/init.d/indimail stop || true
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_prefix}/sbin/initsvc -status || %{_sysconfdir}/init.d/indimail stop || true
       else
         %{_prefix}/sbin/initsvc -status || true
       fi
       %{_prefix}/sbin/initsvc -off || true
     else
-      if [ -x /etc/init.d/indimail ] ; then
-        /etc/init.d/indimail stop
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_sysconfdir}/init.d/indimail stop
       fi
-      /bin/grep "^SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
+      /bin/grep "^SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
       if [ $? -eq 0 ] ; then
-        %{__sed} -i 's{^SV:{#SV:{' /etc/inittab
+        %{__sed} -i 's{^SV:{#SV:{' %{_sysconfdir}/inittab
         if [ $? -eq 0 ] ; then
           /sbin/init q
         fi
@@ -1743,10 +1745,10 @@ if [ $argv1 -eq 2 ] ; then # upgrade
     echo "Running Custom Upgrade Script for post upgrade"
     /bin/sh %{libexecdir}/qupgrade.sh post upgrade %{version} $*
   fi
-  if [ -f /etc/init.d/indimail ] ; then
-    cmp -s %{_prefix}/bin/qmailctl /etc/init.d/indimail >/dev/null 2>&1
+  if [ -f %{_sysconfdir}/init.d/indimail ] ; then
+    cmp -s %{_prefix}/bin/qmailctl %{_sysconfdir}/init.d/indimail >/dev/null 2>&1
     if [ $? -ne 0 ] ; then
-      %{__cp} %{_prefix}/bin/qmailctl /etc/init.d/indimail
+      %{__cp} %{_prefix}/bin/qmailctl %{_sysconfdir}/init.d/indimail
     fi
   fi
   if [ -x /bin/systemctl -a -d /lib/systemd/system ] ; then
@@ -1757,22 +1759,22 @@ if [ $argv1 -eq 2 ] ; then # upgrade
     cmp -s %{shareddir}/boot/systemd /usr/lib/systemd/system/svscan.service >/dev/null 2>&1
     %{__cp} %{shareddir}/boot/systemd /usr/lib/systemd/system/svscan.service
     /bin/systemctl daemon-reload
-  elif [ -f /sbin/initctl -a -d /etc/init ] ; then
-    cmp -s %{shareddir}/boot/upstart /etc/init/svscan.conf >/dev/null 2>&1
-    %{__cp} %{shareddir}/boot/upstart /etc/init/svscan.conf
-  elif [ -d /etc/event.d ] ; then
-    cmp -s %{shareddir}/boot/upstart /etc/event.d/upstart >/dev/null 2>&1
-    %{__cp} %{shareddir}/boot/upstart /etc/event.d
+  elif [ -f /sbin/initctl -a -d %{_sysconfdir}/init ] ; then
+    cmp -s %{shareddir}/boot/upstart %{_sysconfdir}/init/svscan.conf >/dev/null 2>&1
+    %{__cp} %{shareddir}/boot/upstart %{_sysconfdir}/init/svscan.conf
+  elif [ -d %{_sysconfdir}/event.d ] ; then
+    cmp -s %{shareddir}/boot/upstart %{_sysconfdir}/event.d/upstart >/dev/null 2>&1
+    %{__cp} %{shareddir}/boot/upstart %{_sysconfdir}/event.d
   elif [ -d /System/Library/LaunchDaemons ] ; then
     cmp -s %{shareddir}/boot/indimail.plist /System/Library/LaunchDaemons >/dev/null 2>&1
     %{__cp} %{shareddir}/boot/indimail.plist /System/Library/LaunchDaemons
   fi
   # selinux
   %{_prefix}/sbin/svctool --servicedir=%{servicedir} --config=qselinux
-  if [ -f /etc/inittab ] ; then # one of these days, this will disappear
-    /bin/grep "^#SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null 2>&1
+  if [ -f %{_sysconfdir}/inittab ] ; then # one of these days, this will disappear
+    /bin/grep "^#SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null 2>&1
     if [ $? -eq 0 ] ; then
-      %{__sed} -i 's{^#SV:{SV:{' /etc/inittab
+      %{__sed} -i 's{^#SV:{SV:{' %{_sysconfdir}/inittab
     fi
   fi
   ) >> /tmp/%{name}-setup.log 2>&1
@@ -2038,9 +2040,9 @@ done
 echo "adding indimail startup"
 %{_prefix}/sbin/svctool --config=add-boot
 
-if [ -f %{_sysconfdir}/cronlist.q -a -d /etc/cron.d ] ; then
+if [ -f %{qsysconfdir}/cronlist.q -a -d %{_sysconfdir}/cron.d ] ; then
   echo "adding cron entries"
-  %{__cp} %{_sysconfdir}/cronlist.q /etc/cron.d
+  %{__cp} %{qsysconfdir}/cronlist.q %{_sysconfdir}/cron.d
 fi
 
 if [ -f %{libexecdir}/qupgrade.sh ] ; then
@@ -2062,7 +2064,7 @@ else
   if [ -f %{_prefix}/sbin/initsvc ] ; then
   echo "1. Issue %{_prefix}/sbin/initsvc -on"
   else
-  echo "1. Issue /etc/init.d/indimail start"
+  echo "1. Issue %{_sysconfdir}/init.d/indimail start"
   fi
   echo "2. Issue /sbin/init q to start services"
   count=2
@@ -2114,19 +2116,19 @@ if [ -f %{_prefix}/bin/svok ] ; then
       /bin/systemctl stop svscan > /dev/null 2>&1
     elif test -x %{_prefix}/sbin/initsvc
     then
-      if [ -x /etc/init.d/indimail ] ; then
-        %{_prefix}/sbin/initsvc -status || /etc/init.d/indimail stop || true
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_prefix}/sbin/initsvc -status || %{_sysconfdir}/init.d/indimail stop || true
       else
         %{_prefix}/sbin/initsvc -status || true
       fi
       %{_prefix}/sbin/initsvc -off || true
     else
-      if [ -x /etc/init.d/indimail ] ; then
-        /etc/init.d/indimail stop
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_sysconfdir}/init.d/indimail stop
       fi
-      /bin/grep "^SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
+      /bin/grep "^SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
       if [ $? -eq 0 ] ; then
-        %{__sed} -i 's{^SV:{#SV:{' /etc/inittab
+        %{__sed} -i 's{^SV:{#SV:{' %{_sysconfdir}/inittab
         if [ $? -eq 0 ] ; then
           /sbin/init q
         fi
@@ -2141,7 +2143,7 @@ if [ -f %{libexecdir}/qupgrade.sh ] ; then
   /bin/sh %{libexecdir}/qupgrade.sh preun uninstall %{version} "$argv1"
 fi
 
-if [ -f /etc/init.d/sendmail ] ; then
+if [ -f %{_sysconfdir}/init.d/sendmail ] ; then
   if [ -f /sbin/chkconfig ] ; then
     /sbin/chkconfig --add sendmail
   fi
@@ -2244,9 +2246,9 @@ if [ $count -eq 0 ] ; then # ignore disabled services
   %{__rm} -rf %{servicedir} || true
 fi
 
-if [ -d /etc/cron.d ] ; then
+if [ -d %{_sysconfdir}/cron.d ] ; then
   echo "removing cron entries"
-  %{__rm} -f /etc/cron.d/cronlist.q
+  %{__rm} -f %{_sysconfdir}/cron.d/cronlist.q
 fi
 
 echo "removing logs"
@@ -2313,19 +2315,19 @@ if [ -f %{_prefix}/bin/svok ] ; then
       /bin/systemctl stop svscan > /dev/null 2>&1
     elif test -x %{_prefix}/sbin/initsvc
     then
-      if [ -x /etc/init.d/indimail ] ; then
-        %{_prefix}/sbin/initsvc -status || /etc/init.d/indimail stop || true
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_prefix}/sbin/initsvc -status || %{_sysconfdir}/init.d/indimail stop || true
       else
         %{_prefix}/sbin/initsvc -status || true
       fi
       %{_prefix}/sbin/initsvc -off || true
     else
-      if [ -x /etc/init.d/indimail ] ; then
-        /etc/init.d/indimail stop
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_sysconfdir}/init.d/indimail stop
       fi
-      /bin/grep "^SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
+      /bin/grep "^SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
       if [ $? -eq 0 ] ; then
-        %{__sed} -i 's{^SV:{#SV:{' /etc/inittab
+        %{__sed} -i 's{^SV:{#SV:{' %{_sysconfdir}/inittab
         if [ $? -eq 0 ] ; then
           /sbin/init q
         fi
@@ -2364,20 +2366,20 @@ if [ $argv1 -eq 2 ] ; then # upgrade
   elif [ -x /bin/systemctl -a -d /usr/lib/systemd/system ] ; then
     cmp -s %{shareddir}/boot/systemd /usr/lib/systemd/system/svscan.service >/dev/null 2>&1
     %{__cp} %{shareddir}/boot/systemd /usr/lib/systemd/system/svscan.service
-  elif [ -f /sbin/initctl -a -d /etc/init ] ; then
-    cmp -s %{shareddir}/boot/upstart /etc/init/svscan.conf >/dev/null 2>&1
-    %{__cp} %{shareddir}/boot/upstart /etc/init/svscan.conf
-  elif [ -d /etc/event.d ] ; then
-    cmp -s %{shareddir}/boot/upstart /etc/event.d/upstart >/dev/null 2>&1
-    %{__cp} %{shareddir}/boot/upstart /etc/event.d
+  elif [ -f /sbin/initctl -a -d %{_sysconfdir}/init ] ; then
+    cmp -s %{shareddir}/boot/upstart %{_sysconfdir}/init/svscan.conf >/dev/null 2>&1
+    %{__cp} %{shareddir}/boot/upstart %{_sysconfdir}/init/svscan.conf
+  elif [ -d %{_sysconfdir}/event.d ] ; then
+    cmp -s %{shareddir}/boot/upstart %{_sysconfdir}/event.d/upstart >/dev/null 2>&1
+    %{__cp} %{shareddir}/boot/upstart %{_sysconfdir}/event.d
   elif [ -d /System/Library/LaunchDaemons ] ; then
     cmp -s %{shareddir}/boot/indimail.plist /System/Library/LaunchDaemons >/dev/null 2>&1
     %{__cp} %{shareddir}/boot/indimail.plist /System/Library/LaunchDaemons
   fi
-  if [ -f /etc/inittab ] ; then # one of these days, this will disappear
-    /bin/grep "^#SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null 2>&1
+  if [ -f %{_sysconfdir}/inittab ] ; then # one of these days, this will disappear
+    /bin/grep "^#SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null 2>&1
     if [ $? -eq 0 ] ; then
-      %{__sed} -i 's{^#SV:{SV:{' /etc/inittab
+      %{__sed} -i 's{^#SV:{SV:{' %{_sysconfdir}/inittab
     fi
   fi
   ) >> /tmp/%{name}-setup.log 2>&1
@@ -2427,19 +2429,19 @@ if [ -f %{_prefix}/bin/svok ] ; then
       /bin/systemctl stop svscan > /dev/null 2>&1
     elif test -x %{_prefix}/sbin/initsvc
     then
-      if [ -x /etc/init.d/indimail ] ; then
-        %{_prefix}/sbin/initsvc -status || /etc/init.d/indimail stop || true
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_prefix}/sbin/initsvc -status || %{_sysconfdir}/init.d/indimail stop || true
       else
         %{_prefix}/sbin/initsvc -status || true
       fi
       %{_prefix}/sbin/initsvc -off || true
     else
-      if [ -x /etc/init.d/indimail ] ; then
-        /etc/init.d/indimail stop
+      if [ -x %{_sysconfdir}/init.d/indimail ] ; then
+        %{_sysconfdir}/init.d/indimail stop
       fi
-      /bin/grep "^SV:" /etc/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
+      /bin/grep "^SV:" %{_sysconfdir}/inittab |/bin/grep svscan |/bin/grep respawn >/dev/null
       if [ $? -eq 0 ] ; then
-        %{__sed} -i 's{^SV:{#SV:{' /etc/inittab
+        %{__sed} -i 's{^SV:{#SV:{' %{_sysconfdir}/inittab
         if [ $? -eq 0 ] ; then
           /sbin/init q
         fi
@@ -2576,9 +2578,9 @@ if [ -n $alternatives_cmd ] ; then
       %{__mv} /usr/share/man/man1/$i.1.gz /usr/share/man/man1/$i.old.1.gz
     fi
   done
-  if [ -f /etc/pam.d/smtp -a ! -L /etc/pam.d/smtp ] ; then
-    echo "! /etc/pam.d/smtp is a file, should be a link" 1>&2
-    %{__mv} /etc/pam.d/smtp /etc/pam.d/smtp.old
+  if [ -f %{_sysconfdir}/pam.d/smtp -a ! -L %{_sysconfdir}/pam.d/smtp ] ; then
+    echo "! %{_sysconfdir}/pam.d/smtp is a file, should be a link" 1>&2
+    %{__mv} %{_sysconfdir}/pam.d/smtp %{_sysconfdir}/pam.d/smtp.old
   fi
   $alternatives_cmd --install \
     /usr/sbin/sendmail mta %{_prefix}/bin/sendmail 120 \
@@ -2601,10 +2603,10 @@ else
       /bin/ln -s %{_prefix}/bin/sendmail $i
     fi
   done
-  if [ -f /etc/pam.d/smtp -a ! -L /etc/pam.d/smtp ] ; then
-    echo "! /etc/pam.d/smtp is a file, should be a link" 1>&2
-    %{__mv} /etc/pam.d/smtp /etc/pam.d/smtp.old
-    /bin/ln -s /etc/pam.d/pam.multi /etc/pam.d/smtp
+  if [ -f %{_sysconfdir}/pam.d/smtp -a ! -L %{_sysconfdir}/pam.d/smtp ] ; then
+    echo "! %{_sysconfdir}/pam.d/smtp is a file, should be a link" 1>&2
+    %{__mv} %{_sysconfdir}/pam.d/smtp %{_sysconfdir}/pam.d/smtp.old
+    /bin/ln -s %{_sysconfdir}/pam.d/pam.multi %{_sysconfdir}/pam.d/smtp
   fi
   for i in mailq newaliases; do
     if [ -f /usr/share/man/man1/$i.1.gz -a ! -L /usr/share/man/man1/$i.1.gz ] ; then
@@ -2641,7 +2643,7 @@ fi
 if [ -n $alternatives_cmd ] ; then
   $alternatives_cmd --remove mta %{_prefix}/bin/sendmail
   $alternatives_cmd --auto mta
-  for i in /usr/lib/sendmail /usr/sbin/sendmail /etc/pam.d/smtp; do
+  for i in /usr/lib/sendmail /usr/sbin/sendmail %{_sysconfdir}/pam.d/smtp; do
     if [ -f $i.old -o -L $i.old ]; then
       echo "restoring $i"
       %{__rm} -f $i
@@ -2657,7 +2659,7 @@ else
     fi
   fi
 fi
-for i in /usr/lib/sendmail /usr/sbin/sendmail /etc/pam.d/smtp; do
+for i in /usr/lib/sendmail /usr/sbin/sendmail %{_sysconfdir}/pam.d/smtp; do
   if [ -f $i.old -o -L $i.old ]; then
     echo "restoring $i"
     %{__rm} -f $i
