added command line option to set verbose rpmbuild

diff --git a/indimail-mta-x/create_rpm b/indimail-mta-x/create_rpm
--- a/indimail-mta-x/create_rpm
+++ b/indimail-mta-x/create_rpm
@@ -1,5 +1,8 @@
 #!/bin/sh
 # $Log: create_rpm,v $
+# Revision 1.9  2020-07-05 14:14:34+05:30  Cprogrammer
+# added command line option to set verbose rpmbuild
+#
 # Revision 1.8  2020-07-04 23:57:51+05:30  Cprogrammer
 # do silent rpm builds
 #
@@ -25,7 +28,7 @@
 # Initial revision
 #
 #
-# $Id: create_rpm,v 1.8 2020-07-04 23:57:51+05:30 Cprogrammer Exp mbhangui $
+# $Id: create_rpm,v 1.9 2020-07-05 14:14:34+05:30 Cprogrammer Exp mbhangui $
 #
 version=$(head -1 conf-version)
 libdkim_version=$(cat ../libdkim-x/conf-version)
@@ -71,6 +74,34 @@ get_dirname()
 		-e 's}.tar.bz2}}g' \
 		-e 's}.tar.xz}}g'
 }
+
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
 
 if test -f $HOME/.rpmmacros
 then
@@ -247,29 +278,36 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 	else
 		cp indimail-mta-x/indimail-mta.spec /tmp
 	fi
-	echo "rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec"
-	rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec"
+		rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/indimail-mta.spec"
+		rpmbuild -ba --clean /tmp/indimail-mta.spec
+	fi
 	/bin/rm -f /tmp/indimail-mta.spec
 	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	for i in indimail-mta indimail-mini daemontools ucspi-tcp
-	do
-		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
-	done
-	rpm --addsign $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
-	echo -n "RPM lint for indimail-mta-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
+	if [ $? -eq 0 ] ; then
 		for i in indimail-mta indimail-mini daemontools ucspi-tcp
 		do
-			echo $i
-			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
-			echo ------------------------
+			rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
 		done
-		echo indimail-mta-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+		rpm --addsign $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
+		echo -n "RPM lint for indimail-mta-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			for i in indimail-mta indimail-mini daemontools ucspi-tcp
+			do
+				echo $i
+				rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
+				echo ------------------------
+			done
+			echo indimail-mta-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
 	fi
 fi
 if [ $copy_src -eq 1 ] ; then
