attempt to stop oracle before MySQL configuration

diff --git a/indimail-mta-x/create_services.in b/indimail-mta-x/create_services.in
--- a/indimail-mta-x/create_services.in
+++ b/indimail-mta-x/create_services.in
@@ -23,7 +23,7 @@ cp=$(which cp)
 # End USER Configuration OPTIONS
 #
 
-# $Id: create_services.in,v 2.89 2020-10-04 11:47:27+05:30 Cprogrammer Exp mbhangui $
+# $Id: create_services.in,v 2.90 2020-10-07 16:51:10+05:30 Cprogrammer Exp mbhangui $
 
 usage()
 {
@@ -284,6 +284,43 @@ $svctool --config=users $extra_opt
 # MySQL
 #
 if [ $noindimail -eq 0 -a $nomysql -eq 0 ] ; then
+  echo "Attempting to Stop & Disable MySQL service"
+  if [ -f /usr/local/etc/rc.d/mysql-server ] ; then
+    /usr/local/etc/rc.d/mysql-server stop
+    service mysql disable
+  elif [ -f /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist ] ; then
+    launchctl unload -w /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist 2>/dev/null
+    launchctl remove /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist
+  elif [ -f /lib/systemd/system/mysqld.service ] ; then
+    systemctl stop mysqld.service
+    systemctl disable mysqld.service
+  elif [ -f /lib/systemd/system/mariadb.service ] ; then
+    systemctl stop mariadb.service
+    systemctl disable mariadb.service
+  elif [ -f /etc/init.d/mysqld ] ; then
+    /etc/init.d/mysqld stop
+    if [ -x /sbin/chkconfig ] ; then
+      chkconfig mysqld off
+    elif [ -x /sbin/update-rc.d ] ; then
+      update-rc.d -f mysqld disable
+    #else bhagwan bharose
+    fi
+  elif [ -f /etc/init.d/mysqld ] ; then
+    /etc/init.d/mysql stop
+    if [ -x /sbin/chkconfig ] ; then
+      chkconfig mysql off
+    elif [ -x /sbin/update-rc.d ] ; then
+      update-rc.d -f mysql disable
+    #else bhagwan bharose
+    fi
+  else
+    echo "Couldn't automatically stop mysqld process" 1>&2
+  fi
+  ps_list=`ps -ax|grep mysqld|grep -v grep`
+  if [ -n "$count" ] ; then
+    echo "mysqld process is running. Please stop before resuming this script" 1>&2
+    exit 0
+  fi
   $svctool --config=mysql   --mysqlPrefix=$mysql_base \
       --databasedir=$indimaildir/mysqldb $extra_opt
   $svctool --config=mysqldb --mysqlPrefix=$mysql_base \
