added ability to create split arch linux packages

diff --git a/indimail-mta-x/PKGBUILD.in b/indimail-mta-x/PKGBUILD.in
--- a/indimail-mta-x/PKGBUILD.in
+++ b/indimail-mta-x/PKGBUILD.in
@@ -1,8 +1,8 @@
 # Maintainer: @email@
-pkgname=indimail-mta
+pkgname=('indimail-mta' 'indimail-mini')
 pkgver=@version@
 pkgrel=@release@
-pkgdesc="MTA for IndiMail virtualdoamins"
+pkgdesc="MTA for IndiMail virtualdomains"
 arch=('i686' 'x86_64')
 url="https://github.com/mbhangui/indimail-mta"
 license=('GPL3')
@@ -13,15 +13,11 @@ source=("$pkgname-${pkgver}.tar.gz")
 sha256sums=('SKIP')
 _sysconfdir=@sysconfdir@
 _myconfdir=$(echo ${_sysconfdir} | cut -c2-)
-backup=(${_myconfdir}/{'controlfiles.q','cronlist.q'}
-        ${_myconfdir}/{'leapsecs.dat','leapsecs.txt','foxhole_all.cdb'}
-        ${_myconfdir}/control/{'nodnscheck','level2-tlds','level3-tlds'}
-        ${_myconfdir}/tcp/{'tcp.smtp','tcp.qmtp','tcp.qmqp')
 provides=('indimail-mta')
 options=('strip' '!libtool' 'docs' 'staticlibs' 'zipman' 'debug')
-install=archpkg.install
 changelog=$pkgname.changes
 _prefix=@prefix@
+_libdir=@prefix@/lib
 _servicedir=@servicedir@
 _qmaildir=@qmaildir@
 _libexecdir=@libexecdir@
@@ -97,8 +93,13 @@ build() {
   ./qmake -s
 }
 
-package() {
-  depends=('shadow' 'daemontools>=1.0' 'ucspi-tcp>=1.0')
+package_indimail-mta() {
+  backup=(${_myconfdir}/{'controlfiles.q','cronlist.q','defaultdomain'}
+        ${_myconfdir}/{'leapsecs.dat','leapsecs.txt','foxhole_all.cdb'}
+        ${_myconfdir}/control/{'nodnscheck','level2-tlds','level3-tlds'}
+        ${_myconfdir}/tcp/{'tcp.smtp','tcp.qmtp','tcp.qmqp')
+  depends=('shadow' 'coreutils' 'openssl' 'libidn2' 'mariadb-libs' 'libqmail' 'libdkim' 'libsrs2' 'libldap' 'daemontools>=1.0' 'ucspi-tcp>=1.0')
+  install=archpkg1.install
   cd $srcdir/$pkgname-${pkgver}
   sed -i 's|/sbin/|/bin/|g' SBIN.in
   sed -i 's|/sbin/|/bin/|g' SBIN.sql
@@ -124,7 +125,66 @@ package() {
   ) > ${pkgname}-release
   install -D -m 0644 ${pkgname}-release "$pkgdir"${_sysconfdir}/${pkgname}-release
 }
-#### INSTALL SCRIPTS ####
+
+package_indimail-mini() {
+  backup=(${_myconfdir}/{'idhost'})
+  pkgdesc="Mini MTA for IndiMail virtualdomains"
+  depends=('shadow' 'coreutils' 'libqmail' 'daemontools>=1.0' 'ucspi-tcp>=1.0')
+  install=archpkg2.install
+  cd $srcdir/indimail-mta-${pkgver}
+  (
+  echo "d:::0755:::"
+  echo "d:::0555:@shareddir@::"
+  echo "d:::0555:@shareddir@/doc::"
+  echo "d::::@mandir@::"
+  echo "d::::@mandir@/man1::"
+  echo "d::::@mandir@/man5::"
+  echo "d::::@mandir@/man8::"
+  echo "d::::@prefix@/bin::"
+  ) > DIRS
+  (
+  echo "f:::0755:/bin/:sendmail:sendmail"
+  echo "f:::0755:/bin/:qmail-inject:qmail-inject"
+  echo "f:::0755:/bin/:qmail-inject:qmail-inject"
+  echo "f:::0755:/bin/:irmail:irmail"
+  echo "f:::0755:/bin/:forward:forward"
+  echo "f:::0755:/bin/:predate:predate"
+  echo "f:::0755:/bin/:datemail:datemail"
+  echo "f:::0755:/bin/:mailsubj:mailsubj"
+  echo "f:::0755:/bin/:qmail-showctl:qmail-showctl"
+  echo "f:::0755:/bin/:qmaildirmake:qmaildirmake"
+  echo "f:::0755:/bin/:maildir2mbox:maildir2mbox"
+  echo "f:::0755:/bin/:maildirwatch:maildirwatch"
+  echo "f:::0755:/bin/:qmail-qmqpc:qmail-qmqpc"
+  ) > BIN
+  (
+  echo "f:::0644:/man1/:forward.1:forward.1"
+  echo "f:::0644:/man1/:predate.1:predate.1"
+  echo "f:::0644:/man1/:datemail.1:datemail.1"
+  echo "f:::0644:/man1/:mailsubj.1:mailsubj.1"
+  echo "f:::0644:/man1/:qmaildirmake.1:qmaildirmake.1"
+  echo "f:::0644:/man1/:maildir2mbox.1:maildir2mbox.1"
+  echo "f:::0644:/man1/:maildirwatch.1:maildirwatch.1"
+  echo "f:::0644:/man5/:qmail-srs.5:qmail-srs.5"
+  echo "f:::0644:/man8/:qmail-showctl.8:qmail-showctl.8"
+  echo "f:::0644:/man8/:qmail-inject.8:qmail-inject.8"
+  echo "f:::0644:/man8/:isendmail.8:isendmail.8"
+  echo "f:::0644:/man8/:qmail-qmqpc.8:qmail-qmqpc.8"
+  echo "f:::0644:/man8/:irmail.8:irmail.8"
+  ) > MAN
+  echo "f:::0644:/doc/:INSTALL-MINI:doc/INSTALL-MINI" > SHARED
+  > LIBEXEC
+  > ETC
+  > PLUGINS
+  > SBIN
+  ./qmake DESTDIR=${pkgdir} install
+  /bin/rm -rf ${pkgdir}/etc
+  /bin/rm -rf ${pkgdir}/var
+  /bin/rm -rf "${pkgdir}"${_libdir}
+  /bin/rm -rf "${pkgdir}"${_libexecdir}
+}
+
+#### INSTALL1 SCRIPTS ####
 pkgname=indimail-mta
 _sysconfdir=@sysconfdir@
 _prefix=@prefix@
@@ -683,3 +743,173 @@ post_remove() {
   fi
   ) >> /var/log/${pkgname}-setup.log 2>&1
 }
+#### END ####
+#### INSTALL2 SCRIPTS ####
+_prefix=@prefix@
+_servicedir=@servicedir@
+_qmaildir=@qmaildir@
+_sysconfdir=@sysconfdir@
+_mandir=@mandir@
+_uid=555
+_gid=555
+post_upgrade() {
+  (
+  #
+  # Create user/groups indimail. Do not report any problems if it already
+  # exists.
+  #
+  nscd_up=`ps -ef |grep nscd |grep -v grep|wc -l`
+  if [ $nscd_up -ge 1 ] ; then
+    if [ -x ${confdir}/init.d/nscd ] ; then
+      ${confdir}/init.d/nscd stop
+    elif [ -f ${confdir}/lib/systemd/system/multi-user.target/nscd.service ] ; then
+      /bin/systemctl start nscd.service
+    fi
+  fi
+  echo "Adding IndiMail users/groups"
+  /usr/bin/getent group indimail  > /dev/null || /usr/sbin/groupadd -r -g ${_gid} indimail || true
+  if [ $? = 4 ] ; then
+    /usr/sbin/groupadd indimail
+  fi
+  /usr/bin/getent group nofiles   > /dev/null || /usr/sbin/groupadd nofiles  || true
+  /usr/bin/getent group qmail     > /dev/null || /usr/sbin/groupadd qmail    || true
+
+  rm -f /var/spool/mail/indimail
+
+  /usr/bin/getent passwd indimail > /dev/null || /usr/sbin/useradd -r -g indimail -u ${_uid} -d ${_qmaildir} indimail || true
+  if [ $? = 4 ] ; then
+    /usr/sbin/useradd -r -g indimail -d ${_qmaildir} indimail
+  fi
+  if [ $nscd_up -ge 1 ] ; then
+    if [ -x ${confdir}/init.d/nscd ] ; then
+      ${confdir}/init.d/nscd start
+    elif [ -f ${confdir}/lib/systemd/system/multi-user.target/nscd.service ] ; then
+      /bin/systemctl start nscd.service
+    fi
+  fi
+
+  if [ -f ${_prefix}/bin/qmail-qmqpc ] ; then
+    mv ${_prefix}/bin/qmail-queue ${_prefix}/sbin/qmail-queue.orig
+  fi
+  cd ${_prefix}/bin
+  /bin/ln -sf qmail-qmqpc qmail-queue
+  if [ -f ${confdir}/init.d/sendmail ] ; then
+    ${confdir}/init.d/sendmail stop
+    if [ -f /sbin/chkconfig ] ; then
+      /sbin/chkconfig --del sendmail
+    fi
+  fi
+  if [ -x /usr/sbin/alternatives ] ; then
+    alternatives_cmd=/usr/sbin/alternatives
+  elif [ -x /usr/sbin/update-alternatives ] ; then
+    alternatives_cmd=/usr/sbin/update-alternatives
+  else
+    alternatives_cmd=""
+  fi
+  if [ -n $alternatives_cmd ] ; then
+    for i in /usr/lib/sendmail /usr/sbin/sendmail; do
+      if [ -f $i -a ! -L $i ]; then
+        echo "! $i is a file, should be a link" 1>&2
+        mv $i $i.old
+      fi
+    done
+    for i in mailq newaliases; do
+      if [ -f /usr/share/man/man1/$i.1.gz -a ! -L /usr/share/man/man1/$i.1.gz ] ; then
+        echo "! /usr/share/man/man1/$i.1.gz is a file, should be a link" 1>&2
+        mv /usr/share/man/man1/$i.1.gz /usr/share/man/man1/$i.old.1.gz
+      fi
+    done
+    if [ -f ${confdir}/pam.d/smtp -a ! -L ${confdir}/pam.d/smtp ] ; then
+      echo "! ${confdir}/pam.d/smtp is a file, should be a link" 1>&2
+      mv ${confdir}/pam.d/smtp ${confdir}/pam.d/smtp.old
+    fi
+    $alternatives_cmd --install \
+      /usr/sbin/sendmail mta ${_prefix}/bin/sendmail 120 \
+      --slave /usr/share/man/man8/sendmail.8.gz mta-sendmailman \
+        ${_mandir}/man8/isendmail.8.gz \
+      --slave /usr/lib/sendmail mta-sendmail ${_prefix}/bin/sendmail \
+      --slave /usr/bin/rmail mta-rmail ${_prefix}/bin/irmail
+    $alternatives_cmd --set mta ${_prefix}/bin/sendmail
+  else
+    for i in /usr/lib/sendmail /usr/sbin/sendmail; do
+      if [ -f $i -a ! -L $i ]; then
+        echo "! $i is a file, should be a link" 1>&2
+        mv $i $i.old
+        /bin/ln -s ${_prefix}/bin/sendmail $i
+      elif [ -L $i ];then
+        mv $i $i.old
+        /bin/ln -s ${_prefix}/bin/sendmail $i
+      elif [ ! -f $i ];then
+        echo "! $i is missing"
+        /bin/ln -s ${_prefix}/bin/sendmail $i
+      fi
+    done
+    if [ -f ${confdir}/pam.d/smtp -a ! -L ${confdir}/pam.d/smtp ] ; then
+      echo "! ${confdir}/pam.d/smtp is a file, should be a link" 1>&2
+      mv ${confdir}/pam.d/smtp ${confdir}/pam.d/smtp.old
+      /bin/ln -s ${confdir}/pam.d/pam.multi ${confdir}/pam.d/smtp
+    fi
+    for i in mailq newaliases; do
+      if [ -f /usr/share/man/man1/$i.1.gz -a ! -L /usr/share/man/man1/$i.1.gz ] ; then
+        echo "! /usr/share/man/man1/$i.1.gz is a file, should be a link" 1>&2
+        mv /usr/share/man/man1/$i.1.gz /usr/share/man/man1/$i.old.1.gz
+      fi
+    done
+  fi
+
+  # a copy of following control files from your central server
+  # /var/indimail/control/me
+  # /var/indimail/control/defaultdomain,
+  # /var/indimail/control/plusdomain
+  # so that qmail-inject uses appropriate host names in outgoing mail; and
+  # this host's name in /var/indimail/control/idhost, so that qmail-inject
+  # generates Message-ID without any risk of collision
+  if [ ! -f ${_sysconfdir}/control/idhost ] ; then
+    default_domain=$([ -n "$HOSTNAME" ] && echo "$HOSTNAME" || `uname -n`)
+    echo $default_domain > ${_sysconfdir}/control/idhost
+  fi
+  ) >> /var/log/${pkgname}-setup.log
+}
+
+post_remove() {
+  (
+  if [ -x /usr/sbin/alternatives ] ; then
+    alternatives_cmd=/usr/sbin/alternatives
+  elif [ -x /usr/sbin/update-alternatives ] ; then
+    alternatives_cmd=/usr/sbin/update-alternatives
+  else
+    alternatives_cmd=""
+  fi
+  if [ -n $alternatives_cmd ] ; then
+    $alternatives_cmd --remove mta ${_prefix}/bin/sendmail
+    $alternatives_cmd --auto mta
+    for i in /usr/lib/sendmail /usr/sbin/sendmail ${confdir}/pam.d/smtp; do
+      if [ -f $i.old -o -L $i.old ]; then
+        echo "restoring $i"
+        mv $i.old $i
+      fi
+    done
+  else
+    if [ -f ${confdir}/init.d/sendmail ] ; then
+      if [ -f /sbin/chkconfig ] ; then
+        /sbin/chkconfig --add sendmail
+        echo "to start sendmail, issue"
+        echo "${confdir}/init.d/sendmail start"
+      fi
+    fi
+  fi
+  for i in /usr/lib/sendmail /usr/sbin/sendmail ${confdir}/pam.d/smtp; do
+    if [ -f $i.old -o -L $i.old ]; then
+      echo "restoring $i"
+        mv $i.old $i
+    fi
+  done
+  for i in mailq newaliases; do
+    if [ -f /usr/share/man/man1/$i.old.1.gz ] ; then
+      echo "restoring /usr/share/man/man1/$i.1.gz"
+      mv /usr/share/man/man1/$i.old.1.gz /usr/share/man/man1/$i.1.gz
+    fi
+  done
+  ) >> /var/log/${pkgname}-setup.log
+}
+#### END ####
