common instcheck for daemontools, ucspi-tcp, indimail-mta

diff --git a/daemontools-x/instcheck.in b/daemontools-x/instcheck.in
--- a/daemontools-x/instcheck.in
+++ b/daemontools-x/instcheck.in
@@ -1,10 +1,13 @@
 #
 # $Log: instcheck.in,v $
+# Revision 1.2  2022-07-01 18:30:28+05:30  Cprogrammer
+# common instcheck for daemontools, ucspi-tcp, indimail-mta
+#
 # Revision 1.1  2021-08-03 21:22:32+05:30  Cprogrammer
 # Initial revision
 #
 #
-# $Id: instcheck.in,v 1.1 2021-08-03 21:22:32+05:30 Cprogrammer Exp mbhangui $
+# $Id: instcheck.in,v 1.2 2022-07-01 18:30:28+05:30 Cprogrammer Exp mbhangui $
 #
 if [ $# -eq 0 ] ; then
 	name=$(basename $0)
@@ -30,7 +33,7 @@ else
 	dir=@libexecdir@
 	conf_dir=@qsysconfdir@
 	if [ ! -d $conf_dir/perms.d/$package ] ; then
-		echo "$package: missing permission files" 1>&2
+		echo "$package: missing permission files dir [$conf_dir/perms.d/$package]" 1>&2
 		exit 111
 	else
 		cd $conf_dir/perms.d/$package
@@ -43,12 +46,24 @@ else
 		exit 111
 	fi
 fi
+if [ -x $dir/uinstaller ] ; then
+	installer=$dir/uinstaller #ucspi-tcp
+else
+	installer=$dir/installer
+fi
 status=0
 set -e
 while read line
 do
 	set $line
-	eval $dir/installer $opt $DESTDIR"$1" < $2
+	if [ "$1" = "/" ] ; then
+		x=""
+	else
+		x="$1"
+	fi
+	input=$2
+	echo $installer $opt $DESTDIR"$x" < $input
+	eval $installer $opt $DESTDIR"$x" < $input
 	if [ $? -ne 0 ] ; then
 		break
 	fi
