added --print-all-variables option in svctool, minisvc

diff --git a/daemontools-x/minisvc.in b/daemontools-x/minisvc.in
--- a/daemontools-x/minisvc.in
+++ b/daemontools-x/minisvc.in
@@ -1,5 +1,5 @@
 #
-# $Id: minisvc.in,v 1.20 2021-07-07 19:25:55+05:30 Cprogrammer Exp mbhangui $
+# $Id: minisvc.in,v 1.21 2021-07-16 18:50:05+05:30 Cprogrammer Exp mbhangui $
 #
 
 #
@@ -10,7 +10,7 @@ sysconfdir=@sysconfdir@
 shareddir=@shareddir@
 LOGDIR=@logdir@
 host=@HOST@
-RCSID="# \$Id: minisvc.in,v 1.20 2021-07-07 19:25:55+05:30 Cprogrammer Exp mbhangui $"
+RCSID="# \$Id: minisvc.in,v 1.21 2021-07-16 18:50:05+05:30 Cprogrammer Exp mbhangui $"
 
 #
 # End of User Configuration
@@ -177,11 +177,19 @@ Known values for OPTION are:
 
 --print-variables
   --servicedir=service_path
-  --service-name=service_name
+  --service-name=service_name | --envdir=dir
 
+  Print environment variables for a service
   service_path   - Path where supervise service will be installed
   service_name   - name of supervise service without path
                    e.g. (qmail-smtpd.25)
+  dir            - Environment variables directory
+
+--print-all-variables
+  --servicedir=service_path
+
+  Print environment variables all services
+  service_path   - Path where supervise service will be installed
 
 --dumpconfig --servicedir=service_path --cntrldir=cntrl_path
 
@@ -1144,10 +1152,21 @@ elif [ -x /usr/bin/chown ] ; then
 else
 	chown=/bin/chown
 fi
+if [ $(id -u) -ne 0 ] ; then
+	echo "minisvc is not meant to be run by mere mortals. Use sudo to get superpowers"
+	exit 100
+fi
 
 if [ -f @sysconfdir@/svctool.cnf ] ; then
-	$chown root:0 @sysconfdir@/svctool.cnf
-	/bin/chmod 400 @sysconfdir@/svctool.cnf
+	perms=$(stat -c "%u:%g:%a" $sysconfdir/svctool.cnf)
+	if [ $? -ne 0 ] ; then
+		exit 100
+	fi
+	if [ ! $perms = "0:0:400" ] ; then
+		echo "fixing permissions of svctool.cnf"
+		$chown root:0 @sysconfdir@/svctool.cnf
+		/bin/chmod 400 @sysconfdir@/svctool.cnf
+	fi
 	. @sysconfdir@/svctool.cnf
 fi
 [ -z "$TMPDIR" ] && TMPDIR="/tmp/minisvc"
@@ -1306,6 +1325,9 @@ while test $# -gt 0; do
 	--service-name=*)
 	service_name=$optarg
 	;;
+	--envdir=*)
+	envdir=$optarg
+	;;
 	--variable-value=*)
 	variable_value=$optarg
 	;;
@@ -1347,6 +1369,9 @@ while test $# -gt 0; do
 	;;
 	--print-variables)
 	option=17
+	;;
+	--print-all-variables)
+	option=18
 	;;
 
 	--version)
@@ -1632,20 +1657,133 @@ case $option in
 		echo "Supervise Directory not specified" 1>&2
 		usage 1
 	fi
-	if [ -z "$service_name" ] ; then
-		echo "service name not specified" 1>&2
+	if [ -n "$service_name" -a -n "$envdir" ] ; then
+		echo "you cannot specify both service name and envdir both" 1>&2
+		exit 1
+	fi
+	if [ -z "$service_name" -a -z "$envdir" ] ; then
+		echo "service name or envdir has to be specified" 1>&2
 		usage 1
 	fi
-	if [ ! -d $servicedir/$service_name ] ; then
+	if [ -n "$service_name" -a ! -d $servicedir/$service_name ] ; then
 		echo "$servicedir/$service_name: No such file or directory" 1>&2
 		exit 1
 	fi
-	if [ ! -d $servicedir/$service_name/variables ] ; then
-		echo "$servicedir/$service_name: This service has no configured variables" 1>&2
+	if [ -n "$envdir" -a ! -d "$envdir" ] ; then
+		echo "$envdir: No such directory" 1>&2
 		exit 1
 	fi
-	echo "------ environment variables for $servicedir/$service_name ------------"
-	envdir -c $servicedir/$service_name/variables env
+	if [ -n "$service_name" ] ; then
+		i=$servicedir/$service_name/variables
+	elif [ -n "$envdir" ] ; then
+		i=$envdir
+	fi
+	if [ ! -d $i ] ; then
+		(
+		echo "------ $servicedir/$service_name ------------" 
+		echo "NOTE: This service has no configured variables"
+		) 1>&2
+		exit 1
+	fi
+	if [ -L $i/.envdir -o -f $i/.envdir -o -f $i/.envfile ] ; then
+		if [ -n "$service_name" ] ; then
+			echo "------ $servicedir/$service_name ------------"
+		elif [ -n "$envdir" ] ; then
+			echo "------ $envdir ------------"
+		fi
+	fi
+	if [ -L $i/.envdir ] ; then
+		link_name=$(readlink $i/.envdir)
+		echo "NOTE: additional variables were obtained from $link_name"
+		echo
+	elif [ -f $i/.envdir ] ; then
+		echo "NOTE: additional variables were obtained from .envdir"
+		cat $i/.envdir
+		echo
+	fi
+	if [ -f $i/.envfile ] ; then
+		echo "NOTE: additional variables were obtained from .envfile"
+		cat $i/.envfile
+		echo
+	fi
+	if [ -n "$service_name" ] ; then
+		echo "------ environment variables for $servicedir/$service_name ------------"
+	elif [ -n "$envdir" ] ; then
+		echo "------ environment variables for $envdir ------------"
+	fi
+	envdir -c $i env
+	;;
+
+	18)
+	if [ -z "$servicedir" ] ; then
+		echo "Supervise Directory not specified" 1>&2
+		usage 1
+	fi
+	for i in $servicedir/*
+	do
+		if [ -d $i/variables ] ; then
+			vars=$(envdir -c $i/variables env 2>/dev/null)
+			if [ -n "$vars" ] ; then
+				if [ -L $i/variables/.envdir -o -f $i/variables/.envdir -o -f $i/variables/.envfile ] ; then
+					echo "------ $i ------------"
+				fi
+				if [ -L $i/variables/.envdir ] ; then
+					link_name=$(readlink $i/variables/.envdir)
+					echo "NOTE: additional variables were obtained from $link_name"
+					echo
+				elif [ -f $i/variables/.envdir ] ; then
+					echo "NOTE: additional variables were obtained from .envdir"
+					cat $i/variables/.envdir
+					echo
+				fi
+				if [ -f $i/variables/.envfile ] ; then
+					echo "NOTE: additional variables were obtained from .envfile"
+					cat $i/variables/.envfile
+					echo
+				fi
+				echo "------ environment variables for $i ------------"
+				envdir -c $i/variables env
+				echo
+			else
+				echo "------ $i ------------"
+				echo "NOTE: This service has no configured variables"
+				echo
+			fi
+		fi
+	done
+	for i in $sysconfdir/control/defaultqueue $sysconfdir/control/global_vars \
+		$sysconfdir/ezmlm/global_vars
+	do
+		if [ -d $i ] ; then
+			vars=$(envdir -c $i env 2>/dev/null)
+			if [ -n "$vars" ] ; then
+				if [ -L $i/.envdir -o -f $i/.envdir -o -f $i/.envfile ] ; then
+					echo "------ $i ------------"
+				fi
+				if [ -L $i/.envdir ] ; then
+					link_name=$(readlink $i/.envdir)
+					echo "NOTE: additional variables were obtained from $link_name"
+					echo
+				elif [ -f $i/.envdir ] ; then
+					echo "NOTE: additional variables were obtained from .envdir"
+					cat $i/.envdir
+					echo
+				fi
+				if [ -f $i/.envfile ] ; then
+					echo "NOTE: additional variables were obtained from .envfile"
+					cat $i/.envfile
+					echo
+				fi
+				echo "------ environment variables for $i ------------"
+				envdir -c $i env
+				echo
+			else
+				echo "------ $i ------------"
+				echo "NOTE: This directory has no configured variables"
+				echo
+			fi
+		fi
+	done
 	;;
 
 	*)
@@ -1669,6 +1807,9 @@ fi
 exit 0
 #
 # $Log: minisvc.in,v $
+# Revision 1.21  2021-07-16 18:50:05+05:30  Cprogrammer
+# added --print-all-variables option
+#
 # Revision 1.20  2021-07-07 19:25:55+05:30  Cprogrammer
 # added --print-variables option
 #
