send output through pager

diff --git a/daemontools-x/svps.in b/daemontools-x/svps.in
--- a/daemontools-x/svps.in
+++ b/daemontools-x/svps.in
@@ -1,4 +1,7 @@
 # $Log: svps.in,v $
+# Revision 1.4  2020-11-11 18:01:37+05:30  Cprogrammer
+# send output through pager
+#
 # Revision 1.3  2020-11-10 19:14:47+05:30  Cprogrammer
 # display supervise process pid when service is down
 #
@@ -9,61 +12,15 @@
 # Initial revision
 #
 # 
-# $Id: svps.in,v 1.3 2020-11-10 19:14:47+05:30 Cprogrammer Exp mbhangui $
+# $Id: svps.in,v 1.4 2020-11-11 18:01:37+05:30 Cprogrammer Exp mbhangui $
 #
-option=main
-while test $# -gt 0; do
-    case "$1" in
-    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
-	;;
-    *) optarg=
-	;;
-    esac
 
-    case "$1" in
-    -a|--all)
-	option=all
-    ;;
-    -m|--main)
-	option=main
-    ;;
-    -l|--logs)
-	option=logs
-    ;;
-    *)
-    echo "invalid option [$1]" 1>&2
-	echo "svps [--all | --main | --logs]" 1>&2
-    read key
-	exit 1
-    ;;
-    esac
+doit()
+{
+option=$1
+max=$2
 
-    shift
-done
 ps ax|grep "svscan"|egrep -v "grep|multilog"
-@prefix@/bin/svstat @servicedir@/* @servicedir@/*/log @servicedir@/.svscan/log 2>/dev/null \
-	|egrep -v "\.\.|^wait until" > /tmp/svps.$$
-status=${PIPESTATUS[0]}
-if [ $status -ne 0 ] ; then
-	if [ ! -s /tmp/svps.$$ ] ; then
-		/bin/cat /tmp/svps.$$
-		/bin/rm -f /tmp/svps.$$
-		exit $status
-	fi
-fi
-
-max=0
-while read line
-do
-	if [ -z "$line" ] ; then
-		continue
-	fi
-	set $line
-	len=`echo $1 | cut -d: -f1|wc -c`
-	if [ $len -gt $max ] ; then
-		max=$len
-	fi
-done <<<$(cat /tmp/svps.$$)
 
 if [ "$option" = "all" -o "$option" = "main" ] ; then
 	echo
@@ -121,4 +78,71 @@ if [ "$option" = "all" -o "$option" = "logs" ] ; then
 		fi
 	done
 fi
+}
+
+option=main
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    -a|--all)
+	option=all
+    ;;
+    -m|--main)
+	option=main
+    ;;
+    -l|--logs)
+	option=logs
+    ;;
+    *)
+    echo "invalid option [$1]" 1>&2
+	echo "svps [--all | --main | --logs]" 1>&2
+    read key
+	exit 1
+    ;;
+    esac
+
+    shift
+done
+if [ -x /usr/bin/less ] ; then
+	PAGER=/usr/bin/less
+elif [ -x /usr/bin/more ] ; then
+	PAGER=/usr/bin/more
+fi
+
+@prefix@/bin/svstat @servicedir@/* @servicedir@/*/log @servicedir@/.svscan/log 2>/dev/null \
+	|egrep -v "\.\.|^wait until" > /tmp/svps.$$
+status=${PIPESTATUS[0]}
+if [ $status -ne 0 ] ; then
+	if [ ! -s /tmp/svps.$$ ] ; then
+		/bin/cat /tmp/svps.$$
+		/bin/rm -f /tmp/svps.$$
+		exit $status
+	fi
+fi
+
+max=0
+while read line
+do
+	if [ -z "$line" ] ; then
+		continue
+	fi
+	set $line
+	len=`echo $1 | cut -d: -f1|wc -c`
+	if [ $len -gt $max ] ; then
+		max=$len
+	fi
+done <<<$(cat /tmp/svps.$$)
+
+if [ -n "$PAGER" ] ; then
+	doit $option $max | $PAGER
+else
+	doit $option $max
+fi
+
 /bin/rm -f /tmp/svps.$$
