Updated supervise, svps
1. supervise.c: Removed extra sleep in do_init
2. svps.in: use /proc/pid/cwd to get service directory.

diff --git a/daemontools-x/svps.in b/daemontools-x/svps.in
--- a/daemontools-x/svps.in
+++ b/daemontools-x/svps.in
@@ -1,7 +1,8 @@
 # 
-# $Id: svps.in,v 1.23 2024-10-24 18:06:23+05:30 Cprogrammer Exp mbhangui $
+# $Id: svps.in,v 1.24 2026-01-09 18:12:44+05:30 Cprogrammer Exp mbhangui $
 #
 
+# sets time string (tstr)
 do_days()
 {
 	secs=$1
@@ -12,7 +13,7 @@ do_days()
 	fi
 }
 
-get_mod()
+get_mod_time()
 {
 	SYSTEM=$(uname -s)
 	case "$SYSTEM" in
@@ -35,21 +36,30 @@ do_svscan()
 	words=$(expr $words - 1)
 
 	t=$(expr $max - $svscan_length)
-	printf "============ %-"$t"s     state uptime ===== pid/spid ==\n" "svscan"
+	if [ $mday -eq 1 ] ; then
+		printf "============ %-"$t"s     state uptime =========================  pid/spid ==\n" "svscan"
+	else
+		printf "============ %-"$t"s     state uptime ====  pid/spid ==\n" "svscan"
+	fi
+	count=1
 	ps axu|grep root|grep "sbin/svscan"|grep -Ev "grep|multilog|supervise" | while read line
 	do
 		set $line
 		pid=$2
-		if [ -s ${12}/.svscan/variables/DISABLE_RUN ] ; then
-			t=$(cat /proc/$pid/cmdline |tr '\0' '\n'|tail -n +2)
-			get_mod $t/.svscan.pid
+		t=$(cat /proc/$pid/cmdline|tr '\0' '\n'|tail -n +2)
+		if [ -s $t/.svscan/variables/DISABLE_RUN ] ; then
+			get_mod_time $t/.svscan.pid
 		else
-			get_mod $pidfile
+			if [ -f $t/.svscan.pid ] ; then
+				get_mod_time $t/.svscan.pid
+			else
+				get_mod_time $pidfile
+			fi
 		fi
 		diff=$(expr $now - $mod)
 		do_days $diff
 		shift $words
-		printf "%-"$max"s up   %s  pid %7d\n" "$*" "$tstr" $pid
+		printf "%-"$max"s up   %s  pid %7d [%2d]\n" "$*" "$tstr" $pid $count
 	done
 }
 
@@ -63,7 +73,11 @@ doit()
 	case "$option" in
 		all|main)
 		echo
-		printf "============ %-"$t"s     state uptime ===== pid/spid ==\n" $svdir
+		if [ $mday -eq 1 ] ; then
+			printf "============ %-"$t"s     state uptime =========================  pid/spid ==\n" "svscan"
+		else
+			printf "============ %-"$t"s     state uptime ====  pid/spid ==\n" $svdir
+		fi
 
 		grep -w down /tmp/svps.$$ | grep -E -v "normally down|want down" | sort -n -k3 | grep -v "/log" | while read line
 		do
@@ -123,14 +137,14 @@ doit()
 		all|logs)
 		echo
 		printf "============ %-"$t"s     state uptime ===== pid/spid ==\n" ".svscan/log"
-		set $(grep "@servicedir@/\.svscan/log" /tmp/svps.$$)
+		set $(grep "$servicedir/\.svscan/log" /tmp/svps.$$)
 		name=`echo $1|cut -d: -f1`
 		secs=$3
 		do_days $secs
 		printf "%-"$max"s up   %s  pid %7d\n" $name "$tstr" $6
 		echo
 		printf "==== logs == %-"$t"s     state uptime ===== pid/spid ==\n" $svdir
-		grep -E "@servicedir@/.*/log" /tmp/svps.$$ | sort -n -k3 | grep -v "\.svscan" | while read line
+		grep -E "$servicedir/.*/log" /tmp/svps.$$ | sort -n -k3 | grep -v "\.svscan" | while read line
 		do
 			set $line
 			name=`echo $1|cut -d: -f1`
@@ -190,6 +204,38 @@ resume_all()
 	[ $flag -eq 0 ] && echo "No stopped services found" 1>&2
 }
 
+get_pidfile()
+{
+	pidfile=""
+	if [ -n "$servicedir" ] ; then
+		if [ ! -f $servicedir/.svscan.pid ] ; then
+			echo "$servicedir/.svscan.pid: No such file or directory" 1>&2
+			exit 1
+		fi
+		pidfile=$servicedir/.svscan.pid
+	fi
+	if [ -z "$pidfile" ] ; then
+		if [ -d /run/svscan ] ; then
+			pidfile=/run/svscan/.svscan.pid
+		elif [ -d /var/run/svscan ] ; then
+			pidfile=/var/run/svscan/.svscan.pid
+		else
+			pidfile=@servicedir@/.svscan.pid
+		fi
+	fi
+	if [ -f $pidfile ] ; then
+		svpid=$(sed -n '$p' $pidfile)
+	else
+		svpid=$(pgrep -fn @prefix@/sbin/svscan)
+		if [ -z "$svpid" ] ; then
+			echo "svscan not running: $pidfile: No such file or directory" 1>&2
+			exit 1
+		fi
+		t=$(cat /proc/$svpid/cmdline |tr '\0' '\n'|tail -n +2)
+		pidfile=$t/.svscan.pid
+	fi
+}
+
 if [ -z "$PAGER" ] ; then
 	if [ -x /usr/bin/less ] ; then
 		PAGER=/usr/bin/less
@@ -199,15 +245,22 @@ if [ -z "$PAGER" ] ; then
 fi
 option=main
 mday=0
+servicedir=""
+display_tree=0
 while test $# -gt 0; do
     case "$1" in
-    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+    -*=*)
+	optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
 	;;
-    *) optarg=
+    *)
+	optarg=
 	;;
     esac
 
     case "$1" in
+    --servicedir=*)
+	servicedir=$optarg
+    ;;
     -a|--all)
 	option=all
     ;;
@@ -216,6 +269,9 @@ while test $# -gt 0; do
 	;;
 	-t|--term)
 	option=term
+	;;
+	-T|--tree)
+	display_tree=1
 	;;
     -m|--main)
 	option=main
@@ -237,8 +293,9 @@ while test $# -gt 0; do
 	;;
     *)
     echo "invalid option [$1]" 1>&2
-	echo "usage: svps [-a|--all | -m|--main | -h|--hup | -t|--term | -n|--no-pager] |"
+	echo "usage: svps [-a|--all | -m|--main | -h|--hup | -t|--term | -n|--no-pager] |" 1>&2
 	echo "  [-d|--days -s|--stop | -r|--resume | -l|--logs]" 1>&2
+	echo "  [--servicedir | -T|--tree]" 1>&2
     read key
 	exit 1
     ;;
@@ -248,47 +305,48 @@ while test $# -gt 0; do
 done
 
 ID=$(id -u)
-
 if [ $ID -ne 0 ] ; then
   echo "You are not root" 1>&2
   exit 1
 fi
-if [ -d /run/svscan ] ; then
-	pidfile=/run/svscan/.svscan.pid
-	rundir=/run
-elif [ -d /var/run/svscan ] ; then
-	pidfile=/var/run/svscan/.svscan.pid
-	rundir=/var/run
-else
-	pidfile=@servicedir@/.svscan.pid
-	rundir=@servicedir@
-fi
-if [ -f $pidfile ] ; then
-	svpid=$(sed -n '$p' $pidfile)
-else
-	svpid=$(pgrep -fn @prefix@/sbin/svscan)
-	if [ -z "$svpid" ] ; then
-		echo "svscan not running: $pidfile: No such file or directory" 1>&2
-		exit 1
-	fi
-	t=$(cat /proc/$svpid/cmdline |tr '\0' '\n'|tail -n +2)
-	pidfile=$t/.svscan.pid
+
+get_pidfile
+kill -0 $svpid 2>/dev/null
+if [ $? -ne 0 ] ; then
+	echo "Couldn't find a running svscan process" 1>&2
+	exit 1
 fi
 
+# get process entries for svscan can calculate length svscan_length
 ps axu|grep root|grep "sbin/svscan"|grep -Ev "grep|multilog|supervise" > /tmp/svps.$$
 max=0
+svscan_max_length=0
+svscan_length=0
 while read line
 do
 	set $line
-	len=$(echo ${11} ${12} | wc -c)
+	svscan_pid=$2
+	path_len=${11}
+	t="$(realpath /proc/$svscan_pid/cwd)"
+	len=$(echo $path_len $t | wc -c)
 	if [ $len -gt $max ] ; then
 		max=$len
 	fi
-	svscan_length=$(echo ${11} | wc -c)
-	if [ -z "$sv_dirs" ] ; then
-		sv_dirs=${12}
+	svscan_length=$(echo $path_len | wc -c)
+	if [ $svscan_max_length -gt $svscan_length ] ; then
+		svscan_length=$svscan_max_length
 	else
-		sv_dirs="$sv_dirs ${12}"
+		m=$svscan_length
+	fi
+	if [ -n "$servicedir" ] ; then
+		if [ ! "$t" = "$servicedir" ] ; then
+			continue
+		fi
+	fi
+	if [ -z "$sv_dirs" ] ; then
+		sv_dirs="$t"
+	else
+		sv_dirs=$sv_dirs "$t"
 	fi
 done < /tmp/svps.$$
 
@@ -302,28 +360,18 @@ case "$option" in
 	exit 0
 	;;
 	hup)
-	if [ ! -f $pidfile ] ; then
-		echo "$pidfile: No such file or directory" 1>&2
-		exit 1
-	else
-		echo "Sending HUP to svscan with PID $svpid"
-		kill -1 $svpid
-		if [ $? -ne 0 ] ; then
-			echo "Failed to send HUP signal to pid $svpid" 1>&2
-		fi
+	echo "Sending HUP to svscan with PID $svpid"
+	kill -1 $svpid
+	if [ $? -ne 0 ] ; then
+		echo "Failed to send HUP signal to pid $svpid" 1>&2
 	fi
 	exit 0
 	;;
 	term)
-	if [ ! -f $pidfile ] ; then
-		echo "$pidfile: No such file or directory" 1>&2
-		exit 1
-	else
-		echo "Sending TERM to svscan with PID $svpid"
-		kill -TERM $svpid
-		if [ $? -ne 0 ] ; then
-			echo "Failed to send HUP signal to pid $svpid" 1>&2
-		fi
+	echo "Sending TERM to svscan with PID $svpid"
+	kill -TERM $svpid
+	if [ $? -ne 0 ] ; then
+		echo "Failed to send HUP signal to pid $svpid" 1>&2
 	fi
 	exit 0
 	;;
@@ -369,11 +417,20 @@ if [ -n "$PAGER" ] ; then
 	ps axu|grep root|grep "sbin/svscan"|grep -Ev "grep|multilog|supervise" | while read line
 	do
 		set $line
-		@prefix@/bin/svstat ${12}/* ${12}/*/log \
-			${12}/.svscan/log 2>/tmp/svpserr.$$ > /tmp/svps_tmp.$$
-		grep -Ev "\.\.|^wait until" /tmp/svps_tmp.$$ > /tmp/svps.$$
-		/bin/rm -f /tmp/svps_tmp.$$
-		doit $2 ${12} $option
+		pid=$2
+		if [ $display_tree -eq 1 ] ; then
+			echo ""
+			printf "Process Tree for PID %10d\n" $pid
+			echo "==============================="
+			pstree -aAcpglnsTu $2
+		else
+			svdir=$(realpath /proc/$pid/cwd)
+			@prefix@/bin/svstat $svdir/* $svdir/*/log \
+				$svdir/.svscan/log 2>/tmp/svpserr.$$ > /tmp/svps_tmp.$$
+			grep -Ev "\.\.|^wait until" /tmp/svps_tmp.$$ > /tmp/svps.$$
+			/bin/rm -f /tmp/svps_tmp.$$
+			doit $2 $svdir $option
+		fi
 	done
 	) | $PAGER
 else
@@ -381,17 +438,29 @@ else
 	ps axu|grep root|grep "sbin/svscan"|grep -Ev "grep|multilog|supervise" | while read line
 	do
 		set $line
-		@prefix@/bin/svstat ${12}/* ${12}/*/log \
-			${12}/.svscan/log 2>/tmp/svpserr.$$ > /tmp/svps_tmp.$$
-		grep -Ev "\.\.|^wait until" /tmp/svps_tmp.$$ > /tmp/svps.$$
-		/bin/rm -f /tmp/svps_tmp.$$
-		doit $2 ${12} $option
+		pid=$2
+		if [ $display_tree -eq 1 ] ; then
+			echo ""
+			printf "Process Tree for PID %10d\n" $pid
+			echo "==============================="
+			pstree -aAcpglnsTu $2
+		else
+			svdir=$(realpath /proc/$pid/cwd)
+			@prefix@/bin/svstat $svdir/* $svdir/*/log \
+				$svdir/.svscan/log 2>/tmp/svpserr.$$ > /tmp/svps_tmp.$$
+			grep -Ev "\.\.|^wait until" /tmp/svps_tmp.$$ > /tmp/svps.$$
+			/bin/rm -f /tmp/svps_tmp.$$
+			doit $2 $svdir $option
+		fi
 	done
 fi
 
 /bin/rm -f /tmp/svps.$$ /tmp/svpserr.$$
 #
 # $Log: svps.in,v $
+# Revision 1.24  2026-01-09 18:12:44+05:30  Cprogrammer
+# use /proc/pid/cwd to get service directory
+#
 # Revision 1.23  2024-10-24 18:06:23+05:30  Cprogrammer
 # hide container processes
 #
